// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: proto/packet_processing.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PacketProcessingService_ProcessPacket_FullMethodName = "/tlsproxy.PacketProcessingService/ProcessPacket"
)

// PacketProcessingServiceClient is the client API for PacketProcessingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Packet Processing Service - Receives packets from Packet Capture Engine
type PacketProcessingServiceClient interface {
	// Process an intercepted packet
	ProcessPacket(ctx context.Context, in *PacketRequest, opts ...grpc.CallOption) (*PacketResponse, error)
}

type packetProcessingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPacketProcessingServiceClient(cc grpc.ClientConnInterface) PacketProcessingServiceClient {
	return &packetProcessingServiceClient{cc}
}

func (c *packetProcessingServiceClient) ProcessPacket(ctx context.Context, in *PacketRequest, opts ...grpc.CallOption) (*PacketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PacketResponse)
	err := c.cc.Invoke(ctx, PacketProcessingService_ProcessPacket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PacketProcessingServiceServer is the server API for PacketProcessingService service.
// All implementations must embed UnimplementedPacketProcessingServiceServer
// for forward compatibility.
//
// Packet Processing Service - Receives packets from Packet Capture Engine
type PacketProcessingServiceServer interface {
	// Process an intercepted packet
	ProcessPacket(context.Context, *PacketRequest) (*PacketResponse, error)
	mustEmbedUnimplementedPacketProcessingServiceServer()
}

// UnimplementedPacketProcessingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPacketProcessingServiceServer struct{}

func (UnimplementedPacketProcessingServiceServer) ProcessPacket(context.Context, *PacketRequest) (*PacketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessPacket not implemented")
}
func (UnimplementedPacketProcessingServiceServer) mustEmbedUnimplementedPacketProcessingServiceServer() {
}
func (UnimplementedPacketProcessingServiceServer) testEmbeddedByValue() {}

// UnsafePacketProcessingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PacketProcessingServiceServer will
// result in compilation errors.
type UnsafePacketProcessingServiceServer interface {
	mustEmbedUnimplementedPacketProcessingServiceServer()
}

func RegisterPacketProcessingServiceServer(s grpc.ServiceRegistrar, srv PacketProcessingServiceServer) {
	// If the following call panics, it indicates UnimplementedPacketProcessingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PacketProcessingService_ServiceDesc, srv)
}

func _PacketProcessingService_ProcessPacket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PacketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PacketProcessingServiceServer).ProcessPacket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PacketProcessingService_ProcessPacket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PacketProcessingServiceServer).ProcessPacket(ctx, req.(*PacketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PacketProcessingService_ServiceDesc is the grpc.ServiceDesc for PacketProcessingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PacketProcessingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tlsproxy.PacketProcessingService",
	HandlerType: (*PacketProcessingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessPacket",
			Handler:    _PacketProcessingService_ProcessPacket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/packet_processing.proto",
}
