// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/packet_processing.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketAction int32

const (
	PacketAction_FORWARD PacketAction = 0 // Forward packet normally
	PacketAction_DROP    PacketAction = 1 // Drop the packet
	PacketAction_INJECT  PacketAction = 2 // Inject modified packet (HTTP redirect)
	PacketAction_BLOCK   PacketAction = 3 // Block and send RST
)

// Enum value maps for PacketAction.
var (
	PacketAction_name = map[int32]string{
		0: "FORWARD",
		1: "DROP",
		2: "INJECT",
		3: "BLOCK",
	}
	PacketAction_value = map[string]int32{
		"FORWARD": 0,
		"DROP":    1,
		"INJECT":  2,
		"BLOCK":   3,
	}
)

func (x PacketAction) Enum() *PacketAction {
	p := new(PacketAction)
	*p = x
	return p
}

func (x PacketAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_packet_processing_proto_enumTypes[0].Descriptor()
}

func (PacketAction) Type() protoreflect.EnumType {
	return &file_proto_packet_processing_proto_enumTypes[0]
}

func (x PacketAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketAction.Descriptor instead.
func (PacketAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_packet_processing_proto_rawDescGZIP(), []int{0}
}

type PacketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawPacket     []byte                 `protobuf:"bytes,1,opt,name=raw_packet,json=rawPacket,proto3" json:"raw_packet,omitempty"`             // Raw packet data
	SourceIp      string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`                // Source IP address
	DestIp        string                 `protobuf:"bytes,3,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`                      // Destination IP address
	SourcePort    uint32                 `protobuf:"varint,4,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`         // Source port
	DestPort      uint32                 `protobuf:"varint,5,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`               // Destination port
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`                                // TCP, UDP, ICMP
	InterfaceName string                 `protobuf:"bytes,7,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"` // Network interface
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                             // Packet capture timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketRequest) Reset() {
	*x = PacketRequest{}
	mi := &file_proto_packet_processing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketRequest) ProtoMessage() {}

func (x *PacketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packet_processing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketRequest.ProtoReflect.Descriptor instead.
func (*PacketRequest) Descriptor() ([]byte, []int) {
	return file_proto_packet_processing_proto_rawDescGZIP(), []int{0}
}

func (x *PacketRequest) GetRawPacket() []byte {
	if x != nil {
		return x.RawPacket
	}
	return nil
}

func (x *PacketRequest) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *PacketRequest) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *PacketRequest) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *PacketRequest) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *PacketRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PacketRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *PacketRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PacketResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Action         PacketAction           `protobuf:"varint,1,opt,name=action,proto3,enum=tlsproxy.PacketAction" json:"action,omitempty"`           // What to do with the packet
	ModifiedPacket []byte                 `protobuf:"bytes,2,opt,name=modified_packet,json=modifiedPacket,proto3" json:"modified_packet,omitempty"` // Modified/injected packet (if action = INJECT)
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                                       // Reason for the action
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PacketResponse) Reset() {
	*x = PacketResponse{}
	mi := &file_proto_packet_processing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketResponse) ProtoMessage() {}

func (x *PacketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_packet_processing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketResponse.ProtoReflect.Descriptor instead.
func (*PacketResponse) Descriptor() ([]byte, []int) {
	return file_proto_packet_processing_proto_rawDescGZIP(), []int{1}
}

func (x *PacketResponse) GetAction() PacketAction {
	if x != nil {
		return x.Action
	}
	return PacketAction_FORWARD
}

func (x *PacketResponse) GetModifiedPacket() []byte {
	if x != nil {
		return x.ModifiedPacket
	}
	return nil
}

func (x *PacketResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_packet_processing_proto protoreflect.FileDescriptor

const file_proto_packet_processing_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/packet_processing.proto\x12\btlsproxy\"\x83\x02\n" +
	"\rPacketRequest\x12\x1d\n" +
	"\n" +
	"raw_packet\x18\x01 \x01(\fR\trawPacket\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x17\n" +
	"\adest_ip\x18\x03 \x01(\tR\x06destIp\x12\x1f\n" +
	"\vsource_port\x18\x04 \x01(\rR\n" +
	"sourcePort\x12\x1b\n" +
	"\tdest_port\x18\x05 \x01(\rR\bdestPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12%\n" +
	"\x0einterface_name\x18\a \x01(\tR\rinterfaceName\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"\x81\x01\n" +
	"\x0ePacketResponse\x12.\n" +
	"\x06action\x18\x01 \x01(\x0e2\x16.tlsproxy.PacketActionR\x06action\x12'\n" +
	"\x0fmodified_packet\x18\x02 \x01(\fR\x0emodifiedPacket\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason*<\n" +
	"\fPacketAction\x12\v\n" +
	"\aFORWARD\x10\x00\x12\b\n" +
	"\x04DROP\x10\x01\x12\n" +
	"\n" +
	"\x06INJECT\x10\x02\x12\t\n" +
	"\x05BLOCK\x10\x032]\n" +
	"\x17PacketProcessingService\x12B\n" +
	"\rProcessPacket\x12\x17.tlsproxy.PacketRequest\x1a\x18.tlsproxy.PacketResponseB\x11Z\x0ftls_proxy/protob\x06proto3"

var (
	file_proto_packet_processing_proto_rawDescOnce sync.Once
	file_proto_packet_processing_proto_rawDescData []byte
)

func file_proto_packet_processing_proto_rawDescGZIP() []byte {
	file_proto_packet_processing_proto_rawDescOnce.Do(func() {
		file_proto_packet_processing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_packet_processing_proto_rawDesc), len(file_proto_packet_processing_proto_rawDesc)))
	})
	return file_proto_packet_processing_proto_rawDescData
}

var file_proto_packet_processing_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_packet_processing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_packet_processing_proto_goTypes = []any{
	(PacketAction)(0),      // 0: tlsproxy.PacketAction
	(*PacketRequest)(nil),  // 1: tlsproxy.PacketRequest
	(*PacketResponse)(nil), // 2: tlsproxy.PacketResponse
}
var file_proto_packet_processing_proto_depIdxs = []int32{
	0, // 0: tlsproxy.PacketResponse.action:type_name -> tlsproxy.PacketAction
	1, // 1: tlsproxy.PacketProcessingService.ProcessPacket:input_type -> tlsproxy.PacketRequest
	2, // 2: tlsproxy.PacketProcessingService.ProcessPacket:output_type -> tlsproxy.PacketResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_packet_processing_proto_init() }
func file_proto_packet_processing_proto_init() {
	if File_proto_packet_processing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_packet_processing_proto_rawDesc), len(file_proto_packet_processing_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_packet_processing_proto_goTypes,
		DependencyIndexes: file_proto_packet_processing_proto_depIdxs,
		EnumInfos:         file_proto_packet_processing_proto_enumTypes,
		MessageInfos:      file_proto_packet_processing_proto_msgTypes,
	}.Build()
	File_proto_packet_processing_proto = out.File
	file_proto_packet_processing_proto_goTypes = nil
	file_proto_packet_processing_proto_depIdxs = nil
}
