package distribution

import (
	"bytes"
	"errors"
	"fmt"
	"net/url"
	"strings"
	"text/template"
)

// ============================================================================
// Script Configuration
// ============================================================================

// ScriptConfig contains parameters for script template rendering.
type ScriptConfig struct {
	BaseURL         string // HTTP server base URL (e.g., "http://192.168.1.1")
	CACertURL       string // Full URL to CA certificate (e.g., "http://192.168.1.1/ca.crt")
	CADerURL        string // Full URL to DER format certificate
	CertificateName string // CA certificate display name (e.g., "SafeOps Root CA")
	Organization    string // Organization name for display
	RequiresSudo    bool   // Whether script needs root privileges
	Fingerprint     string // SHA-256 fingerprint for verification (optional)
}

// ============================================================================
// Error Types
// ============================================================================

var (
	ErrEmptyBaseURL      = errors.New("base URL cannot be empty")
	ErrEmptyCertURL      = errors.New("CA certificate URL cannot be empty")
	ErrEmptyCertName     = errors.New("certificate name cannot be empty")
	ErrInvalidURL        = errors.New("invalid URL format")
	ErrTemplateExecution = errors.New("template execution failed")
)

// ============================================================================
// Linux Script Template
// ============================================================================

const linuxScriptTemplate = `#!/bin/bash
# SafeOps Root CA Installation Script for Linux
# Generated by SafeOps Certificate Manager
# Organization: {{.Organization}}
#
# Usage: sudo ./install-ca.sh

set -e  # Exit on error

CA_URL="{{.CACertURL}}"
CA_NAME="{{.CertificateName}}"
CERT_DIR="/usr/local/share/ca-certificates"
CERT_FILE="$CERT_DIR/safeops-root-ca.crt"

echo "=================================================="
echo " SafeOps Root CA Installation Script"
echo "=================================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "ERROR: Please run as root (sudo ./install-ca.sh)"
    exit 1
fi

# Create certificate directory if needed
mkdir -p "$CERT_DIR"

# Download CA certificate
echo "[1/3] Downloading CA certificate..."
if command -v curl >/dev/null 2>&1; then
    curl -fsSL -o "$CERT_FILE" "$CA_URL"
elif command -v wget >/dev/null 2>&1; then
    wget -q -O "$CERT_FILE" "$CA_URL"
else
    echo "ERROR: Neither curl nor wget found. Please install one."
    exit 1
fi

if [ ! -f "$CERT_FILE" ]; then
    echo "ERROR: Failed to download certificate"
    exit 1
fi

# Set correct permissions
chmod 644 "$CERT_FILE"

# Update CA trust store
echo "[2/3] Updating system CA trust store..."
if command -v update-ca-certificates >/dev/null 2>&1; then
    # Debian/Ubuntu
    update-ca-certificates
elif command -v update-ca-trust >/dev/null 2>&1; then
    # RHEL/CentOS/Fedora
    cp "$CERT_FILE" /etc/pki/ca-trust/source/anchors/
    update-ca-trust
else
    echo "ERROR: Could not find update-ca-certificates or update-ca-trust"
    echo "Please manually add $CERT_FILE to your system trust store"
    exit 1
fi

# Verification
echo "[3/3] Verifying installation..."
if [ -f "$CERT_FILE" ]; then
    echo ""
    echo "=================================================="
    echo " Installation Complete!"
    echo "=================================================="
    echo "✓ Certificate: $CA_NAME"
    echo "✓ Location: $CERT_FILE"
    echo "✓ Status: Trusted"
    {{if .Fingerprint}}echo "✓ Fingerprint: {{.Fingerprint}}"{{end}}
    echo ""
    echo "You may need to restart your browser for changes to take effect."
else
    echo "ERROR: Certificate verification failed"
    exit 1
fi
`

// ============================================================================
// Windows Script Template
// ============================================================================

const windowsScriptTemplate = `# SafeOps Root CA Installation Script for Windows
# Generated by SafeOps Certificate Manager
# Organization: {{.Organization}}
#
# Usage: Right-click -> Run as Administrator

$ErrorActionPreference = "Stop"

$caUrl = "{{.CACertURL}}"
$caName = "{{.CertificateName}}"
$tempFile = "$env:TEMP\safeops-ca.crt"

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host " SafeOps Root CA Installation Script" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as Administrator
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "ERROR: Please run as Administrator" -ForegroundColor Red
    Write-Host "Right-click the script -> Run as Administrator" -ForegroundColor Yellow
    pause
    exit 1
}

try {
    # Download CA certificate
    Write-Host "[1/3] Downloading CA certificate..." -ForegroundColor White
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $caUrl -OutFile $tempFile -UseBasicParsing

    if (-not (Test-Path $tempFile)) {
        throw "Failed to download certificate"
    }

    # Import certificate to Trusted Root store
    Write-Host "[2/3] Installing CA certificate to Trusted Root store..." -ForegroundColor White
    
    if (Get-Command Import-Certificate -ErrorAction SilentlyContinue) {
        # Windows 8+ / PowerShell 4+
        $cert = Import-Certificate -FilePath $tempFile -CertStoreLocation Cert:\LocalMachine\Root
        Write-Host "   Imported using Import-Certificate cmdlet" -ForegroundColor Gray
    } else {
        # Windows 7 / older PowerShell (use certutil)
        $result = certutil -addstore -f "Root" $tempFile
        if ($LASTEXITCODE -ne 0) {
            throw "certutil failed with exit code $LASTEXITCODE"
        }
        Write-Host "   Imported using certutil" -ForegroundColor Gray
    }

    # Cleanup
    Write-Host "[3/3] Cleaning up..." -ForegroundColor White
    Remove-Item $tempFile -Force -ErrorAction SilentlyContinue

    # Success
    Write-Host ""
    Write-Host "==================================================" -ForegroundColor Green
    Write-Host " Installation Complete!" -ForegroundColor Green
    Write-Host "==================================================" -ForegroundColor Green
    Write-Host "✓ Certificate: $caName" -ForegroundColor Green
    Write-Host "✓ Store: Trusted Root Certification Authorities" -ForegroundColor Green
    Write-Host "✓ Status: Trusted" -ForegroundColor Green
    {{if .Fingerprint}}Write-Host "✓ Fingerprint: {{.Fingerprint}}" -ForegroundColor Green{{end}}
    Write-Host ""
    Write-Host "You may need to restart your browser for changes to take effect." -ForegroundColor Yellow

} catch {
    Write-Host ""
    Write-Host "ERROR: Installation failed" -ForegroundColor Red
    Write-Host $_.Exception.Message -ForegroundColor Red
    
    # Cleanup on error
    if (Test-Path $tempFile) {
        Remove-Item $tempFile -Force -ErrorAction SilentlyContinue
    }
    
    pause
    exit 1
}

Write-Host ""
Write-Host "Press any key to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
`

// ============================================================================
// macOS Script Template
// ============================================================================

const macScriptTemplate = `#!/bin/bash
# SafeOps Root CA Installation Script for macOS
# Generated by SafeOps Certificate Manager
# Organization: {{.Organization}}
#
# Usage: ./install-ca-mac.sh (will prompt for admin password)

set -e

CA_URL="{{.CACertURL}}"
CA_NAME="{{.CertificateName}}"
TEMP_FILE="/tmp/safeops-ca.crt"

echo "=================================================="
echo " SafeOps Root CA Installation Script for macOS"
echo "=================================================="
echo ""

# Download CA certificate
echo "[1/3] Downloading CA certificate..."
curl -fsSL -o "$TEMP_FILE" "$CA_URL"

if [ ! -f "$TEMP_FILE" ]; then
    echo "ERROR: Failed to download certificate"
    exit 1
fi

# Install to System keychain with admin trust
echo "[2/3] Installing CA certificate to System keychain..."
echo "(You may be prompted for your admin password)"
sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain "$TEMP_FILE"

# Cleanup
echo "[3/3] Cleaning up..."
rm -f "$TEMP_FILE"

# Success
echo ""
echo "=================================================="
echo " Installation Complete!"
echo "=================================================="
echo "✓ Certificate: $CA_NAME"
echo "✓ Keychain: System"
echo "✓ Trust: Root CA"
{{if .Fingerprint}}echo "✓ Fingerprint: {{.Fingerprint}}"{{end}}
echo ""
echo "You may need to restart your browser for changes to take effect."
`

// ============================================================================
// ChromeOS Instructions Template
// ============================================================================

const chromeosInstructionsTemplate = `SafeOps Root CA Installation Instructions for ChromeOS
======================================================
Organization: {{.Organization}}

Since ChromeOS does not support scripted CA installation,
please follow these manual steps:

Step 1: Download the CA Certificate
------------------------------------
Open Chrome and navigate to:
  {{.CACertURL}}

Save the file when prompted.

Step 2: Open Settings
---------------------
1. Click the time in the bottom-right corner
2. Click the Settings icon (gear)

Step 3: Navigate to Security
----------------------------
1. Click "Security and Privacy" in the left sidebar
2. Click "Security"
3. Click "Manage certificates"

Step 4: Import Certificate
--------------------------
1. Click the "Authorities" tab
2. Click "Import"
3. Select the downloaded safeops-ca.crt file
4. Check "Trust this certificate for identifying websites"
5. Click "OK"

Step 5: Verify Installation
---------------------------
You should now see "{{.CertificateName}}" in the authorities list.
Close and reopen your browser for changes to take effect.

{{if .Fingerprint}}
Certificate Fingerprint (SHA-256):
{{.Fingerprint}}
{{end}}

Note: ChromeOS enterprise environments can push CA certificates
via Google Admin console policy.

For assistance, contact your IT administrator.
`

// ============================================================================
// Firefox Script Template
// ============================================================================

const firefoxScriptTemplate = `#!/bin/bash
# SafeOps Root CA Installation Script for Firefox
# Generated by SafeOps Certificate Manager
# Organization: {{.Organization}}
#
# Note: Firefox uses its own certificate store, separate from the system store.
# This script requires NSS tools (certutil).

set -e

CA_URL="{{.CACertURL}}"
CA_NAME="{{.CertificateName}}"
TEMP_FILE="/tmp/safeops-ca.crt"

echo "=================================================="
echo " SafeOps Root CA Installation Script for Firefox"
echo "=================================================="
echo ""

# Download certificate
echo "[1/4] Downloading CA certificate..."
if command -v curl >/dev/null 2>&1; then
    curl -fsSL -o "$TEMP_FILE" "$CA_URL"
elif command -v wget >/dev/null 2>&1; then
    wget -q -O "$TEMP_FILE" "$CA_URL"
else
    echo "ERROR: Neither curl nor wget found"
    exit 1
fi

# Find Firefox profile directory
echo "[2/4] Looking for Firefox profiles..."
PROFILE_DIR=""
if [ "$(uname)" = "Darwin" ]; then
    # macOS
    PROFILE_DIR="$HOME/Library/Application Support/Firefox/Profiles"
elif [ "$(uname)" = "Linux" ]; then
    # Linux
    PROFILE_DIR="$HOME/.mozilla/firefox"
else
    echo "ERROR: Unsupported operating system"
    exit 1
fi

if [ ! -d "$PROFILE_DIR" ]; then
    echo "ERROR: Firefox profile directory not found: $PROFILE_DIR"
    echo "Please ensure Firefox has been run at least once."
    exit 1
fi

# Check if certutil is available
echo "[3/4] Checking for NSS certutil..."
if ! command -v certutil >/dev/null 2>&1; then
    echo ""
    echo "ERROR: certutil not found. Please install NSS tools:"
    echo ""
    echo "  Ubuntu/Debian:  sudo apt install libnss3-tools"
    echo "  RHEL/CentOS:    sudo yum install nss-tools"
    echo "  Fedora:         sudo dnf install nss-tools"
    echo "  macOS:          brew install nss"
    echo ""
    rm -f "$TEMP_FILE"
    exit 1
fi

# Import to all Firefox profiles
echo "[4/4] Installing to Firefox profiles..."
INSTALLED=0
for profile in "$PROFILE_DIR"/*.default* "$PROFILE_DIR"/*.dev-edition* "$PROFILE_DIR"/*.esr*; do
    if [ -d "$profile" ]; then
        echo "   Installing to: $(basename "$profile")"
        certutil -A -n "$CA_NAME" -t "C,," -i "$TEMP_FILE" -d sql:"$profile" 2>/dev/null || true
        INSTALLED=$((INSTALLED + 1))
    fi
done

# Cleanup
rm -f "$TEMP_FILE"

# Result
echo ""
if [ $INSTALLED -gt 0 ]; then
    echo "=================================================="
    echo " Installation Complete!"
    echo "=================================================="
    echo "✓ Certificate: $CA_NAME"
    echo "✓ Installed to: $INSTALLED Firefox profile(s)"
    echo "✓ Trust: SSL/TLS CA"
    {{if .Fingerprint}}echo "✓ Fingerprint: {{.Fingerprint}}"{{end}}
    echo ""
    echo "Please restart Firefox for changes to take effect."
else
    echo "WARNING: No Firefox profiles found to install to."
    echo "Please run Firefox at least once, then run this script again."
    exit 1
fi
`

// ============================================================================
// Script Generation Functions
// ============================================================================

// GenerateLinuxScript generates a Bash script for Linux CA installation.
func GenerateLinuxScript(config *ScriptConfig) (string, error) {
	if err := ValidateScriptConfig(config); err != nil {
		return "", fmt.Errorf("GenerateLinuxScript: %w", err)
	}
	return renderTemplate(linuxScriptTemplate, config)
}

// GenerateWindowsScript generates a PowerShell script for Windows CA installation.
func GenerateWindowsScript(config *ScriptConfig) (string, error) {
	if err := ValidateScriptConfig(config); err != nil {
		return "", fmt.Errorf("GenerateWindowsScript: %w", err)
	}
	return renderTemplate(windowsScriptTemplate, config)
}

// GenerateMacScript generates a shell script for macOS CA installation.
func GenerateMacScript(config *ScriptConfig) (string, error) {
	if err := ValidateScriptConfig(config); err != nil {
		return "", fmt.Errorf("GenerateMacScript: %w", err)
	}
	return renderTemplate(macScriptTemplate, config)
}

// GenerateChromeOSScript generates instructions for ChromeOS CA installation.
func GenerateChromeOSScript(config *ScriptConfig) (string, error) {
	if err := ValidateScriptConfig(config); err != nil {
		return "", fmt.Errorf("GenerateChromeOSScript: %w", err)
	}
	return renderTemplate(chromeosInstructionsTemplate, config)
}

// GenerateFirefoxScript generates a script for Firefox CA installation.
func GenerateFirefoxScript(config *ScriptConfig) (string, error) {
	if err := ValidateScriptConfig(config); err != nil {
		return "", fmt.Errorf("GenerateFirefoxScript: %w", err)
	}
	return renderTemplate(firefoxScriptTemplate, config)
}

// ============================================================================
// Bulk Generation
// ============================================================================

// GenerateAllScripts generates all platform scripts in a single call.
// Returns a map of platform name to script content.
func GenerateAllScripts(config *ScriptConfig) (map[string]string, error) {
	if err := ValidateScriptConfig(config); err != nil {
		return nil, fmt.Errorf("GenerateAllScripts: %w", err)
	}

	scripts := make(map[string]string)

	// Generate Linux script
	linux, err := GenerateLinuxScript(config)
	if err != nil {
		return nil, fmt.Errorf("GenerateAllScripts: linux: %w", err)
	}
	scripts["linux"] = linux

	// Generate Windows script
	windows, err := GenerateWindowsScript(config)
	if err != nil {
		return nil, fmt.Errorf("GenerateAllScripts: windows: %w", err)
	}
	scripts["windows"] = windows

	// Generate macOS script
	macos, err := GenerateMacScript(config)
	if err != nil {
		return nil, fmt.Errorf("GenerateAllScripts: macos: %w", err)
	}
	scripts["macos"] = macos

	// Generate ChromeOS instructions
	chromeos, err := GenerateChromeOSScript(config)
	if err != nil {
		return nil, fmt.Errorf("GenerateAllScripts: chromeos: %w", err)
	}
	scripts["chromeos"] = chromeos

	// Generate Firefox script
	firefox, err := GenerateFirefoxScript(config)
	if err != nil {
		return nil, fmt.Errorf("GenerateAllScripts: firefox: %w", err)
	}
	scripts["firefox"] = firefox

	return scripts, nil
}

// ============================================================================
// Validation
// ============================================================================

// ValidateScriptConfig validates the script configuration.
func ValidateScriptConfig(config *ScriptConfig) error {
	if config == nil {
		return errors.New("config cannot be nil")
	}

	if strings.TrimSpace(config.BaseURL) == "" {
		return ErrEmptyBaseURL
	}

	if strings.TrimSpace(config.CACertURL) == "" {
		return ErrEmptyCertURL
	}

	if strings.TrimSpace(config.CertificateName) == "" {
		return ErrEmptyCertName
	}

	// Validate URL formats
	if _, err := url.Parse(config.BaseURL); err != nil {
		return fmt.Errorf("%w: BaseURL: %v", ErrInvalidURL, err)
	}

	if _, err := url.Parse(config.CACertURL); err != nil {
		return fmt.Errorf("%w: CACertURL: %v", ErrInvalidURL, err)
	}

	return nil
}

// ============================================================================
// Template Rendering Helper
// ============================================================================

// renderTemplate executes a Go template with the given config.
func renderTemplate(templateStr string, config *ScriptConfig) (string, error) {
	tmpl, err := template.New("script").Parse(templateStr)
	if err != nil {
		return "", fmt.Errorf("%w: parse error: %v", ErrTemplateExecution, err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, config); err != nil {
		return "", fmt.Errorf("%w: execute error: %v", ErrTemplateExecution, err)
	}

	return buf.String(), nil
}

// ============================================================================
// Utility Functions
// ============================================================================

// NewScriptConfig creates a new ScriptConfig with default values.
func NewScriptConfig(baseURL string) *ScriptConfig {
	// Ensure baseURL doesn't end with slash
	baseURL = strings.TrimSuffix(baseURL, "/")

	return &ScriptConfig{
		BaseURL:         baseURL,
		CACertURL:       baseURL + "/ca.crt",
		CADerURL:        baseURL + "/ca.der",
		CertificateName: "SafeOps Root CA",
		Organization:    "SafeOps",
		RequiresSudo:    true,
	}
}

// WithFingerprint adds a fingerprint to the script configuration.
func (c *ScriptConfig) WithFingerprint(fingerprint string) *ScriptConfig {
	c.Fingerprint = fingerprint
	return c
}

// WithOrganization sets the organization name.
func (c *ScriptConfig) WithOrganization(org string) *ScriptConfig {
	c.Organization = org
	return c
}

// WithCertificateName sets the certificate display name.
func (c *ScriptConfig) WithCertificateName(name string) *ScriptConfig {
	c.CertificateName = name
	return c
}

// ============================================================================
// Script File Names
// ============================================================================

// ScriptFileNames returns the recommended file names for each platform.
func ScriptFileNames() map[string]string {
	return map[string]string{
		"linux":    "install-ca.sh",
		"windows":  "install-ca.ps1",
		"macos":    "install-ca-mac.sh",
		"chromeos": "install-ca-chromeos.txt",
		"firefox":  "install-ca-firefox.sh",
	}
}

// ScriptContentTypes returns the MIME content types for each platform script.
func ScriptContentTypes() map[string]string {
	return map[string]string{
		"linux":    "application/x-sh",
		"windows":  "application/x-powershell",
		"macos":    "application/x-sh",
		"chromeos": "text/plain",
		"firefox":  "application/x-sh",
	}
}
