# ============================================================================
# SafeOps Captive Portal - Self-Signed Certificate Generator
# ============================================================================
# File: D:\SafeOpsFV2\src\captive_portal\scripts\generate_cert.ps1
# Purpose: Generate self-signed TLS certificate for Captive Portal HTTPS
# 
# Why Self-Signed?
#   - Captive Portal serves devices BEFORE they have the Root CA installed
#   - Cannot use Step-CA signed cert (chicken-and-egg problem)
#   - Users will see browser warning, must click "Proceed anyway"
#   - This is expected and acceptable for captive portal flows
#
# Certificate Details:
#   - Algorithm: RSA 2048-bit (compatible with all browsers)
#   - Validity: 1 year (365 days)
#   - Subject: CN=captive.safeops.local
#   - SANs: DNS and IP addresses for portal access
#
# Usage:
#   .\scripts\generate_cert.ps1
#   .\scripts\generate_cert.ps1 -Regenerate
#
# Prerequisites:
#   - OpenSSL 3.x installed and in PATH
#
# Author: SafeOps Phase 3A
# Date: 2026-01-03
# ============================================================================

[CmdletBinding()]
param(
    # Force regeneration even if certificates exist
    [Parameter()]
    [switch]$Regenerate,

    # Certificate validity in days
    [Parameter()]
    [int]$ValidityDays = 365,

    # RSA key size
    [Parameter()]
    [ValidateSet(2048, 4096)]
    [int]$KeySize = 2048,

    # Primary hostname
    [Parameter()]
    [string]$CommonName = "captive.safeops.local",

    # Output directory
    [Parameter()]
    [string]$OutputDir = "D:\SafeOpsFV2\src\captive_portal\internal\certs"
)

# ============================================================================
# Configuration
# ============================================================================

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# Certificate file paths
$keyFile = Join-Path $OutputDir "server.key"
$certFile = Join-Path $OutputDir "server.crt"
$csrFile = Join-Path $OutputDir "server.csr"
$configFile = Join-Path $OutputDir "openssl.cnf"

# Subject Alternative Names (SANs)
# These are all the ways users might access the captive portal
$sanDNS = @(
    "captive.safeops.local",
    "portal.safeops.local",
    "safeops.local",
    "localhost"
)

$sanIP = @(
    "192.168.137.1",   # Mobile Hotspot gateway IP
    "127.0.0.1"        # Localhost
)

# ============================================================================
# Functions
# ============================================================================

function Write-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
    Write-Host "  $Message" -ForegroundColor Cyan
    Write-Host "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "  ✅ $Message" -ForegroundColor Green
}

function Write-Info {
    param([string]$Message)
    Write-Host "  ℹ️  $Message" -ForegroundColor Yellow
}

function Write-Detail {
    param([string]$Message)
    Write-Host "     $Message" -ForegroundColor Gray
}

function Test-OpenSSL {
    <#
    .SYNOPSIS
        Verify OpenSSL is installed and accessible
    #>
    try {
        $version = & openssl version 2>&1
        if ($LASTEXITCODE -ne 0) {
            throw "OpenSSL command failed"
        }
        return $version
    }
    catch {
        throw "OpenSSL is not installed or not in PATH. Install from: https://slproweb.com/products/Win32OpenSSL.html"
    }
}

function New-OpenSSLConfig {
    <#
    .SYNOPSIS
        Create OpenSSL configuration file with SANs
    .DESCRIPTION
        Generates a temporary openssl.cnf with proper Subject Alternative Names
        for the captive portal certificate. This is required because -subj alone
        doesn't support SANs in older OpenSSL versions.
    #>
    
    # Build SAN string
    $sanEntries = @()
    $index = 1
    
    foreach ($dns in $sanDNS) {
        $sanEntries += "DNS.$index = $dns"
        $index++
    }
    
    $ipIndex = 1
    foreach ($ip in $sanIP) {
        $sanEntries += "IP.$ipIndex = $ip"
        $ipIndex++
    }
    
    $sanString = $sanEntries -join "`n"

    # OpenSSL configuration content
    $configContent = @"
# OpenSSL Configuration for SafeOps Captive Portal Certificate
# Auto-generated by generate_cert.ps1

[req]
default_bits = $KeySize
prompt = no
default_md = sha256
distinguished_name = dn
x509_extensions = v3_req
req_extensions = v3_req

[dn]
C = US
ST = California
L = San Francisco
O = SafeOps Security
OU = Network Security
CN = $CommonName

[v3_req]
# Key Usage for TLS server certificate
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth

# Subject Alternative Names
subjectAltName = @alt_names

# Basic constraints (not a CA)
basicConstraints = critical, CA:FALSE

# Subject Key Identifier
subjectKeyIdentifier = hash

[alt_names]
$sanString
"@

    # Write configuration file
    $configContent | Out-File -FilePath $configFile -Encoding ASCII -Force
    Write-Detail "Created OpenSSL config: $configFile"
    
    return $configFile
}

function New-PrivateKey {
    <#
    .SYNOPSIS
        Generate RSA private key
    .DESCRIPTION
        Creates an unencrypted RSA private key for HTTPS server.
        Unencrypted so the Captive Portal can start without password prompt.
    #>
    
    Write-Info "Generating $KeySize-bit RSA private key..."
    
    & openssl genrsa -out $keyFile $KeySize 2>&1 | Out-Null
    
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to generate private key"
    }
    
    # Set restrictive permissions (Windows)
    try {
        $acl = Get-Acl $keyFile
        $acl.SetAccessRuleProtection($true, $false)
        
        # Remove all existing rules
        $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }
        
        # Add Administrator access only
        $adminRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            "BUILTIN\Administrators", "FullControl", "Allow"
        )
        $acl.AddAccessRule($adminRule)
        
        # Add SYSTEM access
        $systemRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            "NT AUTHORITY\SYSTEM", "FullControl", "Allow"
        )
        $acl.AddAccessRule($systemRule)
        
        Set-Acl $keyFile $acl
        Write-Detail "Set restrictive permissions on private key"
    }
    catch {
        Write-Warning "Could not set restrictive permissions: $_"
    }
    
    Write-Success "Private key generated: $keyFile"
}

function New-SelfSignedCertificate {
    <#
    .SYNOPSIS
        Generate self-signed certificate using OpenSSL
    .DESCRIPTION
        Creates a self-signed X.509 certificate with:
        - RSA 2048-bit key
        - SHA-256 signature
        - Subject Alternative Names for all portal access methods
        - 1 year validity
    #>
    
    Write-Info "Generating self-signed certificate..."
    Write-Detail "Common Name: $CommonName"
    Write-Detail "Validity: $ValidityDays days"
    Write-Detail "DNS SANs: $($sanDNS -join ', ')"
    Write-Detail "IP SANs: $($sanIP -join ', ')"
    
    # Generate certificate
    & openssl req -new -x509 `
        -key $keyFile `
        -out $certFile `
        -days $ValidityDays `
        -config $configFile `
        -extensions v3_req 2>&1 | Out-Null
    
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to generate certificate"
    }
    
    Write-Success "Certificate generated: $certFile"
}

function Show-CertificateInfo {
    <#
    .SYNOPSIS
        Display certificate details
    #>
    
    Write-Step "Certificate Information"
    
    # Extract key information using OpenSSL
    $certInfo = & openssl x509 -in $certFile -text -noout 2>&1
    
    # Parse and display relevant fields
    $subject = ($certInfo | Select-String "Subject:").Line
    $issuer = ($certInfo | Select-String "Issuer:").Line
    $notBefore = ($certInfo | Select-String "Not Before:").Line
    $notAfter = ($certInfo | Select-String "Not After:").Line
    
    Write-Host ""
    Write-Host "  📜 Certificate Details:" -ForegroundColor White
    Write-Detail $subject
    Write-Detail $issuer
    Write-Detail $notBefore
    Write-Detail $notAfter
    
    Write-Host ""
    Write-Host "  🔐 Subject Alternative Names:" -ForegroundColor White
    foreach ($dns in $sanDNS) {
        Write-Detail "DNS: $dns"
    }
    foreach ($ip in $sanIP) {
        Write-Detail "IP: $ip"
    }
    
    # Get fingerprint
    $fingerprint = & openssl x509 -in $certFile -fingerprint -sha256 -noout 2>&1
    Write-Host ""
    Write-Host "  🔑 Fingerprint:" -ForegroundColor White
    Write-Detail $fingerprint
}

function Test-Certificate {
    <#
    .SYNOPSIS
        Verify the generated certificate
    #>
    
    Write-Step "Verifying Certificate"
    
    # Verify certificate is valid
    $null = & openssl x509 -in $certFile -noout 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Success "Certificate is valid X.509 format"
    }
    else {
        throw "Certificate verification failed"
    }
    
    # Verify key matches certificate
    $certModulus = & openssl x509 -in $certFile -noout -modulus 2>&1
    $keyModulus = & openssl rsa -in $keyFile -noout -modulus 2>&1
    
    if ($certModulus -eq $keyModulus) {
        Write-Success "Private key matches certificate"
    }
    else {
        throw "Private key does not match certificate!"
    }
    
    # Check expiry
    $endDate = & openssl x509 -in $certFile -noout -enddate 2>&1
    Write-Success "Certificate expiry: $($endDate -replace 'notAfter=', '')"
}

# ============================================================================
# Main Execution
# ============================================================================

Write-Host ""
Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Magenta
Write-Host "║  SafeOps Captive Portal - Certificate Generator               ║" -ForegroundColor Magenta
Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Magenta

try {
    # Step 1: Check prerequisites
    Write-Step "Checking Prerequisites"
    
    $opensslVersion = Test-OpenSSL
    Write-Success "OpenSSL found: $opensslVersion"
    
    # Step 2: Create output directory
    if (-not (Test-Path $OutputDir)) {
        New-Item -ItemType Directory -Force -Path $OutputDir | Out-Null
        Write-Success "Created output directory: $OutputDir"
    }
    
    # Step 3: Check for existing certificates
    if ((Test-Path $keyFile) -and (Test-Path $certFile) -and (-not $Regenerate)) {
        Write-Info "Certificates already exist!"
        Write-Detail "Key: $keyFile"
        Write-Detail "Cert: $certFile"
        Write-Host ""
        Write-Host "  Use -Regenerate switch to overwrite existing certificates" -ForegroundColor Yellow
        
        # Show existing certificate info
        Show-CertificateInfo
        exit 0
    }
    
    # Step 4: Generate OpenSSL config
    Write-Step "Creating OpenSSL Configuration"
    $null = New-OpenSSLConfig
    Write-Success "OpenSSL configuration created with SANs"
    
    # Step 5: Generate private key
    Write-Step "Generating Private Key"
    New-PrivateKey
    
    # Step 6: Generate certificate
    Write-Step "Generating Self-Signed Certificate"
    New-SelfSignedCertificate
    
    # Step 7: Display certificate info
    Show-CertificateInfo
    
    # Step 8: Verify certificate
    Test-Certificate
    
    # Step 9: Cleanup temporary config
    if (Test-Path $csrFile) {
        Remove-Item $csrFile -Force
    }
    
    # Final summary
    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Green
    Write-Host "║  ✅ Certificate Generation Complete!                          ║" -ForegroundColor Green
    Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Green
    Write-Host ""
    Write-Host "  Files created:" -ForegroundColor White
    Write-Host "    Private Key: $keyFile" -ForegroundColor Gray
    Write-Host "    Certificate: $certFile" -ForegroundColor Gray
    Write-Host ""
    Write-Host "  ⚠️  IMPORTANT:" -ForegroundColor Yellow
    Write-Host "    This is a self-signed certificate." -ForegroundColor Yellow
    Write-Host "    Users will see a browser security warning." -ForegroundColor Yellow
    Write-Host "    They must click 'Advanced' → 'Proceed anyway'" -ForegroundColor Yellow
    Write-Host "    This is expected behavior for captive portals." -ForegroundColor Yellow
    Write-Host ""
    
}
catch {
    Write-Host ""
    Write-Host "╔═══════════════════════════════════════════════════════════════╗" -ForegroundColor Red
    Write-Host "║  ❌ Certificate Generation Failed                             ║" -ForegroundColor Red
    Write-Host "╚═══════════════════════════════════════════════════════════════╝" -ForegroundColor Red
    Write-Host ""
    Write-Host "  Error: $_" -ForegroundColor Red
    Write-Host "  Stack: $($_.ScriptStackTrace)" -ForegroundColor Gray
    Write-Host ""
    exit 1
}
