package alerting

import (
	"encoding/json"
	"fmt"
	"time"
)

// Severity represents the severity level of an alert
type Severity int8

const (
	SeverityInfo     Severity = 0
	SeverityLow      Severity = 1
	SeverityMedium   Severity = 2
	SeverityHigh     Severity = 3
	SeverityCritical Severity = 4
)

var severityNames = map[Severity]string{
	SeverityInfo:     "INFO",
	SeverityLow:      "LOW",
	SeverityMedium:   "MEDIUM",
	SeverityHigh:     "HIGH",
	SeverityCritical: "CRITICAL",
}

func (s Severity) String() string {
	if name, ok := severityNames[s]; ok {
		return name
	}
	return fmt.Sprintf("UNKNOWN(%d)", s)
}

func (s Severity) MarshalJSON() ([]byte, error) {
	return json.Marshal(s.String())
}

// AlertType categorizes the detection that triggered the alert
type AlertType string

const (
	AlertDDoS        AlertType = "DDOS"
	AlertBruteForce  AlertType = "BRUTE_FORCE"
	AlertPortScan    AlertType = "PORT_SCAN"
	AlertAnomaly     AlertType = "ANOMALY"
	AlertDomainBlock AlertType = "DOMAIN_BLOCK"
	AlertIPBlock     AlertType = "IP_BLOCK"
	AlertGeoBlock    AlertType = "GEO_BLOCK"
	AlertRateLimit   AlertType = "RATE_LIMIT"
	AlertThreatIntel AlertType = "THREAT_INTEL"
	AlertBeaconing   AlertType = "BEACONING"
	AlertProtocol     AlertType = "PROTOCOL_VIOLATION"
	AlertConfigChange AlertType = "CONFIG_CHANGE"
)

// ActionTaken describes what enforcement action was applied
type ActionTaken string

const (
	ActionBanned     ActionTaken = "BANNED"
	ActionDropped    ActionTaken = "DROPPED"
	ActionBlocked    ActionTaken = "BLOCKED"
	ActionRedirected ActionTaken = "REDIRECTED"
	ActionRateLimited ActionTaken = "RATE_LIMITED"
	ActionLogged     ActionTaken = "LOGGED"
)

// GeoInfo holds geographic information for an IP
type GeoInfo struct {
	CountryCode string `json:"country_code,omitempty"`
	CountryName string `json:"country_name,omitempty"`
	City        string `json:"city,omitempty"`
	ASN         uint32 `json:"asn,omitempty"`
	ASNOrg      string `json:"asn_org,omitempty"`
	IsAnonymizer bool  `json:"is_anonymizer,omitempty"`
}

// Alert represents a single security alert generated by the firewall engine
type Alert struct {
	// Identity
	ID        string    `json:"id"`
	Timestamp time.Time `json:"timestamp"`

	// Classification
	Type     AlertType `json:"type"`
	Severity Severity  `json:"severity"`

	// Network context
	SrcIP    string `json:"src_ip"`
	DstIP    string `json:"dst_ip,omitempty"`
	Protocol string `json:"protocol,omitempty"`
	SrcPort  uint16 `json:"src_port,omitempty"`
	DstPort  uint16 `json:"dst_port,omitempty"`
	Domain   string `json:"domain,omitempty"`

	// Detection details
	Details     string            `json:"details"`
	RuleID      string            `json:"rule_id,omitempty"`
	ThreatScore float64           `json:"threat_score,omitempty"`
	Metadata    map[string]string `json:"metadata,omitempty"`

	// Response
	ActionTaken ActionTaken `json:"action_taken"`
	BanDuration string     `json:"ban_duration,omitempty"`

	// Aggregation (filled by throttle)
	Count       int64  `json:"count,omitempty"`
	WindowStart string `json:"window_start,omitempty"`
	WindowEnd   string `json:"window_end,omitempty"`

	// Geographic
	GeoInfo *GeoInfo `json:"geo_info,omitempty"`
}

// ThrottleKey returns a deduplication key for this alert
func (a *Alert) ThrottleKey() string {
	return string(a.Type) + ":" + a.SrcIP
}

// AlertBuilder provides a fluent API for constructing alerts
type AlertBuilder struct {
	alert Alert
}

// NewAlert creates a new AlertBuilder
func NewAlert(alertType AlertType, severity Severity) *AlertBuilder {
	return &AlertBuilder{
		alert: Alert{
			Timestamp: time.Now(),
			Type:      alertType,
			Severity:  severity,
			Metadata:  make(map[string]string),
		},
	}
}

func (b *AlertBuilder) WithID(id string) *AlertBuilder {
	b.alert.ID = id
	return b
}

func (b *AlertBuilder) WithSource(srcIP string, srcPort uint16) *AlertBuilder {
	b.alert.SrcIP = srcIP
	b.alert.SrcPort = srcPort
	return b
}

func (b *AlertBuilder) WithDestination(dstIP string, dstPort uint16) *AlertBuilder {
	b.alert.DstIP = dstIP
	b.alert.DstPort = dstPort
	return b
}

func (b *AlertBuilder) WithProtocol(proto string) *AlertBuilder {
	b.alert.Protocol = proto
	return b
}

func (b *AlertBuilder) WithDomain(domain string) *AlertBuilder {
	b.alert.Domain = domain
	return b
}

func (b *AlertBuilder) WithDetails(details string) *AlertBuilder {
	b.alert.Details = details
	return b
}

func (b *AlertBuilder) WithRule(ruleID string) *AlertBuilder {
	b.alert.RuleID = ruleID
	return b
}

func (b *AlertBuilder) WithThreatScore(score float64) *AlertBuilder {
	b.alert.ThreatScore = score
	return b
}

func (b *AlertBuilder) WithAction(action ActionTaken) *AlertBuilder {
	b.alert.ActionTaken = action
	return b
}

func (b *AlertBuilder) WithBanDuration(d time.Duration) *AlertBuilder {
	b.alert.BanDuration = d.String()
	return b
}

func (b *AlertBuilder) WithGeoInfo(geo *GeoInfo) *AlertBuilder {
	b.alert.GeoInfo = geo
	return b
}

func (b *AlertBuilder) WithMeta(key, value string) *AlertBuilder {
	b.alert.Metadata[key] = value
	return b
}

func (b *AlertBuilder) Build() *Alert {
	return &b.alert
}
