// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: proto/metadata_stream.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataStreamService_StreamMetadata_FullMethodName = "/safeops.MetadataStreamService/StreamMetadata"
	MetadataStreamService_ApplyVerdict_FullMethodName   = "/safeops.MetadataStreamService/ApplyVerdict"
	MetadataStreamService_GetStats_FullMethodName       = "/safeops.MetadataStreamService/GetStats"
)

// MetadataStreamServiceClient is the client API for MetadataStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataStreamService provides packet metadata streaming and verdict enforcement
type MetadataStreamServiceClient interface {
	// StreamMetadata streams packet metadata to subscribers (server-side streaming)
	StreamMetadata(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PacketMetadata], error)
	// ApplyVerdict sends a verdict decision back to SafeOps Engine
	ApplyVerdict(ctx context.Context, in *VerdictRequest, opts ...grpc.CallOption) (*VerdictResponse, error)
	// GetStats returns engine statistics
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type metadataStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataStreamServiceClient(cc grpc.ClientConnInterface) MetadataStreamServiceClient {
	return &metadataStreamServiceClient{cc}
}

func (c *metadataStreamServiceClient) StreamMetadata(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PacketMetadata], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetadataStreamService_ServiceDesc.Streams[0], MetadataStreamService_StreamMetadata_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, PacketMetadata]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataStreamService_StreamMetadataClient = grpc.ServerStreamingClient[PacketMetadata]

func (c *metadataStreamServiceClient) ApplyVerdict(ctx context.Context, in *VerdictRequest, opts ...grpc.CallOption) (*VerdictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerdictResponse)
	err := c.cc.Invoke(ctx, MetadataStreamService_ApplyVerdict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataStreamServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, MetadataStreamService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataStreamServiceServer is the server API for MetadataStreamService service.
// All implementations must embed UnimplementedMetadataStreamServiceServer
// for forward compatibility.
//
// MetadataStreamService provides packet metadata streaming and verdict enforcement
type MetadataStreamServiceServer interface {
	// StreamMetadata streams packet metadata to subscribers (server-side streaming)
	StreamMetadata(*SubscribeRequest, grpc.ServerStreamingServer[PacketMetadata]) error
	// ApplyVerdict sends a verdict decision back to SafeOps Engine
	ApplyVerdict(context.Context, *VerdictRequest) (*VerdictResponse, error)
	// GetStats returns engine statistics
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedMetadataStreamServiceServer()
}

// UnimplementedMetadataStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataStreamServiceServer struct{}

func (UnimplementedMetadataStreamServiceServer) StreamMetadata(*SubscribeRequest, grpc.ServerStreamingServer[PacketMetadata]) error {
	return status.Error(codes.Unimplemented, "method StreamMetadata not implemented")
}
func (UnimplementedMetadataStreamServiceServer) ApplyVerdict(context.Context, *VerdictRequest) (*VerdictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyVerdict not implemented")
}
func (UnimplementedMetadataStreamServiceServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedMetadataStreamServiceServer) mustEmbedUnimplementedMetadataStreamServiceServer() {}
func (UnimplementedMetadataStreamServiceServer) testEmbeddedByValue()                               {}

// UnsafeMetadataStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataStreamServiceServer will
// result in compilation errors.
type UnsafeMetadataStreamServiceServer interface {
	mustEmbedUnimplementedMetadataStreamServiceServer()
}

func RegisterMetadataStreamServiceServer(s grpc.ServiceRegistrar, srv MetadataStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedMetadataStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataStreamService_ServiceDesc, srv)
}

func _MetadataStreamService_StreamMetadata_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MetadataStreamServiceServer).StreamMetadata(m, &grpc.GenericServerStream[SubscribeRequest, PacketMetadata]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetadataStreamService_StreamMetadataServer = grpc.ServerStreamingServer[PacketMetadata]

func _MetadataStreamService_ApplyVerdict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerdictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataStreamServiceServer).ApplyVerdict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataStreamService_ApplyVerdict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataStreamServiceServer).ApplyVerdict(ctx, req.(*VerdictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataStreamService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataStreamServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataStreamService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataStreamServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataStreamService_ServiceDesc is the grpc.ServiceDesc for MetadataStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "safeops.MetadataStreamService",
	HandlerType: (*MetadataStreamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyVerdict",
			Handler:    _MetadataStreamService_ApplyVerdict_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _MetadataStreamService_GetStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetadata",
			Handler:       _MetadataStreamService_StreamMetadata_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/metadata_stream.proto",
}
