# SafeOps Certificate Authority Initialization Script
# This script initializes step-ca with SafeOps branding

$STEP_CA = "D:\SafeOpsFV2\certs\step-ca\step-ca.exe"
$STEP_CLI = "D:\SafeOpsFV2\certs\step-ca\step_0.27.4\bin\step.exe"
$CA_DIR = "D:\SafeOpsFV2\certs\step-ca\ca"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "SafeOps Certificate Authority Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Create CA directory
Write-Host "[1/5] Creating CA directory..." -ForegroundColor Yellow
New-Item -Path $CA_DIR -ItemType Directory -Force | Out-Null

# Set environment variable for step-ca
$env:STEPPATH = $CA_DIR

# Initialize CA with SafeOps branding
Write-Host "[2/5] Initializing SafeOps Certificate Authority..." -ForegroundColor Yellow

# Generate password file (random password for CA key)
$password = -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object {[char]$_})
$password | Out-File -FilePath "$CA_DIR\password.txt" -NoNewline -Encoding ASCII

# Initialize step-ca
& $STEP_CLI ca init `
    --name "SafeOps Root CA" `
    --dns "safeops.local" `
    --dns "192.168.137.1" `
    --address ":9000" `
    --provisioner "safeops-admin" `
    --password-file "$CA_DIR\password.txt" `
    --provisioner-password-file "$CA_DIR\password.txt"

Write-Host "[3/5] Customizing CA configuration for SafeOps..." -ForegroundColor Yellow

# Read the generated config
$configPath = "$CA_DIR\config\ca.json"
$config = Get-Content $configPath -Raw | ConvertFrom-Json

# Customize configuration
$config.authority.provisioners[0].claims = @{
    minTLSCertDuration = "5m"
    maxTLSCertDuration = "8760h"  # 1 year
    defaultTLSCertDuration = "720h"  # 30 days
    disableRenewal = $false
    allowRenewalAfterExpiry = $false
}

# Add ACME provisioner for automatic enrollment
$acmeProvisioner = @{
    type = "ACME"
    name = "safeops-acme"
    forceCN = $false
    claims = @{
        minTLSCertDuration = "5m"
        maxTLSCertDuration = "8760h"
        defaultTLSCertDuration = "720h"
    }
}
$config.authority.provisioners += $acmeProvisioner

# Save customized config
$config | ConvertTo-Json -Depth 10 | Set-Content $configPath

Write-Host "[4/5] Generating SafeOps branded CA certificate..." -ForegroundColor Yellow

# The CA certificate is already generated by step ca init
# Let's copy it to the main certs directory for easy access
Copy-Item "$CA_DIR\certs\root_ca.crt" "D:\SafeOpsFV2\certs\safeops-root-ca.crt" -Force
Copy-Item "$CA_DIR\certs\intermediate_ca.crt" "D:\SafeOpsFV2\certs\safeops-intermediate-ca.crt" -Force

Write-Host "[5/5] Creating startup configuration..." -ForegroundColor Yellow

# Create startup script
$startupScript = @"
@echo off
echo Starting SafeOps Certificate Authority...
set STEPPATH=D:\SafeOpsFV2\certs\step-ca\ca
"D:\SafeOpsFV2\certs\step-ca\step-ca.exe" "D:\SafeOpsFV2\certs\step-ca\ca\config\ca.json" --password-file "D:\SafeOpsFV2\certs\step-ca\ca\password.txt"
"@

$startupScript | Out-File -FilePath "D:\SafeOpsFV2\certs\step-ca\start-safeops-ca.bat" -Encoding ASCII

Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "SafeOps CA Initialization Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "CA Details:" -ForegroundColor Cyan
Write-Host "  Name: SafeOps Root CA" -ForegroundColor White
Write-Host "  Organization: SafeOps Network" -ForegroundColor White
Write-Host "  Address: https://192.168.137.1:9000" -ForegroundColor White
Write-Host "  Root CA Cert: D:\SafeOpsFV2\certs\safeops-root-ca.crt" -ForegroundColor White
Write-Host ""
Write-Host "To start the CA server, run:" -ForegroundColor Yellow
Write-Host "  D:\SafeOpsFV2\certs\step-ca\start-safeops-ca.bat" -ForegroundColor White
Write-Host ""
