// netsim — Real network traffic simulator for SafeOps Firewall testing
//
// Unlike sectest (which calls security modules directly with fake data),
// netsim generates REAL network traffic that flows through the full pipeline:
//
//   netsim → real TCP/UDP packets → SafeOps Engine (tunnel) → gRPC →
//   Firewall Engine → security checks → REAL alerts in firewall-alerts.jsonl
//
// The simulator sends packets to a non-routable external IP (198.51.100.1,
// TEST-NET-2 per RFC 5737) so they hit the SafeOps Engine's tunnel but
// never actually leave the network. The packets are still parsed, checked
// by the Firewall Engine security modules, and generate real alerts.
//
// Usage:
//
//	go run .                 (run all tests)
//	go run . --test syn      (run specific test)
//	go run . --list          (list available tests)
//
// Must run WHILE safeops-engine + firewall-engine are both running.
// Run as Administrator for best results.
package main

import (
	"flag"
	"fmt"
	"math/rand"
	"net"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

// ANSI colors
const (
	reset  = "\033[0m"
	red    = "\033[31m"
	green  = "\033[32m"
	yellow = "\033[33m"
	cyan   = "\033[36m"
	bold   = "\033[1m"
)

// Target IPs — TEST-NET-2 (RFC 5737), guaranteed non-routable.
// Packets sent here WILL be intercepted by SafeOps Engine tunnel mode
// but will NOT actually leave the machine. This is ideal for testing.
const (
	targetIP   = "198.51.100.1"
	targetIP2  = "198.51.100.2"
	targetIP3  = "198.51.100.3"
	targetIP4  = "198.51.100.4"
	targetIP5  = "198.51.100.5"
	targetIP6  = "198.51.100.6"
	targetIP7  = "198.51.100.7"
	targetIP8  = "198.51.100.8"
	targetIP9  = "198.51.100.9"
	targetIP10 = "198.51.100.10"
)

// VPN ports from blocked_ports.txt
var vpnPorts = []struct {
	port  int
	proto string
	name  string
}{
	{1194, "tcp", "OpenVPN"},
	{1194, "udp", "OpenVPN"},
	{51820, "udp", "WireGuard"},
	{500, "udp", "IKE"},
	{4500, "udp", "NAT-T"},
	{1723, "tcp", "PPTP"},
	{9050, "tcp", "Tor SOCKS"},
	{9001, "tcp", "Tor OR"},
	{5555, "tcp", "SoftEther"},
}

// DoH servers from doh_servers.txt
var dohServers = []string{
	"8.8.8.8", "8.8.4.4", "1.1.1.1", "1.0.0.1", "9.9.9.9",
}

// Blocked domains from domains.txt
var blockedDomains = []string{
	"facebook.com", "twitter.com", "instagram.com", "x.com", "tiktok.com",
}

type testCase struct {
	name        string
	description string
	fn          func() testResult
}

type testResult struct {
	passed      bool
	packetsOut  int
	description string
}

func main() {
	testFlag := flag.String("test", "", "Run specific test (comma-separated names)")
	listFlag := flag.Bool("list", false, "List all available tests")
	durationFlag := flag.Int("duration", 3, "Duration in seconds for flood tests")
	flag.Parse()

	fmt.Println(bold + cyan + `
╔══════════════════════════════════════════════════════════════════╗
║   SafeOps Network Attack Simulator v2.0 (Real Traffic Mode)    ║
║   Generates REAL packets → SafeOps Engine → Firewall Engine    ║
║   Alerts are generated by the FIREWALL ENGINE, not this tool   ║
╚══════════════════════════════════════════════════════════════════╝` + reset)
	fmt.Println()

	duration := time.Duration(*durationFlag) * time.Second

	// Test order matters: DDoS floods and rule-engine tests run FIRST because
	// port scan and brute force tests trigger IP bans, which would cause all
	// subsequent tests from the same source IP to be dropped at the ban check.
	tests := []testCase{
		{"vpn-ports", "VPN Port Access — connect to blocked VPN/Tor ports", func() testResult { return testVPNPorts() }},
		{"doh-bypass", "DoH Bypass — connect to known DoH resolver IPs on 443", func() testResult { return testDoHBypass() }},
		{"dns-block", "Blocked Domain DNS — resolve blocked domains", func() testResult { return testBlockedDomains() }},
		{"udp-flood", "UDP Flood DDoS — 5500+ UDP/sec (threshold: 5000)", func() testResult { return testUDPFlood(targetIP2, duration) }},
		{"syn-flood", "SYN Flood DDoS — 1100+ SYN/sec (threshold: 1000)", func() testResult { return testSYNFlood(targetIP, duration) }},
		{"ssh-brute", "SSH Brute Force — 7 attempts on port 22 (threshold: 5/120s)", func() testResult { return testBruteForce(targetIP5, 22, "SSH", 7) }},
		{"rdp-brute", "RDP Brute Force — 5 attempts on port 3389 (threshold: 3/60s)", func() testResult { return testBruteForce(targetIP6, 3389, "RDP", 5) }},
		{"rapid-conn", "Rapid Connections — 500 connections in burst (rate limiting)", func() testResult { return testRapidConnections(targetIP7) }},
		{"port-scan", "Port Scan — 150 unique ports in <10s (threshold: 100)", func() testResult { return testPortScan(targetIP3) }},
		{"seq-scan", "Sequential Port Scan — 30 sequential (threshold: 20)", func() testResult { return testSequentialScan(targetIP4) }},
		{"multi-proto", "Multi-Protocol Burst — TCP+UDP from same IP simultaneously", func() testResult { return testMultiProtoBurst(targetIP8, duration) }},
	}

	if *listFlag {
		fmt.Println(bold + "Available tests:" + reset)
		for _, t := range tests {
			fmt.Printf("  %-14s %s\n", t.name, t.description)
		}
		return
	}

	// Filter tests if --test flag given
	if *testFlag != "" {
		names := strings.Split(*testFlag, ",")
		nameSet := make(map[string]bool)
		for _, n := range names {
			nameSet[strings.TrimSpace(n)] = true
		}

		var filtered []testCase
		for _, t := range tests {
			if nameSet[t.name] {
				filtered = append(filtered, t)
			}
		}
		if len(filtered) == 0 {
			fmt.Printf(red+"No tests match: %s\n"+reset, *testFlag)
			fmt.Println("Use --list to see available tests")
			os.Exit(1)
		}
		tests = filtered
	}

	fmt.Printf(yellow+"Target IPs: %s (TEST-NET-2, non-routable)\n"+reset, targetIP)
	fmt.Printf(yellow + "Make sure safeops-engine + firewall-engine are BOTH running!\n" + reset)
	fmt.Printf(yellow+"Flood duration: %v\n"+reset, duration)
	fmt.Println(strings.Repeat("─", 64))

	passed := 0
	failed := 0

	for i, t := range tests {
		fmt.Printf("\n"+bold+cyan+"[%d/%d] %s"+reset+"\n", i+1, len(tests), t.description)

		result := t.fn()

		if result.passed {
			fmt.Printf(green+"  ✓ DONE: %s (%d packets sent)\n"+reset, result.description, result.packetsOut)
			passed++
		} else {
			fmt.Printf(red+"  ✗ FAIL: %s\n"+reset, result.description)
			failed++
		}

		// Brief pause between tests to let the firewall engine process
		if i < len(tests)-1 {
			time.Sleep(500 * time.Millisecond)
		}
	}

	fmt.Println("\n" + strings.Repeat("═", 64))
	fmt.Printf(bold+"Results: %d/%d tests completed\n"+reset, passed, passed+failed)
	if failed > 0 {
		fmt.Printf(red+"  %d tests had errors sending packets\n"+reset, failed)
	}
	fmt.Println()
	fmt.Println(yellow + "Now check your Firewall Engine output for alerts!" + reset)
	fmt.Println(yellow + "Alert file: bin/firewall-engine/data/alerts/firewall-alerts.jsonl" + reset)
}

// ============================================================================
// Test: SYN Flood DDoS
// Sends many TCP SYN connections to random ports from the same source.
// The SafeOps Engine sees these as outbound TCP to port X on targetIP,
// sends them via gRPC to Firewall Engine, which detects SYN flood.
// ============================================================================
func testSYNFlood(target string, duration time.Duration) testResult {
	var sent int64
	start := time.Now()
	var wg sync.WaitGroup

	// Use a SINGLE port to avoid triggering port scan detection.
	// Real SYN floods target a specific service port (e.g., 80, 443).
	floodPort := 80

	for time.Since(start) < duration {
		// Launch 200 concurrent TCP dials per batch — each generates a SYN packet.
		// Using goroutines because DialTimeout blocks waiting for SYN-ACK from
		// a non-routable IP, so sequential dialing is too slow.
		for i := 0; i < 200; i++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:%d", target, floodPort), 10*time.Millisecond)
				if err == nil {
					conn.Close()
				}
				atomic.AddInt64(&sent, 1)
			}()
		}
		time.Sleep(50 * time.Millisecond)
	}
	wg.Wait()

	return testResult{true, int(sent), fmt.Sprintf("SYN flood: %d SYN packets to port %d in %v", sent, floodPort, duration)}
}

// ============================================================================
// Test: UDP Flood DDoS
// Sends many UDP packets to random ports.
// ============================================================================
func testUDPFlood(target string, duration time.Duration) testResult {
	sent := 0
	payload := make([]byte, 512)
	rand.Read(payload)
	start := time.Now()

	addr, err := net.ResolveUDPAddr("udp", fmt.Sprintf("%s:%d", target, 9999))
	if err != nil {
		return testResult{false, 0, fmt.Sprintf("resolve error: %v", err)}
	}

	conn, err := net.DialUDP("udp", nil, addr)
	if err != nil {
		return testResult{false, 0, fmt.Sprintf("dial error: %v", err)}
	}
	defer conn.Close()

	for time.Since(start) < duration {
		for i := 0; i < 550; i++ { // ~5500/sec in batches
			conn.Write(payload)
			sent++
		}
		time.Sleep(100 * time.Millisecond)
	}

	return testResult{true, sent, fmt.Sprintf("UDP flood: %d packets in %v", sent, duration)}
}

// ============================================================================
// Test: Port Scan
// Rapidly connects to 150 unique ports on the target.
// ============================================================================
func testPortScan(target string) testResult {
	ports := make([]int, 150)
	for i := range ports {
		ports[i] = rand.Intn(65534) + 1
	}

	sent := 0
	for _, port := range ports {
		conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:%d", target, port), 20*time.Millisecond)
		if err == nil {
			conn.Close()
		}
		sent++
	}

	return testResult{true, sent, fmt.Sprintf("Port scan: %d unique ports probed", sent)}
}

// ============================================================================
// Test: Sequential Port Scan
// Scans ports 1000-1030 in order (easily detected).
// ============================================================================
func testSequentialScan(target string) testResult {
	sent := 0
	for port := 1000; port <= 1030; port++ {
		conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:%d", target, port), 20*time.Millisecond)
		if err == nil {
			conn.Close()
		}
		sent++
	}

	return testResult{true, sent, fmt.Sprintf("Sequential scan: ports 1000-1030 (%d probed)", sent)}
}

// ============================================================================
// Test: Brute Force (SSH/RDP/etc)
// Rapid TCP connections to a specific service port simulate login attempts.
// ============================================================================
func testBruteForce(target string, port int, service string, attempts int) testResult {
	sent := 0
	for i := 0; i < attempts; i++ {
		conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:%d", target, port), 100*time.Millisecond)
		if err == nil {
			// Send some data to simulate auth attempt
			conn.Write([]byte("USER admin\r\nPASS wrong\r\n"))
			time.Sleep(50 * time.Millisecond)
			conn.Close()
		}
		sent++
		time.Sleep(100 * time.Millisecond) // Realistic brute force pace
	}

	return testResult{true, sent, fmt.Sprintf("%s brute force: %d attempts on port %d", service, sent, port)}
}

// ============================================================================
// Test: VPN Port Access
// Connects to known VPN/Tor ports (blocked by SafeOps Engine).
// These may be RST'd by SafeOps Engine before reaching Firewall Engine,
// but the attempt still generates tunnel traffic.
// ============================================================================
func testVPNPorts() testResult {
	sent := 0
	for _, vp := range vpnPorts {
		addr := fmt.Sprintf("%s:%d", targetIP9, vp.port)

		if vp.proto == "tcp" {
			conn, err := net.DialTimeout("tcp", addr, 200*time.Millisecond)
			if err == nil {
				conn.Close()
			}
		} else {
			udpAddr, _ := net.ResolveUDPAddr("udp", addr)
			conn, err := net.DialUDP("udp", nil, udpAddr)
			if err == nil {
				conn.Write([]byte("VPN_PROBE"))
				conn.Close()
			}
		}
		sent++

		fmt.Printf("    %s %s/%d\n", vp.name, vp.proto, vp.port)
	}

	return testResult{true, sent, fmt.Sprintf("VPN ports: %d port probes", sent)}
}

// ============================================================================
// Test: DoH Bypass
// Attempts to connect to known DoH resolver IPs on port 443.
// SafeOps Engine should RST these connections (they're in doh_servers.txt).
// ============================================================================
func testDoHBypass() testResult {
	sent := 0
	for _, server := range dohServers {
		conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:443", server), 500*time.Millisecond)
		if err == nil {
			conn.Close()
			fmt.Printf("    %s:443 — "+yellow+"connected (not blocked!)"+reset+"\n", server)
		} else {
			fmt.Printf("    %s:443 — "+green+"blocked/timeout"+reset+"\n", server)
		}
		sent++
	}

	return testResult{true, sent, fmt.Sprintf("DoH bypass: %d resolver IPs tested", sent)}
}

// ============================================================================
// Test: Blocked Domain DNS
// Resolves domains from domains.txt — should be redirected to 127.0.0.1.
// ============================================================================
func testBlockedDomains() testResult {
	sent := 0
	for _, domain := range blockedDomains {
		ips, err := net.LookupHost(domain)
		if err != nil {
			fmt.Printf("    %s — "+green+"blocked (DNS failed)"+reset+"\n", domain)
		} else if len(ips) > 0 && ips[0] == "127.0.0.1" {
			fmt.Printf("    %s → 127.0.0.1 — "+green+"redirected to block page"+reset+"\n", domain)
		} else {
			fmt.Printf("    %s → %s — "+yellow+"resolved (not blocked?)"+reset+"\n", domain, strings.Join(ips, ", "))
		}
		sent++
	}

	return testResult{true, sent, fmt.Sprintf("Blocked domains: %d DNS queries", sent)}
}

// ============================================================================
// Test: Rapid Connections (Rate Limiting)
// Opens 500 TCP connections in rapid burst from one source to one target.
// This tests the rate limiter (1000 pkt/s per IP, burst 2000).
// ============================================================================
func testRapidConnections(target string) testResult {
	sent := 0
	var wg sync.WaitGroup

	// Send 500 connections concurrently in bursts of 50
	for batch := 0; batch < 10; batch++ {
		for i := 0; i < 50; i++ {
			wg.Add(1)
			port := rand.Intn(65534) + 1
			go func(p int) {
				defer wg.Done()
				conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:%d", target, p), 50*time.Millisecond)
				if err == nil {
					conn.Close()
				}
			}(port)
			sent++
		}
		wg.Wait()
		time.Sleep(10 * time.Millisecond) // Brief pause between bursts
	}

	return testResult{true, sent, fmt.Sprintf("Rapid connections: %d TCP connections in burst", sent)}
}

// ============================================================================
// Test: Multi-Protocol Burst
// Sends TCP + UDP simultaneously from the same source IP to stress test.
// ============================================================================
func testMultiProtoBurst(target string, duration time.Duration) testResult {
	var sent int64
	start := time.Now()
	var wg sync.WaitGroup

	// TCP goroutine
	wg.Add(1)
	go func() {
		defer wg.Done()
		for time.Since(start) < duration {
			for i := 0; i < 100; i++ {
				port := rand.Intn(65534) + 1
				conn, err := net.DialTimeout("tcp", fmt.Sprintf("%s:%d", target, port), 10*time.Millisecond)
				if err == nil {
					conn.Close()
				}
				atomic.AddInt64(&sent, 1)
			}
			time.Sleep(100 * time.Millisecond)
		}
	}()

	// UDP goroutine
	wg.Add(1)
	go func() {
		defer wg.Done()
		payload := make([]byte, 256)
		rand.Read(payload)
		addr, _ := net.ResolveUDPAddr("udp", fmt.Sprintf("%s:9999", target))
		conn, err := net.DialUDP("udp", nil, addr)
		if err != nil {
			return
		}
		defer conn.Close()
		for time.Since(start) < duration {
			for i := 0; i < 200; i++ {
				conn.Write(payload)
				atomic.AddInt64(&sent, 1)
			}
			time.Sleep(100 * time.Millisecond)
		}
	}()

	wg.Wait()

	return testResult{true, int(sent), fmt.Sprintf("Multi-protocol burst: %d TCP+UDP packets in %v", sent, duration)}
}
