#!/usr/bin/env python3
"""
SafeOps SIEM - Filebeat Setup & Index Creator
==============================================
Downloads, installs, and configures Filebeat to ship SafeOps logs to Elasticsearch.
Also creates the required Elasticsearch indices with proper mappings.

Run as Administrator!
"""

import os
import sys
import subprocess
import urllib.request
import zipfile
import json
import time
from pathlib import Path

# ============================================================================
# CONFIGURATION
# ============================================================================

CONFIG = {
    # Filebeat version (match your ELK version)
    "filebeat_version": "8.17.0",
    
    # Installation paths
    "install_dir": "D:/SafeOpsFV2/bin/elk",
    "logs_dir": "D:/SafeOpsFV2/logs",
    
    # Elasticsearch connection
    "elasticsearch_host": "localhost",
    "elasticsearch_port": 9200,
    "elasticsearch_user": "safeops_admin",
    "elasticsearch_pass": "SafeOps@SIEM2026!",
    
    # Kibana (for dashboards)
    "kibana_host": "localhost",
    "kibana_port": 5601,
    
    # Log files to ingest
    "log_inputs": [
        {
            "name": "ids",
            "path": "D:/SafeOpsFV2/logs/ids.log",
            "index": "safeops-ids",
            "category": "active",
            "description": "IDS/IPS Security Alerts"
        },
        {
            "name": "firewall",
            "path": "D:/SafeOpsFV2/logs/firewall.log",
            "index": "safeops-firewall",
            "category": "active",
            "description": "Firewall Decisions"
        },
        {
            "name": "netflow_ew",
            "path": "D:/SafeOpsFV2/logs/netflow/east_west.log",
            "index": "safeops-netflow-ew",
            "category": "passive",
            "description": "Internal Traffic (East-West)"
        },
        {
            "name": "netflow_ns",
            "path": "D:/SafeOpsFV2/logs/netflow/north_south.log",
            "index": "safeops-netflow-ns",
            "category": "passive",
            "description": "External Traffic (North-South)"
        },
        {
            "name": "devices",
            "path": "D:/SafeOpsFV2/logs/devices.jsonl",
            "index": "safeops-devices",
            "category": "passive",
            "description": "Device Inventory"
        },
    ],
}

FILEBEAT_URL = f"https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{CONFIG['filebeat_version']}-windows-x86_64.zip"


def print_banner():
    """Print banner."""
    print("""
╔══════════════════════════════════════════════════════════════════╗
║          SafeOps SIEM - Filebeat Setup & Index Creator           ║
║                                                                  ║
║  Filebeat → Elasticsearch (Direct Ingestion)                     ║
╚══════════════════════════════════════════════════════════════════╝
    """)
    print(f"  Filebeat Version: {CONFIG['filebeat_version']}")
    print(f"  Elasticsearch: {CONFIG['elasticsearch_host']}:{CONFIG['elasticsearch_port']}")
    print(f"  Logs Directory: {CONFIG['logs_dir']}")
    print()


def download_filebeat():
    """Download Filebeat if not already present."""
    # Windows extracted folder has -windows-x86_64 suffix
    filebeat_dir = Path(CONFIG['install_dir']) / f"filebeat-{CONFIG['filebeat_version']}-windows-x86_64"
    
    if filebeat_dir.exists():
        print(f"✅ Filebeat already installed at {filebeat_dir}")
        return filebeat_dir
    
    # Also check without suffix (in case renamed)
    alt_dir = Path(CONFIG['install_dir']) / f"filebeat-{CONFIG['filebeat_version']}"
    if alt_dir.exists():
        print(f"✅ Filebeat already installed at {alt_dir}")
        return alt_dir
    
    temp_dir = Path(CONFIG['install_dir']) / "temp"
    temp_dir.mkdir(parents=True, exist_ok=True)
    
    zip_path = temp_dir / f"filebeat-{CONFIG['filebeat_version']}.zip"
    
    if not zip_path.exists():
        print(f"📥 Downloading Filebeat {CONFIG['filebeat_version']}...")
        print(f"   URL: {FILEBEAT_URL}")
        
        try:
            urllib.request.urlretrieve(FILEBEAT_URL, zip_path)
            print(f"   ✅ Downloaded: {zip_path}")
        except Exception as e:
            print(f"   ❌ Download failed: {e}")
            return None
    
    # Extract
    print(f"📦 Extracting Filebeat...")
    try:
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(CONFIG['install_dir'])
        print(f"   ✅ Extracted to: {CONFIG['install_dir']}")
    except Exception as e:
        print(f"   ❌ Extraction failed: {e}")
        return None
    
    return filebeat_dir


def generate_filebeat_config(filebeat_dir):
    """Generate filebeat.yml configuration."""
    print("\n🔧 Generating Filebeat configuration...")
    
    config_content = f"""# SafeOps SIEM - Filebeat Configuration
# Generated by SafeOps Filebeat Setup
# =====================================

# ======================== Filebeat Inputs ========================

filebeat.inputs:
"""
    
    # Add each log input
    for log_input in CONFIG['log_inputs']:
        config_content += f"""
  # {log_input['description']} ({log_input['category'].upper()})
  - type: log
    enabled: true
    paths:
      - "{log_input['path']}"
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      log_type: "{log_input['name']}"
      category: "{log_input['category']}"
      safeops_version: "2.0"
    fields_under_root: false
    close_inactive: 1m
    clean_inactive: 5m
    ignore_older: 24h
    tail_files: false
"""
    
    config_content += f"""
# ======================== Processors ========================

processors:
  - timestamp:
      field: timestamp_ist
      layouts:
        - '2006-01-02T15:04:05.999999999Z07:00'
      ignore_missing: true
      ignore_failure: true
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_fields:
      target: safeops
      fields:
        platform: "SafeOps FV2"
        version: "2.0.0"

# ======================== Elasticsearch Output ========================

output.elasticsearch:
  hosts: ["{CONFIG['elasticsearch_host']}:{CONFIG['elasticsearch_port']}"]
  username: "{CONFIG['elasticsearch_user']}"
  password: "{CONFIG['elasticsearch_pass']}"
  protocol: "http"
  
  # Index routing based on log_type
  indices:
"""
    
    # Add index routing for each log type
    for log_input in CONFIG['log_inputs']:
        config_content += f"""    - index: "{log_input['index']}-%{{+yyyy.MM.dd}}"
      when.equals:
        fields.log_type: "{log_input['name']}"
"""
    
    config_content += f"""
# ======================== Logging ========================

logging.level: info
logging.to_files: true
logging.files:
  path: {CONFIG['install_dir']}/logs/filebeat
  name: filebeat.log
  keepfiles: 3
  permissions: 0644

# ======================== Monitoring ========================

monitoring.enabled: false
"""
    
    # Write config file
    config_path = filebeat_dir / "filebeat.yml"
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print(f"   ✅ Configuration written: {config_path}")
    return config_path


def create_elasticsearch_indices():
    """Create Elasticsearch indices with proper mappings."""
    print("\n📊 Creating Elasticsearch indices...")
    
    es_url = f"http://{CONFIG['elasticsearch_host']}:{CONFIG['elasticsearch_port']}"
    auth = f"{CONFIG['elasticsearch_user']}:{CONFIG['elasticsearch_pass']}"
    
    # Index template for SafeOps logs
    index_template = {
        "index_patterns": ["safeops-*"],
        "template": {
            "settings": {
                "number_of_shards": 1,
                "number_of_replicas": 0,
                "index.lifecycle.name": "safeops-ilm-policy",
                "index.lifecycle.rollover_alias": "safeops"
            },
            "mappings": {
                "properties": {
                    "@timestamp": {"type": "date"},
                    "timestamp_ist": {"type": "date"},
                    "timestamp": {
                        "properties": {
                            "iso8601": {"type": "date"},
                            "epoch": {"type": "double"}
                        }
                    },
                    "src_ip": {"type": "ip"},
                    "dst_ip": {"type": "ip"},
                    "src_port": {"type": "integer"},
                    "dst_port": {"type": "integer"},
                    "protocol": {"type": "keyword"},
                    "action": {"type": "keyword"},
                    "direction": {"type": "keyword"},
                    "category": {"type": "keyword"},
                    "log_type": {"type": "keyword"},
                    "src_geo": {
                        "properties": {
                            "country": {"type": "keyword"},
                            "country_name": {"type": "keyword"},
                            "city": {"type": "keyword"},
                            "asn": {"type": "integer"},
                            "org": {"type": "keyword"}
                        }
                    },
                    "dst_geo": {
                        "properties": {
                            "country": {"type": "keyword"},
                            "country_name": {"type": "keyword"},
                            "city": {"type": "keyword"},
                            "asn": {"type": "integer"},
                            "org": {"type": "keyword"}
                        }
                    },
                    "fields": {
                        "properties": {
                            "log_type": {"type": "keyword"},
                            "category": {"type": "keyword"}
                        }
                    },
                    "safeops": {
                        "properties": {
                            "platform": {"type": "keyword"},
                            "version": {"type": "keyword"}
                        }
                    }
                }
            }
        },
        "priority": 100
    }
    
    # ILM Policy (7-day retention)
    ilm_policy = {
        "policy": {
            "phases": {
                "hot": {
                    "min_age": "0ms",
                    "actions": {
                        "rollover": {
                            "max_age": "1d",
                            "max_primary_shard_size": "50gb"
                        }
                    }
                },
                "delete": {
                    "min_age": "7d",
                    "actions": {
                        "delete": {}
                    }
                }
            }
        }
    }
    
    try:
        import urllib.request
        
        # Create ILM Policy
        print("   Creating ILM policy (7-day retention)...")
        req = urllib.request.Request(
            f"{es_url}/_ilm/policy/safeops-ilm-policy",
            data=json.dumps(ilm_policy).encode('utf-8'),
            headers={'Content-Type': 'application/json'},
            method='PUT'
        )
        # Add basic auth
        import base64
        credentials = base64.b64encode(auth.encode()).decode()
        req.add_header('Authorization', f'Basic {credentials}')
        
        try:
            urllib.request.urlopen(req)
            print("   ✅ ILM policy created")
        except Exception as e:
            print(f"   ⚠️ ILM policy may already exist: {e}")
        
        # Create Index Template
        print("   Creating index template...")
        req = urllib.request.Request(
            f"{es_url}/_index_template/safeops-template",
            data=json.dumps(index_template).encode('utf-8'),
            headers={'Content-Type': 'application/json'},
            method='PUT'
        )
        req.add_header('Authorization', f'Basic {credentials}')
        
        try:
            urllib.request.urlopen(req)
            print("   ✅ Index template created")
        except Exception as e:
            print(f"   ⚠️ Index template may already exist: {e}")
        
        print("   ✅ Elasticsearch indices configured")
        return True
        
    except Exception as e:
        print(f"   ⚠️ Could not create indices (Elasticsearch may not be running): {e}")
        print("   ℹ️  Indices will be created automatically when Filebeat starts")
        return False


def create_startup_scripts(filebeat_dir):
    """Create startup/stop scripts for Filebeat."""
    print("\n📝 Creating startup scripts...")
    
    scripts_dir = Path(CONFIG['install_dir'])
    
    # Start Filebeat script
    start_script = f"""@echo off
echo Starting SafeOps Filebeat...
cd /d "{filebeat_dir}"
start "Filebeat" filebeat.exe -c filebeat.yml
echo Filebeat started!
echo.
echo Logs are being shipped to Elasticsearch.
echo Check Kibana at http://localhost:{CONFIG['kibana_port']}
"""
    
    with open(scripts_dir / "start-filebeat.bat", 'w') as f:
        f.write(start_script)
    
    # Stop Filebeat script
    stop_script = """@echo off
echo Stopping SafeOps Filebeat...
taskkill /FI "WINDOWTITLE eq Filebeat*" /F 2>nul
taskkill /IM filebeat.exe /F 2>nul
echo Filebeat stopped.
"""
    
    with open(scripts_dir / "stop-filebeat.bat", 'w') as f:
        f.write(stop_script)
    
    # Combined SIEM start script (Elasticsearch + Kibana + Filebeat)
    start_all_script = f"""@echo off
echo ==========================================
echo   Starting SafeOps SIEM Stack
echo ==========================================
echo.

echo [1/3] Starting Elasticsearch...
start "Elasticsearch" /D "{CONFIG['install_dir']}\\elasticsearch-{CONFIG['filebeat_version']}\\bin" elasticsearch.bat
echo Waiting 45 seconds for Elasticsearch...
timeout /t 45 /nobreak

echo.
echo [2/3] Starting Kibana...
start "Kibana" /D "{CONFIG['install_dir']}\\kibana-{CONFIG['filebeat_version']}\\bin" kibana.bat
echo Waiting 30 seconds for Kibana...
timeout /t 30 /nobreak

echo.
echo [3/3] Starting Filebeat...
start "Filebeat" /D "{filebeat_dir}" filebeat.exe -c filebeat.yml

echo.
echo ==========================================
echo   SafeOps SIEM Stack Started!
echo ==========================================
echo.
echo   Elasticsearch: http://localhost:{CONFIG['elasticsearch_port']}
echo   Kibana:        http://localhost:{CONFIG['kibana_port']}
echo.
echo   Indices:
echo     - safeops-ids-*       (IDS Alerts)
echo     - safeops-firewall-*  (Firewall)
echo     - safeops-netflow-ew-* (East-West)
echo     - safeops-netflow-ns-* (North-South)
echo     - safeops-devices-*   (Devices)
echo.
echo   Username: {CONFIG['elasticsearch_user']}
echo   Password: {CONFIG['elasticsearch_pass']}
echo ==========================================
"""
    
    with open(scripts_dir / "start-siem-full.bat", 'w') as f:
        f.write(start_all_script)
    
    print(f"   ✅ Created: start-filebeat.bat")
    print(f"   ✅ Created: stop-filebeat.bat")
    print(f"   ✅ Created: start-siem-full.bat")


def main():
    """Main setup function."""
    print_banner()
    
    # Step 1: Download Filebeat
    filebeat_dir = download_filebeat()
    if not filebeat_dir:
        print("❌ Failed to download Filebeat. Aborting.")
        return False
    
    # Step 2: Generate configuration
    generate_filebeat_config(filebeat_dir)
    
    # Step 3: Create Elasticsearch indices
    create_elasticsearch_indices()
    
    # Step 4: Create startup scripts
    create_startup_scripts(filebeat_dir)
    
    # Create logs directory for Filebeat
    (Path(CONFIG['install_dir']) / "logs" / "filebeat").mkdir(parents=True, exist_ok=True)
    
    # Print completion message
    print("\n" + "=" * 60)
    print("✅ SafeOps Filebeat Setup Complete!")
    print("=" * 60)
    print(f"""
Next Steps:
-----------
1. Make sure Elasticsearch is running (start-siem.bat)
2. Run start-filebeat.bat to start log ingestion
3. Open Kibana at http://localhost:{CONFIG['kibana_port']}
4. Go to Stack Management → Index Management to see indices

OR run start-siem-full.bat to start everything at once!

Log Files Being Ingested:
""")
    for log_input in CONFIG['log_inputs']:
        print(f"  - {log_input['path']} → {log_input['index']}-*")
    
    print("\n" + "=" * 60)
    return True


if __name__ == "__main__":
    success = main()
    if not success:
        sys.exit(1)
