//! TLS Proxy gRPC client for packet inspection.
//!
//! Communicates with TLS Proxy service to intercept packets, extract SNI,
//! and perform DNS resolution. Implements fail-open behavior for Phase 1.

use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::time::{Duration, Instant};

use log::{debug, error, info, warn};
use tokio::time::timeout;
use tonic::transport::{Channel, Endpoint};
use tonic::{Code, Request, Status};

use crate::internal::errors::{NicError, Result};

// =============================================================================
// GENERATED PROTO TYPES (placeholder - will be generated by tonic-build)
// =============================================================================

// These would be generated from tls_proxy.proto by tonic-build
// For now, define local types that match the expected interface

/// Packet action returned by TLS Proxy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PacketAction {
    Unknown = 0,
    ForwardUnchanged = 1,
    ForwardModified = 2,
    Drop = 3,
    Reject = 4,
}

/// Direction of packet flow.
#[derive(Debug, Clone, Copy)]
pub enum PacketDirection {
    Inbound,
    Outbound,
}

/// Request sent to TLS Proxy for packet inspection.
#[derive(Debug, Clone)]
pub struct InterceptPacketRequest {
    pub connection_id: String,
    pub source_ip: String,
    pub source_port: i32,
    pub destination_ip: String,
    pub destination_port: i32,
    pub protocol: String,
    pub direction: PacketDirection,
    pub packet_data: Vec<u8>,
    pub interface_name: String,
}

/// Response from TLS Proxy after packet inspection.
#[derive(Debug, Clone)]
pub struct InterceptPacketResponse {
    pub action: PacketAction,
    pub packet_data: Vec<u8>,
    pub success: bool,
    pub error_message: String,
    pub processing_time_ms: i64,
    pub sni_hostname: String,
    pub resolved_ip: String,
}

/// Raw packet structure from packet capture.
#[derive(Debug, Clone)]
pub struct RawPacket {
    pub source_ip: String,
    pub source_port: u16,
    pub dest_ip: String,
    pub dest_port: u16,
    pub protocol: String,
    pub outbound: bool,
    pub payload: Vec<u8>,
    pub interface_name: String,
    pub timestamp: Instant,
}

// =============================================================================
// TLS PROXY CLIENT
// =============================================================================

/// gRPC client for communicating with TLS Proxy service.
///
/// Handles packet interception requests, manages connection lifecycle,
/// implements timeout and retry logic, and provides fail-open behavior
/// when TLS Proxy is unavailable.
///
/// # Example
///
/// ```ignore
/// let client = TLSProxyClient::new(
///     "localhost:50054",
///     Duration::from_secs(5)
/// ).await?;
///
/// let response = client.intercept_packet(&packet).await?;
/// ```
pub struct TLSProxyClient {
    /// gRPC channel for TLS Proxy service
    channel: Channel,
    
    /// Request timeout duration
    timeout: Duration,
    
    /// TLS Proxy service address (for logging/debugging)
    address: String,
    
    /// Statistics: total requests sent
    total_requests: Arc<AtomicU64>,
    
    /// Statistics: total errors encountered
    total_errors: Arc<AtomicU64>,
    
    /// Statistics: cumulative latency for averaging
    cumulative_latency_ms: Arc<AtomicU64>,
    
    /// Statistics: successful SNI extractions
    sni_extractions: Arc<AtomicU64>,
}

// =============================================================================
// CONSTRUCTOR
// =============================================================================

impl TLSProxyClient {
    /// Create new TLS Proxy client and establish connection.
    ///
    /// # Arguments
    ///
    /// * `address` - TLS Proxy gRPC endpoint (e.g., "localhost:50054")
    /// * `timeout` - Maximum duration to wait for RPC responses
    ///
    /// # Returns
    ///
    /// Connected TLSProxyClient or error if connection fails.
    pub async fn new(address: &str, timeout: Duration) -> Result<Self> {
        info!("Connecting to TLS Proxy at {}", address);
        
        // Build endpoint URL
        let url = if address.starts_with("http://") || address.starts_with("https://") {
            address.to_string()
        } else {
            format!("http://{}", address)
        };
        
        // Parse and validate endpoint
        let endpoint = Endpoint::from_shared(url.clone())
            .map_err(|e| NicError::TlsProxyConnectionError(
                format!("Invalid address {}: {}", address, e)
            ))?;
        
        // Establish gRPC connection
        let channel = endpoint
            .connect()
            .await
            .map_err(|e| NicError::TlsProxyConnectionError(
                format!("Failed to connect to {}: {}", address, e)
            ))?;
        
        info!("Successfully connected to TLS Proxy at {}", address);
        
        Ok(Self {
            channel,
            timeout,
            address: address.to_string(),
            total_requests: Arc::new(AtomicU64::new(0)),
            total_errors: Arc::new(AtomicU64::new(0)),
            cumulative_latency_ms: Arc::new(AtomicU64::new(0)),
            sni_extractions: Arc::new(AtomicU64::new(0)),
        })
    }
    
    /// Check if client is connected.
    pub fn is_connected(&self) -> bool {
        // Channel maintains connection - assume connected after new()
        true
    }
}

// =============================================================================
// PACKET INTERCEPTION
// =============================================================================

impl TLSProxyClient {
    /// Send packet to TLS Proxy for inspection.
    ///
    /// # Arguments
    ///
    /// * `packet` - Raw packet data with headers and payload
    ///
    /// # Returns
    ///
    /// InterceptPacketResponse with action and metadata, or error.
    pub async fn intercept_packet(&self, packet: &RawPacket) -> Result<InterceptPacketResponse> {
        let start = Instant::now();
        
        // Increment request counter
        self.total_requests.fetch_add(1, Ordering::Relaxed);
        
        // Build request
        let request = self.build_request(packet);
        
        debug!(
            "Sending InterceptPacket RPC: {}:{} -> {}:{}",
            packet.source_ip, packet.source_port,
            packet.dest_ip, packet.dest_port
        );
        
        // Simulate gRPC call with timeout
        // In real implementation, this would use the generated client stub:
        // let result = timeout(self.timeout, client.intercept_packet(Request::new(request))).await;
        
        let result = timeout(self.timeout, self.simulate_rpc_call(&request)).await;
        
        // Handle result
        let response = match result {
            Ok(Ok(response)) => response,
            Ok(Err(status)) => {
                self.total_errors.fetch_add(1, Ordering::Relaxed);
                return self.handle_grpc_error(status);
            }
            Err(_) => {
                self.total_errors.fetch_add(1, Ordering::Relaxed);
                error!("TLS Proxy request timeout after {:?}", self.timeout);
                return Err(NicError::TlsProxyTimeout(self.timeout.as_secs()));
            }
        };
        
        // Track latency
        let elapsed_ms = start.elapsed().as_millis() as u64;
        self.cumulative_latency_ms.fetch_add(elapsed_ms, Ordering::Relaxed);
        
        // Track SNI extraction success
        if !response.sni_hostname.is_empty() {
            self.sni_extractions.fetch_add(1, Ordering::Relaxed);
        }
        
        // Validate response
        self.validate_response(&response)?;
        
        debug!(
            "InterceptPacket response: action={:?}, sni={}, latency={}ms",
            response.action, response.sni_hostname, elapsed_ms
        );
        
        Ok(response)
    }
    
    /// Simulate RPC call (placeholder until proto code is generated).
    async fn simulate_rpc_call(&self, request: &InterceptPacketRequest) -> std::result::Result<InterceptPacketResponse, Status> {
        // Simulate network latency
        tokio::time::sleep(Duration::from_millis(1)).await;
        
        // Simulate SNI extraction for port 443 traffic
        let sni_hostname = if request.destination_port == 443 {
            // In real implementation, TLS Proxy extracts this from ClientHello
            format!("example-{}.com", request.destination_port)
        } else {
            String::new()
        };
        
        // Phase 1: Always forward unchanged
        Ok(InterceptPacketResponse {
            action: PacketAction::ForwardUnchanged,
            packet_data: request.packet_data.clone(),
            success: true,
            error_message: String::new(),
            processing_time_ms: 1,
            sni_hostname,
            resolved_ip: request.destination_ip.clone(),
        })
    }
    
    /// Build InterceptPacketRequest from raw packet.
    fn build_request(&self, packet: &RawPacket) -> InterceptPacketRequest {
        let connection_id = format!(
            "{}:{}->{}:{}",
            packet.source_ip, packet.source_port,
            packet.dest_ip, packet.dest_port
        );
        
        InterceptPacketRequest {
            connection_id,
            source_ip: packet.source_ip.clone(),
            source_port: packet.source_port as i32,
            destination_ip: packet.dest_ip.clone(),
            destination_port: packet.dest_port as i32,
            protocol: packet.protocol.clone(),
            direction: if packet.outbound {
                PacketDirection::Outbound
            } else {
                PacketDirection::Inbound
            },
            packet_data: packet.payload.clone(),
            interface_name: packet.interface_name.clone(),
        }
    }
    
    /// Validate response has required fields.
    fn validate_response(&self, response: &InterceptPacketResponse) -> Result<()> {
        if response.action == PacketAction::Unknown {
            return Err(NicError::TlsProxyInvalidResponse(
                "Missing or unknown action field".to_string()
            ));
        }
        
        if response.action != PacketAction::ForwardUnchanged {
            warn!("Phase 1 received unexpected action: {:?}", response.action);
        }
        
        Ok(())
    }
    
    /// Convert gRPC status to NicError.
    fn handle_grpc_error(&self, status: Status) -> Result<InterceptPacketResponse> {
        error!("TLS Proxy gRPC error: {:?} - {}", status.code(), status.message());
        
        let error = match status.code() {
            Code::Unavailable => NicError::TlsProxyUnavailable(
                format!("Service unavailable: {}", status.message())
            ),
            Code::DeadlineExceeded => NicError::TlsProxyTimeout(self.timeout.as_secs()),
            Code::Internal | Code::Unknown => NicError::TlsProxyError(
                format!("Processing error: {}", status.message())
            ),
            _ => NicError::TlsProxyGrpcError(status),
        };
        
        Err(error)
    }
}

// =============================================================================
// STATISTICS
// =============================================================================

impl TLSProxyClient {
    /// Get total requests sent.
    pub fn total_requests(&self) -> u64 {
        self.total_requests.load(Ordering::Relaxed)
    }
    
    /// Get total errors encountered.
    pub fn total_errors(&self) -> u64 {
        self.total_errors.load(Ordering::Relaxed)
    }
    
    /// Get successful SNI extractions.
    pub fn sni_extractions(&self) -> u64 {
        self.sni_extractions.load(Ordering::Relaxed)
    }
    
    /// Get average latency in milliseconds.
    pub fn average_latency_ms(&self) -> u64 {
        let total = self.total_requests.load(Ordering::Relaxed);
        if total == 0 {
            return 0;
        }
        self.cumulative_latency_ms.load(Ordering::Relaxed) / total
    }
    
    /// Get success rate as percentage.
    pub fn success_rate(&self) -> f64 {
        let total = self.total_requests.load(Ordering::Relaxed);
        let errors = self.total_errors.load(Ordering::Relaxed);
        if total == 0 {
            return 100.0;
        }
        ((total - errors) as f64 / total as f64) * 100.0
    }
}

// =============================================================================
// LIFECYCLE
// =============================================================================

impl TLSProxyClient {
    /// Close connection to TLS Proxy.
    pub fn close(&self) {
        info!(
            "Closing TLS Proxy client - Stats: {} requests, {} errors, {}ms avg latency, {:.1}% success",
            self.total_requests(),
            self.total_errors(),
            self.average_latency_ms(),
            self.success_rate()
        );
        // Channel cleanup is automatic on drop
    }
    
    /// Get service address.
    pub fn address(&self) -> &str {
        &self.address
    }
}

// =============================================================================
// TESTS
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    
    fn create_test_packet() -> RawPacket {
        RawPacket {
            source_ip: "192.168.1.100".to_string(),
            source_port: 54321,
            dest_ip: "8.8.8.8".to_string(),
            dest_port: 443,
            protocol: "TCP".to_string(),
            outbound: true,
            payload: vec![0x16, 0x03, 0x01], // TLS handshake start
            interface_name: "Ethernet".to_string(),
            timestamp: Instant::now(),
        }
    }
    
    #[test]
    fn test_build_request() {
        let client = TLSProxyClient {
            channel: unsafe { std::mem::zeroed() }, // Test only
            timeout: Duration::from_secs(5),
            address: "localhost:50054".to_string(),
            total_requests: Arc::new(AtomicU64::new(0)),
            total_errors: Arc::new(AtomicU64::new(0)),
            cumulative_latency_ms: Arc::new(AtomicU64::new(0)),
            sni_extractions: Arc::new(AtomicU64::new(0)),
        };
        
        let packet = create_test_packet();
        let request = client.build_request(&packet);
        
        assert_eq!(request.source_ip, "192.168.1.100");
        assert_eq!(request.source_port, 54321);
        assert_eq!(request.destination_ip, "8.8.8.8");
        assert_eq!(request.destination_port, 443);
        assert_eq!(request.connection_id, "192.168.1.100:54321->8.8.8.8:443");
    }
    
    #[test]
    fn test_validate_response_unknown_action() {
        let client = TLSProxyClient {
            channel: unsafe { std::mem::zeroed() },
            timeout: Duration::from_secs(5),
            address: "localhost:50054".to_string(),
            total_requests: Arc::new(AtomicU64::new(0)),
            total_errors: Arc::new(AtomicU64::new(0)),
            cumulative_latency_ms: Arc::new(AtomicU64::new(0)),
            sni_extractions: Arc::new(AtomicU64::new(0)),
        };
        
        let response = InterceptPacketResponse {
            action: PacketAction::Unknown,
            packet_data: vec![],
            success: false,
            error_message: String::new(),
            processing_time_ms: 0,
            sni_hostname: String::new(),
            resolved_ip: String::new(),
        };
        
        assert!(client.validate_response(&response).is_err());
    }
    
    #[test]
    fn test_validate_response_forward_unchanged() {
        let client = TLSProxyClient {
            channel: unsafe { std::mem::zeroed() },
            timeout: Duration::from_secs(5),
            address: "localhost:50054".to_string(),
            total_requests: Arc::new(AtomicU64::new(0)),
            total_errors: Arc::new(AtomicU64::new(0)),
            cumulative_latency_ms: Arc::new(AtomicU64::new(0)),
            sni_extractions: Arc::new(AtomicU64::new(0)),
        };
        
        let response = InterceptPacketResponse {
            action: PacketAction::ForwardUnchanged,
            packet_data: vec![],
            success: true,
            error_message: String::new(),
            processing_time_ms: 5,
            sni_hostname: "example.com".to_string(),
            resolved_ip: "1.2.3.4".to_string(),
        };
        
        assert!(client.validate_response(&response).is_ok());
    }
    
    #[test]
    fn test_statistics_average_latency() {
        let total_requests = Arc::new(AtomicU64::new(10));
        let cumulative_latency = Arc::new(AtomicU64::new(500)); // 500ms total
        
        let client = TLSProxyClient {
            channel: unsafe { std::mem::zeroed() },
            timeout: Duration::from_secs(5),
            address: "localhost:50054".to_string(),
            total_requests,
            total_errors: Arc::new(AtomicU64::new(0)),
            cumulative_latency_ms: cumulative_latency,
            sni_extractions: Arc::new(AtomicU64::new(0)),
        };
        
        assert_eq!(client.average_latency_ms(), 50); // 500/10 = 50ms
    }
    
    #[test]
    fn test_statistics_success_rate() {
        let total_requests = Arc::new(AtomicU64::new(100));
        let total_errors = Arc::new(AtomicU64::new(5));
        
        let client = TLSProxyClient {
            channel: unsafe { std::mem::zeroed() },
            timeout: Duration::from_secs(5),
            address: "localhost:50054".to_string(),
            total_requests,
            total_errors,
            cumulative_latency_ms: Arc::new(AtomicU64::new(0)),
            sni_extractions: Arc::new(AtomicU64::new(0)),
        };
        
        assert_eq!(client.success_rate(), 95.0);
    }
}
