// Protocol Buffers definition for DHCP Monitor gRPC Service
// Compile with: protoc --go_out=. --go-grpc_out=. proto/dhcp_monitor.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/dhcp_monitor.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Device - Complete device information from database
type Device struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeviceId        string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                       // UUID primary key
	MacAddress      string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`                 // AA:BB:CC:DD:EE:FF format
	CurrentIp       string                 `protobuf:"bytes,3,opt,name=current_ip,json=currentIp,proto3" json:"current_ip,omitempty"`                    // IPv4 or IPv6 address
	Hostname        string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                                       // Device-reported hostname
	DeviceType      string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`                 // Laptop, Phone, IoT, Printer, Server, Unknown
	Vendor          string                 `protobuf:"bytes,6,opt,name=vendor,proto3" json:"vendor,omitempty"`                                           // MAC OUI vendor (Apple, Samsung, Dell)
	TrustStatus     string                 `protobuf:"bytes,7,opt,name=trust_status,json=trustStatus,proto3" json:"trust_status,omitempty"`              // UNTRUSTED, TRUSTED, BLOCKED
	InterfaceName   string                 `protobuf:"bytes,8,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`        // "Mobile Hotspot", "Ethernet", "vEthernet"
	InterfaceIndex  int32                  `protobuf:"varint,9,opt,name=interface_index,json=interfaceIndex,proto3" json:"interface_index,omitempty"`    // Windows interface index
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`                                          // ACTIVE, OFFLINE, EXPIRED
	DetectionMethod string                 `protobuf:"bytes,11,opt,name=detection_method,json=detectionMethod,proto3" json:"detection_method,omitempty"` // IP_HELPER_API, DHCP_EVENT_LOG, ARP_TABLE
	FirstSeen       string                 `protobuf:"bytes,12,opt,name=first_seen,json=firstSeen,proto3" json:"first_seen,omitempty"`                   // ISO 8601 timestamp
	LastSeen        string                 `protobuf:"bytes,13,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`                      // ISO 8601 timestamp
	IsOnline        bool                   `protobuf:"varint,14,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`                     // Current online status
	// Phase 3A: Portal tracking for ALLOW_ONCE policy
	PortalShown   bool   `protobuf:"varint,15,opt,name=portal_shown,json=portalShown,proto3" json:"portal_shown,omitempty"`        // Has device seen captive portal?
	PortalShownAt string `protobuf:"bytes,16,opt,name=portal_shown_at,json=portalShownAt,proto3" json:"portal_shown_at,omitempty"` // ISO 8601 timestamp when portal was shown
	// Phase 3B: CA certificate tracking
	CaCertInstalled   bool   `protobuf:"varint,17,opt,name=ca_cert_installed,json=caCertInstalled,proto3" json:"ca_cert_installed,omitempty"`        // Has device installed SafeOps CA certificate?
	CaCertInstalledAt string `protobuf:"bytes,18,opt,name=ca_cert_installed_at,json=caCertInstalledAt,proto3" json:"ca_cert_installed_at,omitempty"` // ISO 8601 timestamp when CA cert was installed
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *Device) GetCurrentIp() string {
	if x != nil {
		return x.CurrentIp
	}
	return ""
}

func (x *Device) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Device) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Device) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *Device) GetTrustStatus() string {
	if x != nil {
		return x.TrustStatus
	}
	return ""
}

func (x *Device) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *Device) GetInterfaceIndex() int32 {
	if x != nil {
		return x.InterfaceIndex
	}
	return 0
}

func (x *Device) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Device) GetDetectionMethod() string {
	if x != nil {
		return x.DetectionMethod
	}
	return ""
}

func (x *Device) GetFirstSeen() string {
	if x != nil {
		return x.FirstSeen
	}
	return ""
}

func (x *Device) GetLastSeen() string {
	if x != nil {
		return x.LastSeen
	}
	return ""
}

func (x *Device) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *Device) GetPortalShown() bool {
	if x != nil {
		return x.PortalShown
	}
	return false
}

func (x *Device) GetPortalShownAt() string {
	if x != nil {
		return x.PortalShownAt
	}
	return ""
}

func (x *Device) GetCaCertInstalled() bool {
	if x != nil {
		return x.CaCertInstalled
	}
	return false
}

func (x *Device) GetCaCertInstalledAt() string {
	if x != nil {
		return x.CaCertInstalledAt
	}
	return ""
}

// IPRequest - Query device by IP address
type IPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IpAddress     string                 `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // IPv4 or IPv6 address to lookup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPRequest) Reset() {
	*x = IPRequest{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPRequest) ProtoMessage() {}

func (x *IPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPRequest.ProtoReflect.Descriptor instead.
func (*IPRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *IPRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// MACRequest - Query device by MAC address
type MACRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // Hardware address (AA:BB:CC:DD:EE:FF)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MACRequest) Reset() {
	*x = MACRequest{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MACRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MACRequest) ProtoMessage() {}

func (x *MACRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MACRequest.ProtoReflect.Descriptor instead.
func (*MACRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *MACRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

// DeviceIDRequest - Query device by UUID
type DeviceIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // UUID of device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceIDRequest) Reset() {
	*x = DeviceIDRequest{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceIDRequest) ProtoMessage() {}

func (x *DeviceIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceIDRequest.ProtoReflect.Descriptor instead.
func (*DeviceIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceIDRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// TrustUpdateRequest - Update device trust status
type TrustUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`          // UUID of device to update
	TrustStatus   string                 `protobuf:"bytes,2,opt,name=trust_status,json=trustStatus,proto3" json:"trust_status,omitempty"` // TRUSTED, UNTRUSTED, or BLOCKED
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustUpdateRequest) Reset() {
	*x = TrustUpdateRequest{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustUpdateRequest) ProtoMessage() {}

func (x *TrustUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustUpdateRequest.ProtoReflect.Descriptor instead.
func (*TrustUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{4}
}

func (x *TrustUpdateRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TrustUpdateRequest) GetTrustStatus() string {
	if x != nil {
		return x.TrustStatus
	}
	return ""
}

// MarkPortalShownRequest - Mark that device has seen captive portal
// Phase 3A: For ALLOW_ONCE policy tracking
type MarkPortalShownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`    // UUID of device (or IP address)
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // Alternative: device IP (for convenience)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPortalShownRequest) Reset() {
	*x = MarkPortalShownRequest{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPortalShownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPortalShownRequest) ProtoMessage() {}

func (x *MarkPortalShownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPortalShownRequest.ProtoReflect.Descriptor instead.
func (*MarkPortalShownRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{5}
}

func (x *MarkPortalShownRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MarkPortalShownRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

// MarkCACertInstalledRequest - Mark that device has installed CA certificate
// Phase 3B: For CA cert distribution tracking
type MarkCACertInstalledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // UUID of device
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`    // Alternative: device IP (for convenience)
	MacAddress    string                 `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"` // Alternative: device MAC (for convenience)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkCACertInstalledRequest) Reset() {
	*x = MarkCACertInstalledRequest{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkCACertInstalledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkCACertInstalledRequest) ProtoMessage() {}

func (x *MarkCACertInstalledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkCACertInstalledRequest.ProtoReflect.Descriptor instead.
func (*MarkCACertInstalledRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{6}
}

func (x *MarkCACertInstalledRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *MarkCACertInstalledRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *MarkCACertInstalledRequest) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

// ListDevicesRequest - Paginated device list with filters
type ListDevicesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilterByTrust  string                 `protobuf:"bytes,1,opt,name=filter_by_trust,json=filterByTrust,proto3" json:"filter_by_trust,omitempty"`    // Optional: TRUSTED, UNTRUSTED, BLOCKED, or empty for all
	FilterByType   string                 `protobuf:"bytes,2,opt,name=filter_by_type,json=filterByType,proto3" json:"filter_by_type,omitempty"`       // Optional: Laptop, Phone, IoT, etc., or empty for all
	FilterByStatus string                 `protobuf:"bytes,3,opt,name=filter_by_status,json=filterByStatus,proto3" json:"filter_by_status,omitempty"` // Optional: ACTIVE, OFFLINE, EXPIRED, or empty for all
	InterfaceName  string                 `protobuf:"bytes,4,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`      // Optional: Filter by interface name
	Limit          int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`                                          // Max devices to return (0 = no limit)
	Offset         int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`                                        // Number of devices to skip (pagination)
	OnlineOnly     bool                   `protobuf:"varint,7,opt,name=online_only,json=onlineOnly,proto3" json:"online_only,omitempty"`              // If true, only return online devices
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{7}
}

func (x *ListDevicesRequest) GetFilterByTrust() string {
	if x != nil {
		return x.FilterByTrust
	}
	return ""
}

func (x *ListDevicesRequest) GetFilterByType() string {
	if x != nil {
		return x.FilterByType
	}
	return ""
}

func (x *ListDevicesRequest) GetFilterByStatus() string {
	if x != nil {
		return x.FilterByStatus
	}
	return ""
}

func (x *ListDevicesRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *ListDevicesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDevicesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDevicesRequest) GetOnlineOnly() bool {
	if x != nil {
		return x.OnlineOnly
	}
	return false
}

// DeviceList - Response containing array of devices
type DeviceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`                          // Array of device records
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total matching devices (for pagination)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceList) Reset() {
	*x = DeviceList{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceList) ProtoMessage() {}

func (x *DeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceList.ProtoReflect.Descriptor instead.
func (*DeviceList) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceList) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *DeviceList) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// DeviceStats - Aggregate statistics
type DeviceStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalDevices     int32                  `protobuf:"varint,1,opt,name=total_devices,json=totalDevices,proto3" json:"total_devices,omitempty"`             // Total devices ever seen
	ActiveDevices    int32                  `protobuf:"varint,2,opt,name=active_devices,json=activeDevices,proto3" json:"active_devices,omitempty"`          // Devices with ACTIVE status
	TrustedDevices   int32                  `protobuf:"varint,3,opt,name=trusted_devices,json=trustedDevices,proto3" json:"trusted_devices,omitempty"`       // Devices with TRUSTED status
	UntrustedDevices int32                  `protobuf:"varint,4,opt,name=untrusted_devices,json=untrustedDevices,proto3" json:"untrusted_devices,omitempty"` // Devices with UNTRUSTED status
	BlockedDevices   int32                  `protobuf:"varint,5,opt,name=blocked_devices,json=blockedDevices,proto3" json:"blocked_devices,omitempty"`       // Devices with BLOCKED status
	OfflineDevices   int32                  `protobuf:"varint,6,opt,name=offline_devices,json=offlineDevices,proto3" json:"offline_devices,omitempty"`       // Devices with OFFLINE status
	OnlineDevices    int32                  `protobuf:"varint,7,opt,name=online_devices,json=onlineDevices,proto3" json:"online_devices,omitempty"`          // Devices currently online
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeviceStats) Reset() {
	*x = DeviceStats{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStats) ProtoMessage() {}

func (x *DeviceStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStats.ProtoReflect.Descriptor instead.
func (*DeviceStats) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{9}
}

func (x *DeviceStats) GetTotalDevices() int32 {
	if x != nil {
		return x.TotalDevices
	}
	return 0
}

func (x *DeviceStats) GetActiveDevices() int32 {
	if x != nil {
		return x.ActiveDevices
	}
	return 0
}

func (x *DeviceStats) GetTrustedDevices() int32 {
	if x != nil {
		return x.TrustedDevices
	}
	return 0
}

func (x *DeviceStats) GetUntrustedDevices() int32 {
	if x != nil {
		return x.UntrustedDevices
	}
	return 0
}

func (x *DeviceStats) GetBlockedDevices() int32 {
	if x != nil {
		return x.BlockedDevices
	}
	return 0
}

func (x *DeviceStats) GetOfflineDevices() int32 {
	if x != nil {
		return x.OfflineDevices
	}
	return 0
}

func (x *DeviceStats) GetOnlineDevices() int32 {
	if x != nil {
		return x.OnlineDevices
	}
	return 0
}

// Empty - For RPCs that don't need parameters
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{10}
}

// HealthStatus - Service health check response
type HealthStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Healthy        bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`                                    // Overall health status
	DatabaseStatus string                 `protobuf:"bytes,2,opt,name=database_status,json=databaseStatus,proto3" json:"database_status,omitempty"` // "connected" or error message
	Uptime         string                 `protobuf:"bytes,3,opt,name=uptime,proto3" json:"uptime,omitempty"`                                       // Service uptime duration
	TotalQueries   int64                  `protobuf:"varint,4,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`      // Total queries processed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{11}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetDatabaseStatus() string {
	if x != nil {
		return x.DatabaseStatus
	}
	return ""
}

func (x *HealthStatus) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthStatus) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

// DhcpEvent - DHCP packet captured by Packet Engine
// Sent to DHCP Monitor for device tracking and database storage
type DhcpEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacAddress    string                 `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`          // Client MAC from chaddr field (AA:BB:CC:DD:EE:FF)
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                // Assigned IP from yiaddr field
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`                                // DHCP Option 12 - Host Name
	VendorClass   string                 `protobuf:"bytes,4,opt,name=vendor_class,json=vendorClass,proto3" json:"vendor_class,omitempty"`       // DHCP Option 60 - Vendor Class Identifier
	MessageType   string                 `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`       // DISCOVER, OFFER, REQUEST, ACK, NAK, RELEASE, INFORM
	InterfaceName string                 `protobuf:"bytes,6,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"` // Network interface where packet was captured
	Timestamp     float64                `protobuf:"fixed64,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                            // Unix timestamp when packet was captured
	RequestedIp   string                 `protobuf:"bytes,8,opt,name=requested_ip,json=requestedIp,proto3" json:"requested_ip,omitempty"`       // DHCP Option 50 - Requested IP Address
	ServerIp      string                 `protobuf:"bytes,9,opt,name=server_ip,json=serverIp,proto3" json:"server_ip,omitempty"`                // DHCP Server IP from siaddr field
	GatewayIp     string                 `protobuf:"bytes,10,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`            // DHCP Option 3 - Router (gateway) IP
	SubnetMask    string                 `protobuf:"bytes,11,opt,name=subnet_mask,json=subnetMask,proto3" json:"subnet_mask,omitempty"`         // DHCP Option 1 - Subnet Mask
	LeaseTime     int32                  `protobuf:"varint,12,opt,name=lease_time,json=leaseTime,proto3" json:"lease_time,omitempty"`           // DHCP Option 51 - IP Address Lease Time (seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DhcpEvent) Reset() {
	*x = DhcpEvent{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DhcpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DhcpEvent) ProtoMessage() {}

func (x *DhcpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DhcpEvent.ProtoReflect.Descriptor instead.
func (*DhcpEvent) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{12}
}

func (x *DhcpEvent) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *DhcpEvent) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *DhcpEvent) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DhcpEvent) GetVendorClass() string {
	if x != nil {
		return x.VendorClass
	}
	return ""
}

func (x *DhcpEvent) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *DhcpEvent) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *DhcpEvent) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DhcpEvent) GetRequestedIp() string {
	if x != nil {
		return x.RequestedIp
	}
	return ""
}

func (x *DhcpEvent) GetServerIp() string {
	if x != nil {
		return x.ServerIp
	}
	return ""
}

func (x *DhcpEvent) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *DhcpEvent) GetSubnetMask() string {
	if x != nil {
		return x.SubnetMask
	}
	return ""
}

func (x *DhcpEvent) GetLeaseTime() int32 {
	if x != nil {
		return x.LeaseTime
	}
	return 0
}

// DhcpEventResponse - Response after processing DHCP event
type DhcpEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                              // Whether event was processed successfully
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`             // UUID of created/updated device
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                               // Status message or error
	IsNewDevice   bool                   `protobuf:"varint,4,opt,name=is_new_device,json=isNewDevice,proto3" json:"is_new_device,omitempty"` // True if this is a newly detected device
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DhcpEventResponse) Reset() {
	*x = DhcpEventResponse{}
	mi := &file_proto_dhcp_monitor_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DhcpEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DhcpEventResponse) ProtoMessage() {}

func (x *DhcpEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dhcp_monitor_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DhcpEventResponse.ProtoReflect.Descriptor instead.
func (*DhcpEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_dhcp_monitor_proto_rawDescGZIP(), []int{13}
}

func (x *DhcpEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DhcpEventResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DhcpEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DhcpEventResponse) GetIsNewDevice() bool {
	if x != nil {
		return x.IsNewDevice
	}
	return false
}

var File_proto_dhcp_monitor_proto protoreflect.FileDescriptor

const file_proto_dhcp_monitor_proto_rawDesc = "" +
	"\n" +
	"\x18proto/dhcp_monitor.proto\x12\fdhcp_monitor\"\xf1\x04\n" +
	"\x06Device\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"current_ip\x18\x03 \x01(\tR\tcurrentIp\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12\x16\n" +
	"\x06vendor\x18\x06 \x01(\tR\x06vendor\x12!\n" +
	"\ftrust_status\x18\a \x01(\tR\vtrustStatus\x12%\n" +
	"\x0einterface_name\x18\b \x01(\tR\rinterfaceName\x12'\n" +
	"\x0finterface_index\x18\t \x01(\x05R\x0einterfaceIndex\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12)\n" +
	"\x10detection_method\x18\v \x01(\tR\x0fdetectionMethod\x12\x1d\n" +
	"\n" +
	"first_seen\x18\f \x01(\tR\tfirstSeen\x12\x1b\n" +
	"\tlast_seen\x18\r \x01(\tR\blastSeen\x12\x1b\n" +
	"\tis_online\x18\x0e \x01(\bR\bisOnline\x12!\n" +
	"\fportal_shown\x18\x0f \x01(\bR\vportalShown\x12&\n" +
	"\x0fportal_shown_at\x18\x10 \x01(\tR\rportalShownAt\x12*\n" +
	"\x11ca_cert_installed\x18\x11 \x01(\bR\x0fcaCertInstalled\x12/\n" +
	"\x14ca_cert_installed_at\x18\x12 \x01(\tR\x11caCertInstalledAt\"*\n" +
	"\tIPRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\"-\n" +
	"\n" +
	"MACRequest\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\".\n" +
	"\x0fDeviceIDRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"T\n" +
	"\x12TrustUpdateRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12!\n" +
	"\ftrust_status\x18\x02 \x01(\tR\vtrustStatus\"T\n" +
	"\x16MarkPortalShownRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\"y\n" +
	"\x1aMarkCACertInstalledRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1f\n" +
	"\vmac_address\x18\x03 \x01(\tR\n" +
	"macAddress\"\x82\x02\n" +
	"\x12ListDevicesRequest\x12&\n" +
	"\x0ffilter_by_trust\x18\x01 \x01(\tR\rfilterByTrust\x12$\n" +
	"\x0efilter_by_type\x18\x02 \x01(\tR\ffilterByType\x12(\n" +
	"\x10filter_by_status\x18\x03 \x01(\tR\x0efilterByStatus\x12%\n" +
	"\x0einterface_name\x18\x04 \x01(\tR\rinterfaceName\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vonline_only\x18\a \x01(\bR\n" +
	"onlineOnly\"]\n" +
	"\n" +
	"DeviceList\x12.\n" +
	"\adevices\x18\x01 \x03(\v2\x14.dhcp_monitor.DeviceR\adevices\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xa8\x02\n" +
	"\vDeviceStats\x12#\n" +
	"\rtotal_devices\x18\x01 \x01(\x05R\ftotalDevices\x12%\n" +
	"\x0eactive_devices\x18\x02 \x01(\x05R\ractiveDevices\x12'\n" +
	"\x0ftrusted_devices\x18\x03 \x01(\x05R\x0etrustedDevices\x12+\n" +
	"\x11untrusted_devices\x18\x04 \x01(\x05R\x10untrustedDevices\x12'\n" +
	"\x0fblocked_devices\x18\x05 \x01(\x05R\x0eblockedDevices\x12'\n" +
	"\x0foffline_devices\x18\x06 \x01(\x05R\x0eofflineDevices\x12%\n" +
	"\x0eonline_devices\x18\a \x01(\x05R\ronlineDevices\"\a\n" +
	"\x05Empty\"\x8e\x01\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12'\n" +
	"\x0fdatabase_status\x18\x02 \x01(\tR\x0edatabaseStatus\x12\x16\n" +
	"\x06uptime\x18\x03 \x01(\tR\x06uptime\x12#\n" +
	"\rtotal_queries\x18\x04 \x01(\x03R\ftotalQueries\"\x8f\x03\n" +
	"\tDhcpEvent\x12\x1f\n" +
	"\vmac_address\x18\x01 \x01(\tR\n" +
	"macAddress\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12!\n" +
	"\fvendor_class\x18\x04 \x01(\tR\vvendorClass\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageType\x12%\n" +
	"\x0einterface_name\x18\x06 \x01(\tR\rinterfaceName\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x01R\ttimestamp\x12!\n" +
	"\frequested_ip\x18\b \x01(\tR\vrequestedIp\x12\x1b\n" +
	"\tserver_ip\x18\t \x01(\tR\bserverIp\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\n" +
	" \x01(\tR\tgatewayIp\x12\x1f\n" +
	"\vsubnet_mask\x18\v \x01(\tR\n" +
	"subnetMask\x12\x1d\n" +
	"\n" +
	"lease_time\x18\f \x01(\x05R\tleaseTime\"\x88\x01\n" +
	"\x11DhcpEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\"\n" +
	"\ris_new_device\x18\x04 \x01(\bR\visNewDevice2\xe2\x05\n" +
	"\vDHCPMonitor\x12>\n" +
	"\rGetDeviceByIP\x12\x17.dhcp_monitor.IPRequest\x1a\x14.dhcp_monitor.Device\x12@\n" +
	"\x0eGetDeviceByMAC\x12\x18.dhcp_monitor.MACRequest\x1a\x14.dhcp_monitor.Device\x12D\n" +
	"\rGetDeviceByID\x12\x1d.dhcp_monitor.DeviceIDRequest\x1a\x14.dhcp_monitor.Device\x12K\n" +
	"\x11UpdateTrustStatus\x12 .dhcp_monitor.TrustUpdateRequest\x1a\x14.dhcp_monitor.Device\x12M\n" +
	"\x0fMarkPortalShown\x12$.dhcp_monitor.MarkPortalShownRequest\x1a\x14.dhcp_monitor.Device\x12U\n" +
	"\x13MarkCACertInstalled\x12(.dhcp_monitor.MarkCACertInstalledRequest\x1a\x14.dhcp_monitor.Device\x12I\n" +
	"\vListDevices\x12 .dhcp_monitor.ListDevicesRequest\x1a\x18.dhcp_monitor.DeviceList\x12@\n" +
	"\x0eGetDeviceStats\x12\x13.dhcp_monitor.Empty\x1a\x19.dhcp_monitor.DeviceStats\x12>\n" +
	"\vHealthCheck\x12\x13.dhcp_monitor.Empty\x1a\x1a.dhcp_monitor.HealthStatus\x12K\n" +
	"\x0fReportDhcpEvent\x12\x17.dhcp_monitor.DhcpEvent\x1a\x1f.dhcp_monitor.DhcpEventResponseB\x18Z\x16dhcp_monitor/proto/genb\x06proto3"

var (
	file_proto_dhcp_monitor_proto_rawDescOnce sync.Once
	file_proto_dhcp_monitor_proto_rawDescData []byte
)

func file_proto_dhcp_monitor_proto_rawDescGZIP() []byte {
	file_proto_dhcp_monitor_proto_rawDescOnce.Do(func() {
		file_proto_dhcp_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dhcp_monitor_proto_rawDesc), len(file_proto_dhcp_monitor_proto_rawDesc)))
	})
	return file_proto_dhcp_monitor_proto_rawDescData
}

var file_proto_dhcp_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_dhcp_monitor_proto_goTypes = []any{
	(*Device)(nil),                     // 0: dhcp_monitor.Device
	(*IPRequest)(nil),                  // 1: dhcp_monitor.IPRequest
	(*MACRequest)(nil),                 // 2: dhcp_monitor.MACRequest
	(*DeviceIDRequest)(nil),            // 3: dhcp_monitor.DeviceIDRequest
	(*TrustUpdateRequest)(nil),         // 4: dhcp_monitor.TrustUpdateRequest
	(*MarkPortalShownRequest)(nil),     // 5: dhcp_monitor.MarkPortalShownRequest
	(*MarkCACertInstalledRequest)(nil), // 6: dhcp_monitor.MarkCACertInstalledRequest
	(*ListDevicesRequest)(nil),         // 7: dhcp_monitor.ListDevicesRequest
	(*DeviceList)(nil),                 // 8: dhcp_monitor.DeviceList
	(*DeviceStats)(nil),                // 9: dhcp_monitor.DeviceStats
	(*Empty)(nil),                      // 10: dhcp_monitor.Empty
	(*HealthStatus)(nil),               // 11: dhcp_monitor.HealthStatus
	(*DhcpEvent)(nil),                  // 12: dhcp_monitor.DhcpEvent
	(*DhcpEventResponse)(nil),          // 13: dhcp_monitor.DhcpEventResponse
}
var file_proto_dhcp_monitor_proto_depIdxs = []int32{
	0,  // 0: dhcp_monitor.DeviceList.devices:type_name -> dhcp_monitor.Device
	1,  // 1: dhcp_monitor.DHCPMonitor.GetDeviceByIP:input_type -> dhcp_monitor.IPRequest
	2,  // 2: dhcp_monitor.DHCPMonitor.GetDeviceByMAC:input_type -> dhcp_monitor.MACRequest
	3,  // 3: dhcp_monitor.DHCPMonitor.GetDeviceByID:input_type -> dhcp_monitor.DeviceIDRequest
	4,  // 4: dhcp_monitor.DHCPMonitor.UpdateTrustStatus:input_type -> dhcp_monitor.TrustUpdateRequest
	5,  // 5: dhcp_monitor.DHCPMonitor.MarkPortalShown:input_type -> dhcp_monitor.MarkPortalShownRequest
	6,  // 6: dhcp_monitor.DHCPMonitor.MarkCACertInstalled:input_type -> dhcp_monitor.MarkCACertInstalledRequest
	7,  // 7: dhcp_monitor.DHCPMonitor.ListDevices:input_type -> dhcp_monitor.ListDevicesRequest
	10, // 8: dhcp_monitor.DHCPMonitor.GetDeviceStats:input_type -> dhcp_monitor.Empty
	10, // 9: dhcp_monitor.DHCPMonitor.HealthCheck:input_type -> dhcp_monitor.Empty
	12, // 10: dhcp_monitor.DHCPMonitor.ReportDhcpEvent:input_type -> dhcp_monitor.DhcpEvent
	0,  // 11: dhcp_monitor.DHCPMonitor.GetDeviceByIP:output_type -> dhcp_monitor.Device
	0,  // 12: dhcp_monitor.DHCPMonitor.GetDeviceByMAC:output_type -> dhcp_monitor.Device
	0,  // 13: dhcp_monitor.DHCPMonitor.GetDeviceByID:output_type -> dhcp_monitor.Device
	0,  // 14: dhcp_monitor.DHCPMonitor.UpdateTrustStatus:output_type -> dhcp_monitor.Device
	0,  // 15: dhcp_monitor.DHCPMonitor.MarkPortalShown:output_type -> dhcp_monitor.Device
	0,  // 16: dhcp_monitor.DHCPMonitor.MarkCACertInstalled:output_type -> dhcp_monitor.Device
	8,  // 17: dhcp_monitor.DHCPMonitor.ListDevices:output_type -> dhcp_monitor.DeviceList
	9,  // 18: dhcp_monitor.DHCPMonitor.GetDeviceStats:output_type -> dhcp_monitor.DeviceStats
	11, // 19: dhcp_monitor.DHCPMonitor.HealthCheck:output_type -> dhcp_monitor.HealthStatus
	13, // 20: dhcp_monitor.DHCPMonitor.ReportDhcpEvent:output_type -> dhcp_monitor.DhcpEventResponse
	11, // [11:21] is the sub-list for method output_type
	1,  // [1:11] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_dhcp_monitor_proto_init() }
func file_proto_dhcp_monitor_proto_init() {
	if File_proto_dhcp_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dhcp_monitor_proto_rawDesc), len(file_proto_dhcp_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_dhcp_monitor_proto_goTypes,
		DependencyIndexes: file_proto_dhcp_monitor_proto_depIdxs,
		MessageInfos:      file_proto_dhcp_monitor_proto_msgTypes,
	}.Build()
	File_proto_dhcp_monitor_proto = out.File
	file_proto_dhcp_monitor_proto_goTypes = nil
	file_proto_dhcp_monitor_proto_depIdxs = nil
}
