// This file is @generated by prost-build.
/// Start service request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartServiceRequest {
    /// Name of service to start
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Environment variable overrides
    #[prost(map = "string, string", tag = "2")]
    pub env_overrides: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Block until service is healthy
    #[prost(bool, tag = "3")]
    pub wait_for_ready: bool,
}
/// Stop service request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StopServiceRequest {
    /// Name of service to stop
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Force kill if graceful shutdown fails
    #[prost(bool, tag = "2")]
    pub force: bool,
    /// Graceful shutdown timeout
    #[prost(uint32, tag = "3")]
    pub timeout_seconds: u32,
    /// Attempt graceful shutdown
    #[prost(bool, tag = "4")]
    pub graceful: bool,
}
/// Restart service request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RestartServiceRequest {
    /// Name of service to restart
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Use graceful restart
    #[prost(bool, tag = "2")]
    pub graceful: bool,
    /// Seconds to drain connections
    #[prost(uint32, tag = "3")]
    pub drain_timeout: u32,
}
/// Service status request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceStatusRequest {
    /// Service name, empty for all services
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
}
/// Health check request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthRequest {
    /// List of services to check, empty for all
    #[prost(string, repeated, tag = "1")]
    pub service_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Config update request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigUpdateRequest {
    /// Target service name
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Path to config file
    #[prost(string, tag = "2")]
    pub config_path: ::prost::alloc::string::String,
    /// Config file content (TOML)
    #[prost(bytes = "vec", tag = "3")]
    pub config_content: ::prost::alloc::vec::Vec<u8>,
    /// Only validate, don't apply
    #[prost(bool, tag = "4")]
    pub validate_only: bool,
}
/// Config request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigRequest {
    /// Target service name
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Specific config section (optional)
    #[prost(string, tag = "2")]
    pub config_key: ::prost::alloc::string::String,
}
/// Validate config request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateConfigRequest {
    /// Service to validate config for
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Config content to validate
    #[prost(bytes = "vec", tag = "2")]
    pub config_content: ::prost::alloc::vec::Vec<u8>,
}
/// Metrics request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsRequest {
    /// Services to get metrics from
    #[prost(string, repeated, tag = "1")]
    pub service_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Filter by metric names
    #[prost(string, repeated, tag = "2")]
    pub metric_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Time range for metrics
    #[prost(message, optional, tag = "3")]
    pub time_range: ::core::option::Option<TimeRange>,
}
/// Time range for metrics
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeRange {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<super::common::Timestamp>,
}
/// Dependency graph request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DependencyGraphRequest {
    /// Get dependencies for specific service, empty for full graph
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
}
/// Generic service operation response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Human-readable message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// New service state after operation
    #[prost(enumeration = "super::common::ServiceState", tag = "3")]
    pub new_state: i32,
    /// Process ID (if applicable)
    #[prost(uint32, tag = "4")]
    pub process_id: u32,
}
/// Service status response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceStatusResponse {
    /// Service name
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Current state
    #[prost(enumeration = "super::common::ServiceState", tag = "2")]
    pub state: i32,
    /// Process ID
    #[prost(uint32, tag = "3")]
    pub pid: u32,
    /// Uptime in seconds
    #[prost(uint64, tag = "4")]
    pub uptime_seconds: u64,
    /// Memory usage
    #[prost(uint64, tag = "5")]
    pub memory_bytes: u64,
    /// CPU usage percentage
    #[prost(double, tag = "6")]
    pub cpu_percent: f64,
    /// Service version
    #[prost(string, tag = "7")]
    pub version: ::prost::alloc::string::String,
    /// When service started
    #[prost(message, optional, tag = "8")]
    pub started_at: ::core::option::Option<super::common::Timestamp>,
}
/// Health response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    /// Map of service name to health status
    #[prost(map = "string, message", tag = "1")]
    pub services: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::common::HealthStatus,
    >,
    /// When health was checked
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
/// Config update response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigUpdateResponse {
    /// Update status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Validation errors
    #[prost(string, repeated, tag = "2")]
    pub validation_errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Whether restart is needed
    #[prost(bool, tag = "3")]
    pub requires_restart: bool,
}
/// Config response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigResponse {
    /// Config as TOML string
    #[prost(string, tag = "1")]
    pub config_content: ::prost::alloc::string::String,
    /// Last modification time
    #[prost(message, optional, tag = "2")]
    pub last_updated: ::core::option::Option<super::common::Timestamp>,
}
/// Validate config response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateConfigResponse {
    /// Whether config is valid
    #[prost(bool, tag = "1")]
    pub is_valid: bool,
    /// Validation errors
    #[prost(string, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Validation warnings
    #[prost(string, repeated, tag = "3")]
    pub warnings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Metrics response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricsResponse {
    /// Map of service name to metrics
    #[prost(map = "string, message", tag = "1")]
    pub services: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ServiceMetrics,
    >,
    /// When metrics were collected
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
/// Dependency graph response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DependencyGraphResponse {
    /// List of service nodes
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<DependencyNode>,
    /// List of dependency edges
    #[prost(message, repeated, tag = "2")]
    pub edges: ::prost::alloc::vec::Vec<DependencyEdge>,
}
/// Service metrics
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceMetrics {
    /// Counter metrics (monotonically increasing)
    #[prost(map = "string, double", tag = "1")]
    pub counters: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
    /// Gauge metrics (can go up/down)
    #[prost(map = "string, double", tag = "2")]
    pub gauges: ::std::collections::HashMap<::prost::alloc::string::String, f64>,
    /// Histogram metrics
    #[prost(map = "string, message", tag = "3")]
    pub histograms: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        Histogram,
    >,
    /// Metric labels
    #[prost(map = "string, string", tag = "4")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Histogram metric
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Histogram {
    /// Bucket boundaries
    #[prost(double, repeated, tag = "1")]
    pub buckets: ::prost::alloc::vec::Vec<f64>,
    /// Count per bucket
    #[prost(uint64, repeated, tag = "2")]
    pub counts: ::prost::alloc::vec::Vec<u64>,
    /// Sum of all observations
    #[prost(double, tag = "3")]
    pub sum: f64,
    /// Total number of observations
    #[prost(uint64, tag = "4")]
    pub total_count: u64,
}
/// Dependency graph node
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DependencyNode {
    /// Service name
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// Current service state
    #[prost(enumeration = "super::common::ServiceState", tag = "2")]
    pub state: i32,
    /// List of services this depends on
    #[prost(string, repeated, tag = "3")]
    pub dependencies: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Dependency graph edge
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DependencyEdge {
    /// Service that has the dependency
    #[prost(string, tag = "1")]
    pub from_service: ::prost::alloc::string::String,
    /// Service that is depended on
    #[prost(string, tag = "2")]
    pub to_service: ::prost::alloc::string::String,
    /// Type of dependency
    #[prost(enumeration = "DependencyType", tag = "3")]
    pub dependency_type: i32,
}
/// Dependency type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DependencyType {
    DependencyUnknown = 0,
    /// Must be running
    DependencyRequired = 1,
    /// Nice to have, but not required
    DependencyOptional = 2,
}
impl DependencyType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DependencyType::DependencyUnknown => "DEPENDENCY_UNKNOWN",
            DependencyType::DependencyRequired => "DEPENDENCY_REQUIRED",
            DependencyType::DependencyOptional => "DEPENDENCY_OPTIONAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DEPENDENCY_UNKNOWN" => Some(Self::DependencyUnknown),
            "DEPENDENCY_REQUIRED" => Some(Self::DependencyRequired),
            "DEPENDENCY_OPTIONAL" => Some(Self::DependencyOptional),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod orchestrator_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Orchestrator Service - Central coordination service for all SafeOps microservices
    #[derive(Debug, Clone)]
    pub struct OrchestratorServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl OrchestratorServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> OrchestratorServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> OrchestratorServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            OrchestratorServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Service Lifecycle Methods
        pub async fn start_service(
            &mut self,
            request: impl tonic::IntoRequest<super::StartServiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/StartService",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "StartService",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn stop_service(
            &mut self,
            request: impl tonic::IntoRequest<super::StopServiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/StopService",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "StopService",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn restart_service(
            &mut self,
            request: impl tonic::IntoRequest<super::RestartServiceRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/RestartService",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "RestartService",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_service_status(
            &mut self,
            request: impl tonic::IntoRequest<super::ServiceStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServiceStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/GetServiceStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "GetServiceStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Health Monitoring Methods
        pub async fn get_health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/GetHealth",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "GetHealth",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn stream_health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::HealthResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/StreamHealth",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "StreamHealth",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Configuration Methods
        pub async fn update_config(
            &mut self,
            request: impl tonic::IntoRequest<super::ConfigUpdateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ConfigUpdateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/UpdateConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "UpdateConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_config(
            &mut self,
            request: impl tonic::IntoRequest<super::ConfigRequest>,
        ) -> std::result::Result<tonic::Response<super::ConfigResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/GetConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "GetConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_config(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/ValidateConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "ValidateConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn reload_config(
            &mut self,
            request: impl tonic::IntoRequest<super::ConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/ReloadConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "ReloadConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Metrics Methods
        pub async fn get_metrics(
            &mut self,
            request: impl tonic::IntoRequest<super::MetricsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MetricsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/GetMetrics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "GetMetrics",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn stream_metrics(
            &mut self,
            request: impl tonic::IntoRequest<super::MetricsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::MetricsResponse>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/StreamMetrics",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "StreamMetrics",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Dependency Management
        pub async fn get_dependency_graph(
            &mut self,
            request: impl tonic::IntoRequest<super::DependencyGraphRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DependencyGraphResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/GetDependencyGraph",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "GetDependencyGraph",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn check_dependencies(
            &mut self,
            request: impl tonic::IntoRequest<super::DependencyGraphRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ServiceResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.orchestrator.OrchestratorService/CheckDependencies",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.orchestrator.OrchestratorService",
                        "CheckDependencies",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
