// This file is @generated by prost-build.
/// Log packet request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogPacketRequest {
    /// Packet timestamp
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Source IP
    #[prost(message, optional, tag = "2")]
    pub source_ip: ::core::option::Option<super::common::IpAddress>,
    /// Destination IP
    #[prost(message, optional, tag = "3")]
    pub dest_ip: ::core::option::Option<super::common::IpAddress>,
    /// Source port
    #[prost(uint32, tag = "4")]
    pub source_port: u32,
    /// Destination port
    #[prost(uint32, tag = "5")]
    pub dest_port: u32,
    /// Protocol
    #[prost(enumeration = "super::common::Protocol", tag = "6")]
    pub protocol: i32,
    /// Packet size in bytes
    #[prost(uint32, tag = "7")]
    pub packet_size: u32,
    /// TCP flags
    #[prost(string, tag = "8")]
    pub flags: ::prost::alloc::string::String,
    /// SHA256 hash of payload
    #[prost(string, tag = "9")]
    pub payload_hash: ::prost::alloc::string::String,
    /// Network interface
    #[prost(string, tag = "10")]
    pub interface_name: ::prost::alloc::string::String,
}
/// Log connection request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogConnectionRequest {
    /// Unique connection ID
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    /// Connection start
    #[prost(message, optional, tag = "2")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// Connection end
    #[prost(message, optional, tag = "3")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
    /// Source IP
    #[prost(message, optional, tag = "4")]
    pub source_ip: ::core::option::Option<super::common::IpAddress>,
    /// Destination IP
    #[prost(message, optional, tag = "5")]
    pub dest_ip: ::core::option::Option<super::common::IpAddress>,
    /// Source port
    #[prost(uint32, tag = "6")]
    pub source_port: u32,
    /// Destination port
    #[prost(uint32, tag = "7")]
    pub dest_port: u32,
    /// Protocol
    #[prost(enumeration = "super::common::Protocol", tag = "8")]
    pub protocol: i32,
    /// Bytes sent
    #[prost(uint64, tag = "9")]
    pub bytes_sent: u64,
    /// Bytes received
    #[prost(uint64, tag = "10")]
    pub bytes_received: u64,
    /// Packets sent
    #[prost(uint64, tag = "11")]
    pub packets_sent: u64,
    /// Packets received
    #[prost(uint64, tag = "12")]
    pub packets_received: u64,
    /// Why connection ended
    #[prost(string, tag = "13")]
    pub termination_reason: ::prost::alloc::string::String,
}
/// Log DNS query request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogDnsQueryRequest {
    /// Query timestamp
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Client IP
    #[prost(message, optional, tag = "2")]
    pub client_ip: ::core::option::Option<super::common::IpAddress>,
    /// Queried domain
    #[prost(string, tag = "3")]
    pub query_domain: ::prost::alloc::string::String,
    /// DNS query type (A/AAAA/MX)
    #[prost(string, tag = "4")]
    pub query_type: ::prost::alloc::string::String,
    /// DNS response code
    #[prost(uint32, tag = "5")]
    pub response_code: u32,
    /// Resolved IP addresses
    #[prost(string, repeated, tag = "6")]
    pub response_ips: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Response time in ms
    #[prost(uint32, tag = "7")]
    pub response_time_ms: u32,
}
/// Log HTTP request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogHttpRequestRequest {
    /// Request timestamp
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Client IP
    #[prost(message, optional, tag = "2")]
    pub client_ip: ::core::option::Option<super::common::IpAddress>,
    /// HTTP method (GET/POST)
    #[prost(string, tag = "3")]
    pub method: ::prost::alloc::string::String,
    /// Host header
    #[prost(string, tag = "4")]
    pub host: ::prost::alloc::string::String,
    /// Request path
    #[prost(string, tag = "5")]
    pub path: ::prost::alloc::string::String,
    /// User-Agent header
    #[prost(string, tag = "6")]
    pub user_agent: ::prost::alloc::string::String,
    /// HTTP status code
    #[prost(uint32, tag = "7")]
    pub status_code: u32,
    /// Bytes transferred
    #[prost(uint64, tag = "8")]
    pub bytes_transferred: u64,
    /// Request duration in ms
    #[prost(uint32, tag = "9")]
    pub duration_ms: u32,
}
/// Bulk log request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BulkLogRequest {
    /// Log entries (up to 10,000)
    #[prost(message, repeated, tag = "1")]
    pub log_entries: ::prost::alloc::vec::Vec<LogEntry>,
    /// Batch identifier
    #[prost(string, tag = "2")]
    pub batch_id: ::prost::alloc::string::String,
}
/// Query logs request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryLogsRequest {
    /// Start of time range
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// End of time range
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
    /// Filter by source IP
    #[prost(message, optional, tag = "3")]
    pub source_ip: ::core::option::Option<super::common::IpAddress>,
    /// Filter by destination IP
    #[prost(message, optional, tag = "4")]
    pub dest_ip: ::core::option::Option<super::common::IpAddress>,
    /// Filter by protocol
    #[prost(enumeration = "super::common::Protocol", tag = "5")]
    pub protocol: i32,
    /// Filter by port
    #[prost(uint32, tag = "6")]
    pub port: u32,
    /// Filter by log type
    #[prost(enumeration = "LogType", tag = "7")]
    pub log_type: i32,
    /// Max results
    #[prost(uint32, tag = "8")]
    pub limit: u32,
    /// Pagination offset
    #[prost(uint32, tag = "9")]
    pub offset: u32,
}
/// Search logs request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchLogsRequest {
    /// Search term
    #[prost(string, tag = "1")]
    pub search_term: ::prost::alloc::string::String,
    /// Fields (IP/DOMAIN/PORT)
    #[prost(string, repeated, tag = "2")]
    pub fields_to_search: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Start of time range
    #[prost(message, optional, tag = "3")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// End of time range
    #[prost(message, optional, tag = "4")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
    /// Pagination
    #[prost(message, optional, tag = "5")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Get logs by connection request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogsByConnectionRequest {
    /// Connection ID
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
/// Get logs by IP request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogsByIpRequest {
    /// IP address to query
    #[prost(message, optional, tag = "1")]
    pub ip_address: ::core::option::Option<super::common::IpAddress>,
    /// Direction filter
    #[prost(enumeration = "TrafficDirection", tag = "2")]
    pub direction: i32,
    /// Start of time range
    #[prost(message, optional, tag = "3")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// End of time range
    #[prost(message, optional, tag = "4")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
    /// Pagination
    #[prost(message, optional, tag = "5")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Stream logs request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamLogsRequest {
    /// Filter by log type
    #[prost(enumeration = "LogType", tag = "1")]
    pub log_type: i32,
    /// Minimum severity
    #[prost(enumeration = "LogSeverity", tag = "2")]
    pub min_severity: i32,
    /// Optional IP filter
    #[prost(message, optional, tag = "3")]
    pub ip_filter: ::core::option::Option<super::common::IpAddress>,
}
/// Tail logs request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TailLogsRequest {
    /// Number of recent lines
    #[prost(uint32, tag = "1")]
    pub tail_lines: u32,
    /// Follow like tail -f
    #[prost(bool, tag = "2")]
    pub follow: bool,
    /// Filter by log type
    #[prost(enumeration = "LogType", tag = "3")]
    pub log_type: i32,
}
/// Retention policy request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetentionPolicyRequest {
    /// Log type
    #[prost(enumeration = "LogType", tag = "1")]
    pub log_type: i32,
    /// Days to retain
    #[prost(uint32, tag = "2")]
    pub retention_days: u32,
    /// Enable compression
    #[prost(bool, tag = "3")]
    pub compression_enabled: bool,
    /// Days before archiving
    #[prost(uint32, tag = "4")]
    pub archive_after_days: u32,
    /// Compression algorithm
    #[prost(enumeration = "CompressionAlgorithm", tag = "5")]
    pub compression_algo: i32,
    /// Archive path/URL
    #[prost(string, tag = "6")]
    pub archive_location: ::prost::alloc::string::String,
}
/// Get retention policy request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRetentionPolicyRequest {
    /// Log type to query
    #[prost(enumeration = "LogType", tag = "1")]
    pub log_type: i32,
}
/// Purge logs request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PurgeLogsRequest {
    /// Purge logs older than this
    #[prost(uint32, tag = "1")]
    pub older_than_days: u32,
    /// Log types to purge
    #[prost(enumeration = "LogType", repeated, tag = "2")]
    pub log_types: ::prost::alloc::vec::Vec<i32>,
    /// Dry run mode
    #[prost(bool, tag = "3")]
    pub dry_run: bool,
}
/// Log stats request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogStatsRequest {
    /// Start time
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// End time
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
}
/// Storage stats request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageStatsRequest {}
/// Export logs request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExportLogsRequest {
    /// Start of time range
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// End of time range
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
    /// Export format
    #[prost(enumeration = "ExportFormat", tag = "3")]
    pub format: i32,
    /// Filter by log type
    #[prost(enumeration = "LogType", tag = "4")]
    pub log_type: i32,
    /// Optional IP filter
    #[prost(message, optional, tag = "5")]
    pub ip_filter: ::core::option::Option<super::common::IpAddress>,
    /// FILE/S3/FTP destination
    #[prost(string, tag = "6")]
    pub destination: ::prost::alloc::string::String,
    /// Compress export
    #[prost(bool, tag = "7")]
    pub compress: bool,
}
/// Schedule export request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleExportRequest {
    /// Cron expression
    #[prost(string, tag = "1")]
    pub schedule_cron: ::prost::alloc::string::String,
    /// Export configuration
    #[prost(message, optional, tag = "2")]
    pub export_config: ::core::option::Option<ExportLogsRequest>,
    /// Enable schedule
    #[prost(bool, tag = "3")]
    pub enabled: bool,
}
/// Log response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogResponse {
    /// Generated log ID
    #[prost(string, tag = "1")]
    pub log_id: ::prost::alloc::string::String,
    /// Ingestion status
    #[prost(enumeration = "super::common::Status", tag = "2")]
    pub status: i32,
    /// When log was ingested
    #[prost(message, optional, tag = "3")]
    pub ingestion_time: ::core::option::Option<super::common::Timestamp>,
}
/// Bulk log response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BulkLogResponse {
    /// Successfully ingested
    #[prost(uint32, tag = "1")]
    pub successful_count: u32,
    /// Failed to ingest
    #[prost(uint32, tag = "2")]
    pub failed_count: u32,
    /// IDs of failed logs
    #[prost(string, repeated, tag = "3")]
    pub failed_log_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Overall status
    #[prost(enumeration = "super::common::Status", tag = "4")]
    pub status: i32,
}
/// Log query response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogQueryResponse {
    /// Log entries
    #[prost(message, repeated, tag = "1")]
    pub log_entries: ::prost::alloc::vec::Vec<LogEntry>,
    /// Total matching logs
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
    /// Pagination info
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Log stats response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogStatsResponse {
    /// Total log count
    #[prost(uint64, tag = "1")]
    pub total_logs: u64,
    /// Breakdown by protocol
    #[prost(map = "string, uint64", tag = "2")]
    pub logs_by_protocol: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u64,
    >,
    /// Breakdown by service
    #[prost(map = "string, uint64", tag = "3")]
    pub logs_by_service: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u64,
    >,
    /// Storage used
    #[prost(uint64, tag = "4")]
    pub storage_used_bytes: u64,
    /// Oldest log time
    #[prost(message, optional, tag = "5")]
    pub oldest_log_timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Newest log time
    #[prost(message, optional, tag = "6")]
    pub newest_log_timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Breakdown by type
    #[prost(map = "string, uint64", tag = "7")]
    pub logs_by_type: ::std::collections::HashMap<::prost::alloc::string::String, u64>,
}
/// Storage stats response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageStatsResponse {
    /// Total storage
    #[prost(uint64, tag = "1")]
    pub total_storage_bytes: u64,
    /// Available storage
    #[prost(uint64, tag = "2")]
    pub available_storage_bytes: u64,
    /// Compression ratio
    #[prost(double, tag = "3")]
    pub compression_ratio: f64,
    /// Average logs/day
    #[prost(uint64, tag = "4")]
    pub logs_per_day_average: u64,
    /// Storage by log type
    #[prost(map = "string, uint64", tag = "5")]
    pub storage_by_type: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u64,
    >,
}
/// Retention policy response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetentionPolicyResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Retention policy
    #[prost(message, optional, tag = "2")]
    pub policy: ::core::option::Option<RetentionPolicy>,
    /// Status message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Purge logs response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PurgeLogsResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Number of logs purged
    #[prost(uint64, tag = "2")]
    pub logs_purged: u64,
    /// Bytes freed
    #[prost(uint64, tag = "3")]
    pub bytes_freed: u64,
    /// Was this a dry run
    #[prost(bool, tag = "4")]
    pub was_dry_run: bool,
}
/// Export response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExportResponse {
    /// Export job ID
    #[prost(string, tag = "1")]
    pub export_id: ::prost::alloc::string::String,
    /// Export status
    #[prost(enumeration = "super::common::Status", tag = "2")]
    pub status: i32,
    /// Export file path/URL
    #[prost(string, tag = "3")]
    pub file_path: ::prost::alloc::string::String,
    /// Export size
    #[prost(uint64, tag = "4")]
    pub size_bytes: u64,
    /// Export format
    #[prost(enumeration = "ExportFormat", tag = "5")]
    pub format: i32,
    /// When export created
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
}
/// Log entry
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntry {
    /// Unique log ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Log timestamp
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Type of log
    #[prost(enumeration = "LogType", tag = "3")]
    pub log_type: i32,
    /// Source IP
    #[prost(message, optional, tag = "4")]
    pub source_ip: ::core::option::Option<super::common::IpAddress>,
    /// Destination IP
    #[prost(message, optional, tag = "5")]
    pub dest_ip: ::core::option::Option<super::common::IpAddress>,
    /// Source port
    #[prost(uint32, tag = "6")]
    pub source_port: u32,
    /// Destination port
    #[prost(uint32, tag = "7")]
    pub dest_port: u32,
    /// Network protocol
    #[prost(enumeration = "super::common::Protocol", tag = "8")]
    pub protocol: i32,
    /// Event data (JSON)
    #[prost(string, tag = "9")]
    pub event_data: ::prost::alloc::string::String,
    /// Log severity
    #[prost(enumeration = "LogSeverity", tag = "10")]
    pub severity: i32,
    /// Originating service
    #[prost(string, tag = "11")]
    pub service_name: ::prost::alloc::string::String,
    /// When log was indexed
    #[prost(message, optional, tag = "12")]
    pub indexed_at: ::core::option::Option<super::common::Timestamp>,
}
/// Retention policy
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetentionPolicy {
    /// Log type
    #[prost(enumeration = "LogType", tag = "1")]
    pub log_type: i32,
    /// Retention period
    #[prost(uint32, tag = "2")]
    pub retention_days: u32,
    /// Compression enabled
    #[prost(bool, tag = "3")]
    pub compression_enabled: bool,
    /// Compression algorithm
    #[prost(enumeration = "CompressionAlgorithm", tag = "4")]
    pub compression_algorithm: i32,
    /// Archive location
    #[prost(string, tag = "5")]
    pub archive_location: ::prost::alloc::string::String,
    /// Auto-purge enabled
    #[prost(bool, tag = "6")]
    pub auto_purge_enabled: bool,
    /// Days before archiving
    #[prost(uint32, tag = "7")]
    pub archive_after_days: u32,
}
/// Log type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogType {
    Unknown = 0,
    Packet = 1,
    Connection = 2,
    DnsQuery = 3,
    HttpRequest = 4,
    FirewallEvent = 5,
    IdsAlert = 6,
    DhcpLease = 7,
    TlsHandshake = 8,
    WifiEvent = 9,
}
impl LogType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LogType::Unknown => "LOG_TYPE_UNKNOWN",
            LogType::Packet => "LOG_TYPE_PACKET",
            LogType::Connection => "LOG_TYPE_CONNECTION",
            LogType::DnsQuery => "LOG_TYPE_DNS_QUERY",
            LogType::HttpRequest => "LOG_TYPE_HTTP_REQUEST",
            LogType::FirewallEvent => "LOG_TYPE_FIREWALL_EVENT",
            LogType::IdsAlert => "LOG_TYPE_IDS_ALERT",
            LogType::DhcpLease => "LOG_TYPE_DHCP_LEASE",
            LogType::TlsHandshake => "LOG_TYPE_TLS_HANDSHAKE",
            LogType::WifiEvent => "LOG_TYPE_WIFI_EVENT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LOG_TYPE_UNKNOWN" => Some(Self::Unknown),
            "LOG_TYPE_PACKET" => Some(Self::Packet),
            "LOG_TYPE_CONNECTION" => Some(Self::Connection),
            "LOG_TYPE_DNS_QUERY" => Some(Self::DnsQuery),
            "LOG_TYPE_HTTP_REQUEST" => Some(Self::HttpRequest),
            "LOG_TYPE_FIREWALL_EVENT" => Some(Self::FirewallEvent),
            "LOG_TYPE_IDS_ALERT" => Some(Self::IdsAlert),
            "LOG_TYPE_DHCP_LEASE" => Some(Self::DhcpLease),
            "LOG_TYPE_TLS_HANDSHAKE" => Some(Self::TlsHandshake),
            "LOG_TYPE_WIFI_EVENT" => Some(Self::WifiEvent),
            _ => None,
        }
    }
}
/// Export format
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExportFormat {
    Unknown = 0,
    Pcap = 1,
    Json = 2,
    Csv = 3,
    Syslog = 4,
    Cef = 5,
}
impl ExportFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ExportFormat::Unknown => "EXPORT_FORMAT_UNKNOWN",
            ExportFormat::Pcap => "EXPORT_FORMAT_PCAP",
            ExportFormat::Json => "EXPORT_FORMAT_JSON",
            ExportFormat::Csv => "EXPORT_FORMAT_CSV",
            ExportFormat::Syslog => "EXPORT_FORMAT_SYSLOG",
            ExportFormat::Cef => "EXPORT_FORMAT_CEF",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EXPORT_FORMAT_UNKNOWN" => Some(Self::Unknown),
            "EXPORT_FORMAT_PCAP" => Some(Self::Pcap),
            "EXPORT_FORMAT_JSON" => Some(Self::Json),
            "EXPORT_FORMAT_CSV" => Some(Self::Csv),
            "EXPORT_FORMAT_SYSLOG" => Some(Self::Syslog),
            "EXPORT_FORMAT_CEF" => Some(Self::Cef),
            _ => None,
        }
    }
}
/// Compression algorithm
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompressionAlgorithm {
    CompressionNone = 0,
    CompressionGzip = 1,
    CompressionZstd = 2,
    CompressionLz4 = 3,
}
impl CompressionAlgorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CompressionAlgorithm::CompressionNone => "COMPRESSION_NONE",
            CompressionAlgorithm::CompressionGzip => "COMPRESSION_GZIP",
            CompressionAlgorithm::CompressionZstd => "COMPRESSION_ZSTD",
            CompressionAlgorithm::CompressionLz4 => "COMPRESSION_LZ4",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPRESSION_NONE" => Some(Self::CompressionNone),
            "COMPRESSION_GZIP" => Some(Self::CompressionGzip),
            "COMPRESSION_ZSTD" => Some(Self::CompressionZstd),
            "COMPRESSION_LZ4" => Some(Self::CompressionLz4),
            _ => None,
        }
    }
}
/// Traffic direction
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TrafficDirection {
    DirectionUnknown = 0,
    DirectionSource = 1,
    DirectionDest = 2,
    DirectionBoth = 3,
}
impl TrafficDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TrafficDirection::DirectionUnknown => "DIRECTION_UNKNOWN",
            TrafficDirection::DirectionSource => "DIRECTION_SOURCE",
            TrafficDirection::DirectionDest => "DIRECTION_DEST",
            TrafficDirection::DirectionBoth => "DIRECTION_BOTH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIRECTION_UNKNOWN" => Some(Self::DirectionUnknown),
            "DIRECTION_SOURCE" => Some(Self::DirectionSource),
            "DIRECTION_DEST" => Some(Self::DirectionDest),
            "DIRECTION_BOTH" => Some(Self::DirectionBoth),
            _ => None,
        }
    }
}
/// Log severity
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LogSeverity {
    SeverityUnknown = 0,
    SeverityInfo = 1,
    SeverityWarning = 2,
    SeverityError = 3,
    SeverityCritical = 4,
}
impl LogSeverity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            LogSeverity::SeverityUnknown => "SEVERITY_UNKNOWN",
            LogSeverity::SeverityInfo => "SEVERITY_INFO",
            LogSeverity::SeverityWarning => "SEVERITY_WARNING",
            LogSeverity::SeverityError => "SEVERITY_ERROR",
            LogSeverity::SeverityCritical => "SEVERITY_CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNKNOWN" => Some(Self::SeverityUnknown),
            "SEVERITY_INFO" => Some(Self::SeverityInfo),
            "SEVERITY_WARNING" => Some(Self::SeverityWarning),
            "SEVERITY_ERROR" => Some(Self::SeverityError),
            "SEVERITY_CRITICAL" => Some(Self::SeverityCritical),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod network_logger_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Network Logger Service - Centralized logging sink for all network events
    #[derive(Debug, Clone)]
    pub struct NetworkLoggerServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl NetworkLoggerServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> NetworkLoggerServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> NetworkLoggerServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            NetworkLoggerServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Logging Methods
        pub async fn log_packet(
            &mut self,
            request: impl tonic::IntoRequest<super::LogPacketRequest>,
        ) -> std::result::Result<tonic::Response<super::LogResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/LogPacket",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "LogPacket",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn log_connection(
            &mut self,
            request: impl tonic::IntoRequest<super::LogConnectionRequest>,
        ) -> std::result::Result<tonic::Response<super::LogResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/LogConnection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "LogConnection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn log_dns_query(
            &mut self,
            request: impl tonic::IntoRequest<super::LogDnsQueryRequest>,
        ) -> std::result::Result<tonic::Response<super::LogResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/LogDNSQuery",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "LogDNSQuery",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn log_http_request(
            &mut self,
            request: impl tonic::IntoRequest<super::LogHttpRequestRequest>,
        ) -> std::result::Result<tonic::Response<super::LogResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/LogHTTPRequest",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "LogHTTPRequest",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn bulk_log(
            &mut self,
            request: impl tonic::IntoRequest<super::BulkLogRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BulkLogResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/BulkLog",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "BulkLog",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Query Methods
        pub async fn query_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::QueryLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogQueryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/QueryLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "QueryLogs",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn search_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogQueryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/SearchLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "SearchLogs",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_logs_by_connection(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLogsByConnectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogQueryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/GetLogsByConnection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "GetLogsByConnection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_logs_by_ip(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLogsByIpRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogQueryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/GetLogsByIP",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "GetLogsByIP",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Stream Methods
        pub async fn stream_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::LogEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/StreamLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "StreamLogs",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn tail_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::TailLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::LogEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/TailLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "TailLogs",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Retention Methods
        pub async fn set_retention_policy(
            &mut self,
            request: impl tonic::IntoRequest<super::RetentionPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetentionPolicyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/SetRetentionPolicy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "SetRetentionPolicy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_retention_policy(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRetentionPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetentionPolicyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/GetRetentionPolicy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "GetRetentionPolicy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn purge_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::PurgeLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PurgeLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/PurgeLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "PurgeLogs",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Statistics Methods
        pub async fn get_log_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::LogStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LogStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/GetLogStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "GetLogStats",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_storage_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::StorageStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StorageStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/GetStorageStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "GetStorageStats",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Export Methods
        pub async fn export_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::ExportLogsRequest>,
        ) -> std::result::Result<tonic::Response<super::ExportResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/ExportLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "ExportLogs",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn schedule_export(
            &mut self,
            request: impl tonic::IntoRequest<super::ScheduleExportRequest>,
        ) -> std::result::Result<tonic::Response<super::ExportResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.network_logger.NetworkLoggerService/ScheduleExport",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.network_logger.NetworkLoggerService",
                        "ScheduleExport",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
