// This file is @generated by prost-build.
/// Generate certificate request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateCertificateRequest {
    /// Common name (CN)
    #[prost(string, tag = "1")]
    pub common_name: ::prost::alloc::string::String,
    /// SANs
    #[prost(string, repeated, tag = "2")]
    pub subject_alternative_names: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// Organization (O)
    #[prost(string, tag = "3")]
    pub organization: ::prost::alloc::string::String,
    /// Country (C)
    #[prost(string, tag = "4")]
    pub country: ::prost::alloc::string::String,
    /// Key algorithm
    #[prost(enumeration = "KeyAlgorithm", tag = "5")]
    pub key_algorithm: i32,
    /// Key size (bits)
    #[prost(uint32, tag = "6")]
    pub key_size: u32,
    /// Validity period
    #[prost(uint32, tag = "7")]
    pub validity_days: u32,
}
/// Import certificate request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ImportCertificateRequest {
    /// Certificate (PEM)
    #[prost(bytes = "vec", tag = "1")]
    pub certificate_pem: ::prost::alloc::vec::Vec<u8>,
    /// Private key (PEM)
    #[prost(bytes = "vec", tag = "2")]
    pub private_key_pem: ::prost::alloc::vec::Vec<u8>,
    /// Certificate chain
    #[prost(bytes = "vec", tag = "3")]
    pub certificate_chain: ::prost::alloc::vec::Vec<u8>,
    /// Key passphrase
    #[prost(string, tag = "4")]
    pub passphrase: ::prost::alloc::string::String,
}
/// Renew certificate request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RenewCertificateRequest {
    /// Certificate ID to renew
    #[prost(string, tag = "1")]
    pub certificate_id: ::prost::alloc::string::String,
    /// Renew N days before expiry
    #[prost(uint32, tag = "2")]
    pub renew_before_days: u32,
}
/// Revoke certificate request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeCertificateRequest {
    /// Certificate ID to revoke
    #[prost(string, tag = "1")]
    pub certificate_id: ::prost::alloc::string::String,
    /// Revocation reason
    #[prost(enumeration = "RevocationReason", tag = "2")]
    pub reason: i32,
}
/// Delete certificate request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteCertificateRequest {
    /// Certificate ID to delete
    #[prost(string, tag = "1")]
    pub certificate_id: ::prost::alloc::string::String,
    /// Also delete private key
    #[prost(bool, tag = "2")]
    pub delete_private_key: bool,
}
/// List certificates request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListCertificatesRequest {
    /// Filter by status
    #[prost(enumeration = "CertificateStatus", tag = "1")]
    pub status: i32,
    /// Filter by issuer
    #[prost(string, tag = "2")]
    pub issuer: ::prost::alloc::string::String,
    /// Filter by domain
    #[prost(string, tag = "3")]
    pub domain: ::prost::alloc::string::String,
    /// Pagination
    #[prost(message, optional, tag = "4")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Get certificate details request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCertificateDetailsRequest {
    /// Certificate ID (optional)
    #[prost(string, tag = "1")]
    pub certificate_id: ::prost::alloc::string::String,
    /// Or domain name
    #[prost(string, tag = "2")]
    pub domain_name: ::prost::alloc::string::String,
}
/// ACME config request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcmeConfigRequest {
    /// ACME server URL
    #[prost(string, tag = "1")]
    pub acme_server_url: ::prost::alloc::string::String,
    /// Account email
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    /// DNS provider
    #[prost(enumeration = "DnsProvider", tag = "3")]
    pub dns_provider: i32,
    /// API credentials
    #[prost(string, tag = "4")]
    pub api_credentials: ::prost::alloc::string::String,
    /// Challenge type
    #[prost(enumeration = "ChallengeType", tag = "5")]
    pub challenge_type: i32,
}
/// Request ACME certificate request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestAcmeCertificateRequest {
    /// Domains to certify
    #[prost(string, repeated, tag = "1")]
    pub domains: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Challenge type
    #[prost(enumeration = "ChallengeType", tag = "2")]
    pub challenge_type: i32,
    /// Enable auto-renewal
    #[prost(bool, tag = "3")]
    pub auto_renew: bool,
}
/// Get ACME status request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetAcmeStatusRequest {}
/// Generate CA request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenerateCaRequest {
    /// CA common name
    #[prost(string, tag = "1")]
    pub common_name: ::prost::alloc::string::String,
    /// Organization
    #[prost(string, tag = "2")]
    pub organization: ::prost::alloc::string::String,
    /// Country
    #[prost(string, tag = "3")]
    pub country: ::prost::alloc::string::String,
    /// Validity period (years)
    #[prost(uint32, tag = "4")]
    pub validity_years: u32,
    /// Key algorithm
    #[prost(enumeration = "KeyAlgorithm", tag = "5")]
    pub key_algorithm: i32,
    /// Key size
    #[prost(uint32, tag = "6")]
    pub key_size: u32,
}
/// Sign CSR request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignCsrRequest {
    /// CSR in PEM format
    #[prost(bytes = "vec", tag = "1")]
    pub csr_pem: ::prost::alloc::vec::Vec<u8>,
    /// Validity period
    #[prost(uint32, tag = "2")]
    pub validity_days: u32,
    /// CA to sign with
    #[prost(string, tag = "3")]
    pub ca_id: ::prost::alloc::string::String,
}
/// Get CA chain request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCaChainRequest {
    /// CA ID
    #[prost(string, tag = "1")]
    pub ca_id: ::prost::alloc::string::String,
}
/// Validate certificate request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateCertificateRequest {
    /// Certificate ID (optional)
    #[prost(string, tag = "1")]
    pub certificate_id: ::prost::alloc::string::String,
    /// Or certificate PEM
    #[prost(bytes = "vec", tag = "2")]
    pub certificate_pem: ::prost::alloc::vec::Vec<u8>,
}
/// Check expiration request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CheckExpirationRequest {
    /// Days threshold (default: 30)
    #[prost(uint32, tag = "1")]
    pub days_threshold: u32,
}
/// Verify chain request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyChainRequest {
    /// Certificate ID to verify
    #[prost(string, tag = "1")]
    pub certificate_id: ::prost::alloc::string::String,
}
/// Get certificate stats request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCertificateStatsRequest {}
/// Get expiring certificates request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetExpiringCertificatesRequest {
    /// Days until expiration
    #[prost(uint32, tag = "1")]
    pub days_threshold: u32,
    /// Pagination
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Certificate response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CertificateResponse {
    /// Certificate ID
    #[prost(string, tag = "1")]
    pub certificate_id: ::prost::alloc::string::String,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "2")]
    pub status: i32,
    /// Status message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Certificate list response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CertificateListResponse {
    /// List of certificates
    #[prost(message, repeated, tag = "1")]
    pub certificates: ::prost::alloc::vec::Vec<Certificate>,
    /// Total count
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
    /// Pagination info
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Certificate detail response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CertificateDetailResponse {
    /// Certificate ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Common name
    #[prost(string, tag = "2")]
    pub common_name: ::prost::alloc::string::String,
    /// SAN list
    #[prost(string, repeated, tag = "3")]
    pub san_list: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Issuer
    #[prost(string, tag = "4")]
    pub issuer: ::prost::alloc::string::String,
    /// Subject
    #[prost(string, tag = "5")]
    pub subject: ::prost::alloc::string::String,
    /// Serial number
    #[prost(string, tag = "6")]
    pub serial_number: ::prost::alloc::string::String,
    /// Valid from
    #[prost(message, optional, tag = "7")]
    pub valid_from: ::core::option::Option<super::common::Timestamp>,
    /// Valid until
    #[prost(message, optional, tag = "8")]
    pub valid_until: ::core::option::Option<super::common::Timestamp>,
    /// Key algorithm
    #[prost(enumeration = "KeyAlgorithm", tag = "9")]
    pub key_algorithm: i32,
    /// Signature algorithm
    #[prost(string, tag = "10")]
    pub signature_algorithm: ::prost::alloc::string::String,
    /// SHA256 fingerprint
    #[prost(string, tag = "11")]
    pub fingerprint_sha256: ::prost::alloc::string::String,
    /// Certificate (PEM)
    #[prost(bytes = "vec", tag = "12")]
    pub certificate_pem: ::prost::alloc::vec::Vec<u8>,
    /// Chain (PEM)
    #[prost(bytes = "vec", tag = "13")]
    pub chain_pem: ::prost::alloc::vec::Vec<u8>,
}
/// ACME config response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcmeConfigResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Status message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// ACME status response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcmeStatusResponse {
    /// Is configured
    #[prost(bool, tag = "1")]
    pub configured: bool,
    /// Account email
    #[prost(string, tag = "2")]
    pub account_email: ::prost::alloc::string::String,
    /// ACME server URL
    #[prost(string, tag = "3")]
    pub acme_server: ::prost::alloc::string::String,
    /// Last request time
    #[prost(message, optional, tag = "4")]
    pub last_request_time: ::core::option::Option<super::common::Timestamp>,
    /// Pending challenges
    #[prost(string, repeated, tag = "5")]
    pub pending_challenges: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// CA response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaResponse {
    /// CA certificate ID
    #[prost(string, tag = "1")]
    pub ca_certificate_id: ::prost::alloc::string::String,
    /// CA certificate (PEM)
    #[prost(bytes = "vec", tag = "2")]
    pub ca_certificate_pem: ::prost::alloc::vec::Vec<u8>,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "3")]
    pub status: i32,
}
/// CA chain response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaChainResponse {
    /// Certificate chain
    #[prost(bytes = "vec", repeated, tag = "1")]
    pub chain_pem: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "2")]
    pub status: i32,
}
/// Validation response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationResponse {
    /// Is valid
    #[prost(bool, tag = "1")]
    pub is_valid: bool,
    /// Validation errors
    #[prost(string, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Validation warnings
    #[prost(string, repeated, tag = "3")]
    pub warnings: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Chain is valid
    #[prost(bool, tag = "4")]
    pub chain_valid: bool,
    /// Not before date
    #[prost(message, optional, tag = "5")]
    pub not_before: ::core::option::Option<super::common::Timestamp>,
    /// Not after date
    #[prost(message, optional, tag = "6")]
    pub not_after: ::core::option::Option<super::common::Timestamp>,
    /// Days until expiration
    #[prost(uint32, tag = "7")]
    pub days_until_expiration: u32,
}
/// Expiration check response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExpirationCheckResponse {
    /// Expiring certificates
    #[prost(message, repeated, tag = "1")]
    pub expiring_certificates: ::prost::alloc::vec::Vec<Certificate>,
    /// Total expiring count
    #[prost(uint32, tag = "2")]
    pub total_expiring: u32,
}
/// Chain validation response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChainValidationResponse {
    /// Is valid
    #[prost(bool, tag = "1")]
    pub is_valid: bool,
    /// Chain issues
    #[prost(string, repeated, tag = "2")]
    pub chain_issues: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Certificate path
    #[prost(string, repeated, tag = "3")]
    pub certificate_path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Certificate statistics response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CertificateStatsResponse {
    /// Total certificates
    #[prost(uint32, tag = "1")]
    pub total_certificates: u32,
    /// Valid certificates
    #[prost(uint32, tag = "2")]
    pub valid_certificates: u32,
    /// Expiring < 30 days
    #[prost(uint32, tag = "3")]
    pub expiring_soon: u32,
    /// Expired certificates
    #[prost(uint32, tag = "4")]
    pub expired_certificates: u32,
    /// Revoked certificates
    #[prost(uint32, tag = "5")]
    pub revoked_certificates: u32,
    /// Stats timestamp
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
/// Expiring certificates response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExpiringCertificatesResponse {
    /// Expiring certificates
    #[prost(message, repeated, tag = "1")]
    pub certificates: ::prost::alloc::vec::Vec<ExpiringCertificate>,
    /// Total count
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
    /// Pagination info
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Expiring certificate entry
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExpiringCertificate {
    /// Certificate ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Domain
    #[prost(string, tag = "2")]
    pub domain: ::prost::alloc::string::String,
    /// Expiration date
    #[prost(message, optional, tag = "3")]
    pub expiration_date: ::core::option::Option<super::common::Timestamp>,
    /// Days remaining
    #[prost(uint32, tag = "4")]
    pub days_remaining: u32,
}
/// Certificate
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Certificate {
    /// Certificate ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Common name
    #[prost(string, tag = "2")]
    pub common_name: ::prost::alloc::string::String,
    /// SANs
    #[prost(string, repeated, tag = "3")]
    pub subject_alternative_names: ::prost::alloc::vec::Vec<
        ::prost::alloc::string::String,
    >,
    /// Issuer
    #[prost(string, tag = "4")]
    pub issuer: ::prost::alloc::string::String,
    /// Subject
    #[prost(string, tag = "5")]
    pub subject: ::prost::alloc::string::String,
    /// Serial number
    #[prost(string, tag = "6")]
    pub serial_number: ::prost::alloc::string::String,
    /// Valid from
    #[prost(message, optional, tag = "7")]
    pub valid_from: ::core::option::Option<super::common::Timestamp>,
    /// Valid until
    #[prost(message, optional, tag = "8")]
    pub valid_until: ::core::option::Option<super::common::Timestamp>,
    /// Certificate status
    #[prost(enumeration = "CertificateStatus", tag = "9")]
    pub status: i32,
    /// Key algorithm
    #[prost(enumeration = "KeyAlgorithm", tag = "10")]
    pub key_algorithm: i32,
    /// Key size (bits)
    #[prost(uint32, tag = "11")]
    pub key_size: u32,
    /// Signature algorithm
    #[prost(string, tag = "12")]
    pub signature_algorithm: ::prost::alloc::string::String,
    /// SHA256 fingerprint
    #[prost(string, tag = "13")]
    pub fingerprint_sha256: ::prost::alloc::string::String,
    /// Auto-renew enabled
    #[prost(bool, tag = "14")]
    pub auto_renew: bool,
    /// Services using this cert
    #[prost(string, repeated, tag = "15")]
    pub used_by_services: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Certificate status
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CertificateStatus {
    StatusUnknown = 0,
    StatusValid = 1,
    StatusExpiring = 2,
    StatusExpired = 3,
    StatusRevoked = 4,
    StatusPendingValidation = 5,
}
impl CertificateStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CertificateStatus::StatusUnknown => "STATUS_UNKNOWN",
            CertificateStatus::StatusValid => "STATUS_VALID",
            CertificateStatus::StatusExpiring => "STATUS_EXPIRING",
            CertificateStatus::StatusExpired => "STATUS_EXPIRED",
            CertificateStatus::StatusRevoked => "STATUS_REVOKED",
            CertificateStatus::StatusPendingValidation => "STATUS_PENDING_VALIDATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNKNOWN" => Some(Self::StatusUnknown),
            "STATUS_VALID" => Some(Self::StatusValid),
            "STATUS_EXPIRING" => Some(Self::StatusExpiring),
            "STATUS_EXPIRED" => Some(Self::StatusExpired),
            "STATUS_REVOKED" => Some(Self::StatusRevoked),
            "STATUS_PENDING_VALIDATION" => Some(Self::StatusPendingValidation),
            _ => None,
        }
    }
}
/// Key algorithm
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum KeyAlgorithm {
    AlgorithmUnknown = 0,
    AlgorithmRsa = 1,
    AlgorithmEcdsa = 2,
    AlgorithmEd25519 = 3,
}
impl KeyAlgorithm {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            KeyAlgorithm::AlgorithmUnknown => "ALGORITHM_UNKNOWN",
            KeyAlgorithm::AlgorithmRsa => "ALGORITHM_RSA",
            KeyAlgorithm::AlgorithmEcdsa => "ALGORITHM_ECDSA",
            KeyAlgorithm::AlgorithmEd25519 => "ALGORITHM_ED25519",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ALGORITHM_UNKNOWN" => Some(Self::AlgorithmUnknown),
            "ALGORITHM_RSA" => Some(Self::AlgorithmRsa),
            "ALGORITHM_ECDSA" => Some(Self::AlgorithmEcdsa),
            "ALGORITHM_ED25519" => Some(Self::AlgorithmEd25519),
            _ => None,
        }
    }
}
/// Revocation reason
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RevocationReason {
    ReasonUnspecified = 0,
    ReasonKeyCompromise = 1,
    ReasonCaCompromise = 2,
    ReasonAffiliationChanged = 3,
    ReasonSuperseded = 4,
    ReasonCessationOfOperation = 5,
    ReasonCertificateHold = 6,
    ReasonRemoveFromCrl = 8,
}
impl RevocationReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RevocationReason::ReasonUnspecified => "REASON_UNSPECIFIED",
            RevocationReason::ReasonKeyCompromise => "REASON_KEY_COMPROMISE",
            RevocationReason::ReasonCaCompromise => "REASON_CA_COMPROMISE",
            RevocationReason::ReasonAffiliationChanged => "REASON_AFFILIATION_CHANGED",
            RevocationReason::ReasonSuperseded => "REASON_SUPERSEDED",
            RevocationReason::ReasonCessationOfOperation => {
                "REASON_CESSATION_OF_OPERATION"
            }
            RevocationReason::ReasonCertificateHold => "REASON_CERTIFICATE_HOLD",
            RevocationReason::ReasonRemoveFromCrl => "REASON_REMOVE_FROM_CRL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REASON_UNSPECIFIED" => Some(Self::ReasonUnspecified),
            "REASON_KEY_COMPROMISE" => Some(Self::ReasonKeyCompromise),
            "REASON_CA_COMPROMISE" => Some(Self::ReasonCaCompromise),
            "REASON_AFFILIATION_CHANGED" => Some(Self::ReasonAffiliationChanged),
            "REASON_SUPERSEDED" => Some(Self::ReasonSuperseded),
            "REASON_CESSATION_OF_OPERATION" => Some(Self::ReasonCessationOfOperation),
            "REASON_CERTIFICATE_HOLD" => Some(Self::ReasonCertificateHold),
            "REASON_REMOVE_FROM_CRL" => Some(Self::ReasonRemoveFromCrl),
            _ => None,
        }
    }
}
/// ACME challenge type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChallengeType {
    ChallengeUnknown = 0,
    ChallengeHttp01 = 1,
    ChallengeDns01 = 2,
    ChallengeTlsAlpn01 = 3,
}
impl ChallengeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ChallengeType::ChallengeUnknown => "CHALLENGE_UNKNOWN",
            ChallengeType::ChallengeHttp01 => "CHALLENGE_HTTP01",
            ChallengeType::ChallengeDns01 => "CHALLENGE_DNS01",
            ChallengeType::ChallengeTlsAlpn01 => "CHALLENGE_TLS_ALPN01",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CHALLENGE_UNKNOWN" => Some(Self::ChallengeUnknown),
            "CHALLENGE_HTTP01" => Some(Self::ChallengeHttp01),
            "CHALLENGE_DNS01" => Some(Self::ChallengeDns01),
            "CHALLENGE_TLS_ALPN01" => Some(Self::ChallengeTlsAlpn01),
            _ => None,
        }
    }
}
/// DNS provider
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DnsProvider {
    Unknown = 0,
    Cloudflare = 1,
    Route53 = 2,
    GoogleCloudDns = 3,
    AzureDns = 4,
    Custom = 5,
}
impl DnsProvider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            DnsProvider::Unknown => "DNS_PROVIDER_UNKNOWN",
            DnsProvider::Cloudflare => "DNS_PROVIDER_CLOUDFLARE",
            DnsProvider::Route53 => "DNS_PROVIDER_ROUTE53",
            DnsProvider::GoogleCloudDns => "DNS_PROVIDER_GOOGLE_CLOUD_DNS",
            DnsProvider::AzureDns => "DNS_PROVIDER_AZURE_DNS",
            DnsProvider::Custom => "DNS_PROVIDER_CUSTOM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DNS_PROVIDER_UNKNOWN" => Some(Self::Unknown),
            "DNS_PROVIDER_CLOUDFLARE" => Some(Self::Cloudflare),
            "DNS_PROVIDER_ROUTE53" => Some(Self::Route53),
            "DNS_PROVIDER_GOOGLE_CLOUD_DNS" => Some(Self::GoogleCloudDns),
            "DNS_PROVIDER_AZURE_DNS" => Some(Self::AzureDns),
            "DNS_PROVIDER_CUSTOM" => Some(Self::Custom),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod certificate_manager_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Certificate Manager Service - SSL/TLS certificate lifecycle management
    #[derive(Debug, Clone)]
    pub struct CertificateManagerServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CertificateManagerServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CertificateManagerServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CertificateManagerServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            CertificateManagerServiceClient::new(
                InterceptedService::new(inner, interceptor),
            )
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Certificate Methods
        pub async fn generate_certificate(
            &mut self,
            request: impl tonic::IntoRequest<super::GenerateCertificateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/GenerateCertificate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "GenerateCertificate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn import_certificate(
            &mut self,
            request: impl tonic::IntoRequest<super::ImportCertificateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/ImportCertificate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "ImportCertificate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn renew_certificate(
            &mut self,
            request: impl tonic::IntoRequest<super::RenewCertificateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/RenewCertificate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "RenewCertificate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn revoke_certificate(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeCertificateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/RevokeCertificate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "RevokeCertificate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_certificate(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteCertificateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/DeleteCertificate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "DeleteCertificate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_certificates(
            &mut self,
            request: impl tonic::IntoRequest<super::ListCertificatesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/ListCertificates",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "ListCertificates",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_certificate_details(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCertificateDetailsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateDetailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/GetCertificateDetails",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "GetCertificateDetails",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// ACME Methods
        pub async fn configure_acme(
            &mut self,
            request: impl tonic::IntoRequest<super::AcmeConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AcmeConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/ConfigureACME",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "ConfigureACME",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn request_acme_certificate(
            &mut self,
            request: impl tonic::IntoRequest<super::RequestAcmeCertificateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/RequestACMECertificate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "RequestACMECertificate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_acme_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetAcmeStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AcmeStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/GetACMEStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "GetACMEStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// CA Methods
        pub async fn generate_ca(
            &mut self,
            request: impl tonic::IntoRequest<super::GenerateCaRequest>,
        ) -> std::result::Result<tonic::Response<super::CaResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/GenerateCA",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "GenerateCA",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn sign_csr(
            &mut self,
            request: impl tonic::IntoRequest<super::SignCsrRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/SignCSR",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "SignCSR",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_ca_chain(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCaChainRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaChainResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/GetCAChain",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "GetCAChain",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Validation Methods
        pub async fn validate_certificate(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateCertificateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/ValidateCertificate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "ValidateCertificate",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn check_expiration(
            &mut self,
            request: impl tonic::IntoRequest<super::CheckExpirationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExpirationCheckResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/CheckExpiration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "CheckExpiration",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn verify_chain(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyChainRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChainValidationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/VerifyChain",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "VerifyChain",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Statistics
        pub async fn get_certificate_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCertificateStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CertificateStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/GetCertificateStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "GetCertificateStats",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_expiring_certificates(
            &mut self,
            request: impl tonic::IntoRequest<super::GetExpiringCertificatesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExpiringCertificatesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.certificate_manager.CertificateManagerService/GetExpiringCertificates",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.certificate_manager.CertificateManagerService",
                        "GetExpiringCertificates",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
