// This file is @generated by prost-build.
/// Create SSID request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateSsidRequest {
    /// SSID name
    #[prost(string, tag = "1")]
    pub ssid_name: ::prost::alloc::string::String,
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "2")]
    pub radio_band: i32,
    /// Security mode
    #[prost(enumeration = "SecurityMode", tag = "3")]
    pub security_mode: i32,
    /// Passphrase (if secured)
    #[prost(string, tag = "4")]
    pub passphrase: ::prost::alloc::string::String,
    /// Hidden SSID
    #[prost(bool, tag = "5")]
    pub hidden: bool,
    /// Max clients
    #[prost(uint32, tag = "6")]
    pub max_clients: u32,
    /// VLAN ID (0 = none)
    #[prost(uint32, tag = "7")]
    pub vlan_id: u32,
    /// Is guest network
    #[prost(bool, tag = "8")]
    pub guest_network: bool,
}
/// Update SSID request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateSsidRequest {
    /// SSID ID to update
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Updated name
    #[prost(string, tag = "2")]
    pub ssid_name: ::prost::alloc::string::String,
    /// Updated security
    #[prost(enumeration = "SecurityMode", tag = "3")]
    pub security_mode: i32,
    /// Updated passphrase
    #[prost(string, tag = "4")]
    pub passphrase: ::prost::alloc::string::String,
    /// Hidden flag
    #[prost(bool, tag = "5")]
    pub hidden: bool,
    /// Updated max clients
    #[prost(uint32, tag = "6")]
    pub max_clients: u32,
}
/// Delete SSID request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteSsidRequest {
    /// SSID ID to delete
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Disconnect clients first
    #[prost(bool, tag = "2")]
    pub disconnect_clients: bool,
}
/// List SSIDs request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListSsiDsRequest {
    /// Filter by band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Only enabled SSIDs
    #[prost(bool, tag = "2")]
    pub enabled_only: bool,
}
/// Enable SSID request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnableSsidRequest {
    /// SSID ID to enable
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
}
/// Disable SSID request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisableSsidRequest {
    /// SSID ID to disable
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
}
/// Get clients request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClientsRequest {
    /// Filter by SSID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Only connected clients
    #[prost(bool, tag = "2")]
    pub connected_only: bool,
    /// Pagination
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Get client details request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClientDetailsRequest {
    /// Client MAC (optional)
    #[prost(message, optional, tag = "1")]
    pub client_mac: ::core::option::Option<super::common::MacAddress>,
    /// Or client IP
    #[prost(message, optional, tag = "2")]
    pub client_ip: ::core::option::Option<super::common::IpAddress>,
}
/// Disconnect client request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisconnectClientRequest {
    /// Client MAC
    #[prost(message, optional, tag = "1")]
    pub client_mac: ::core::option::Option<super::common::MacAddress>,
    /// Disconnect reason code
    #[prost(uint32, tag = "2")]
    pub reason_code: u32,
}
/// Block client request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockClientRequest {
    /// Client MAC to block
    #[prost(message, optional, tag = "1")]
    pub client_mac: ::core::option::Option<super::common::MacAddress>,
    /// Block duration (0 = permanent)
    #[prost(uint32, tag = "2")]
    pub duration_seconds: u32,
    /// Reason for blocking
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
/// Unblock client request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnblockClientRequest {
    /// Client MAC to unblock
    #[prost(message, optional, tag = "1")]
    pub client_mac: ::core::option::Option<super::common::MacAddress>,
}
/// Radio settings request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RadioSettingsRequest {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Channel number
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    /// Channel width
    #[prost(enumeration = "ChannelWidth", tag = "3")]
    pub channel_width: i32,
    /// TX power in dBm
    #[prost(uint32, tag = "4")]
    pub tx_power_dbm: u32,
    /// WiFi standard
    #[prost(enumeration = "WifiStandard", tag = "5")]
    pub mode: i32,
    /// Beacon interval
    #[prost(uint32, tag = "6")]
    pub beacon_interval_ms: u32,
}
/// Get radio settings request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRadioSettingsRequest {
    /// Radio band to query
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
}
/// Set channel request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetChannelRequest {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Channel number
    #[prost(uint32, tag = "2")]
    pub channel_number: u32,
    /// Auto-select best channel
    #[prost(bool, tag = "3")]
    pub auto_select: bool,
}
/// Set TX power request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetTxPowerRequest {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Power in dBm
    #[prost(uint32, tag = "2")]
    pub power_dbm: u32,
    /// Or power percentage
    #[prost(uint32, tag = "3")]
    pub power_percent: u32,
}
/// Security mode request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityModeRequest {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Security mode
    #[prost(enumeration = "SecurityMode", tag = "2")]
    pub mode: i32,
    /// Passphrase
    #[prost(string, tag = "3")]
    pub passphrase: ::prost::alloc::string::String,
    /// Encryption type
    #[prost(enumeration = "EncryptionType", tag = "4")]
    pub encryption: i32,
}
/// Update PSK request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdatePskRequest {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// New passphrase
    #[prost(string, tag = "2")]
    pub new_passphrase: ::prost::alloc::string::String,
}
/// Enable WPS request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnableWpsRequest {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// WPS PIN (optional)
    #[prost(string, tag = "2")]
    pub pin: ::prost::alloc::string::String,
}
/// Disable WPS request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisableWpsRequest {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
}
/// Get WPS status request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetWpsStatusRequest {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
}
/// Get AP stats request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetApStatsRequest {
    /// Start time
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// End time
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
}
/// Get client stats request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClientStatsRequest {
    /// Client MAC
    #[prost(message, optional, tag = "1")]
    pub client_mac: ::core::option::Option<super::common::MacAddress>,
}
/// Get radio stats request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRadioStatsRequest {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
}
/// Stream client events request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamClientEventsRequest {
    /// Filter by SSID (optional)
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
}
/// Create guest network request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGuestNetworkRequest {
    /// Guest SSID name
    #[prost(string, tag = "1")]
    pub ssid_name: ::prost::alloc::string::String,
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "2")]
    pub radio_band: i32,
    /// Guest passphrase (optional)
    #[prost(string, tag = "3")]
    pub passphrase: ::prost::alloc::string::String,
    /// Session timeout
    #[prost(uint32, tag = "4")]
    pub session_timeout_minutes: u32,
    /// Enable captive portal
    #[prost(bool, tag = "5")]
    pub captive_portal_enabled: bool,
}
/// Captive portal request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptivePortalRequest {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Enable portal
    #[prost(bool, tag = "2")]
    pub enabled: bool,
    /// Redirect URL
    #[prost(string, tag = "3")]
    pub redirect_url: ::prost::alloc::string::String,
    /// Auth method
    #[prost(enumeration = "CaptivePortalAuth", tag = "4")]
    pub authentication_method: i32,
    /// Session timeout
    #[prost(uint32, tag = "5")]
    pub session_timeout_minutes: u32,
}
/// Get guest clients request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGuestClientsRequest {
    /// Guest SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Only authorized clients
    #[prost(bool, tag = "2")]
    pub authorized_only: bool,
}
/// SSID response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsidResponse {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "2")]
    pub status: i32,
    /// Status message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// SSID list response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SsidListResponse {
    /// List of SSIDs
    #[prost(message, repeated, tag = "1")]
    pub ssids: ::prost::alloc::vec::Vec<Ssid>,
    /// Total count
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
}
/// Client list response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientListResponse {
    /// List of clients
    #[prost(message, repeated, tag = "1")]
    pub clients: ::prost::alloc::vec::Vec<Client>,
    /// Total count
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
    /// Pagination info
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Client detail response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientDetailResponse {
    /// Client details
    #[prost(message, optional, tag = "1")]
    pub client: ::core::option::Option<Client>,
    /// Signal strength
    #[prost(int32, tag = "2")]
    pub signal_strength_dbm: i32,
    /// TX rate
    #[prost(double, tag = "3")]
    pub tx_rate_mbps: f64,
    /// RX rate
    #[prost(double, tag = "4")]
    pub rx_rate_mbps: f64,
    /// Connection time
    #[prost(message, optional, tag = "5")]
    pub connected_time: ::core::option::Option<super::common::Timestamp>,
    /// Data usage
    #[prost(uint64, tag = "6")]
    pub data_usage_bytes: u64,
}
/// Client action response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientActionResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Status message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Radio settings response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RadioSettingsResponse {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Current channel
    #[prost(uint32, tag = "2")]
    pub current_channel: u32,
    /// Channel width
    #[prost(enumeration = "ChannelWidth", tag = "3")]
    pub channel_width: i32,
    /// TX power
    #[prost(uint32, tag = "4")]
    pub tx_power_dbm: u32,
    /// WiFi standard
    #[prost(enumeration = "WifiStandard", tag = "5")]
    pub mode: i32,
    /// Beacon interval
    #[prost(uint32, tag = "6")]
    pub beacon_interval_ms: u32,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "7")]
    pub status: i32,
}
/// Channel response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChannelResponse {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Selected channel
    #[prost(uint32, tag = "2")]
    pub channel: u32,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "3")]
    pub status: i32,
}
/// TX power response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TxPowerResponse {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Power in dBm
    #[prost(uint32, tag = "2")]
    pub power_dbm: u32,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "3")]
    pub status: i32,
}
/// Security mode response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SecurityModeResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Status message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// WPS status response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WpsStatusResponse {
    /// WPS enabled
    #[prost(bool, tag = "1")]
    pub enabled: bool,
    /// WPS PIN
    #[prost(string, tag = "2")]
    pub pin: ::prost::alloc::string::String,
    /// Last attempt
    #[prost(message, optional, tag = "3")]
    pub last_connection_attempt: ::core::option::Option<super::common::Timestamp>,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "4")]
    pub status: i32,
}
/// AP statistics response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ApStatsResponse {
    /// Total clients
    #[prost(uint32, tag = "1")]
    pub total_clients: u32,
    /// Clients per SSID
    #[prost(map = "string, uint32", tag = "2")]
    pub clients_by_ssid: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u32,
    >,
    /// Clients per band
    #[prost(map = "string, uint32", tag = "3")]
    pub clients_by_band: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u32,
    >,
    /// Total data
    #[prost(uint64, tag = "4")]
    pub total_data_transferred: u64,
    /// Uptime
    #[prost(uint64, tag = "5")]
    pub uptime_seconds: u64,
    /// Stats timestamp
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
/// Client statistics response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientStatsResponse {
    /// Client MAC
    #[prost(message, optional, tag = "1")]
    pub client_mac: ::core::option::Option<super::common::MacAddress>,
    /// Signal strength
    #[prost(int32, tag = "2")]
    pub signal_strength_dbm: i32,
    /// TX rate
    #[prost(double, tag = "3")]
    pub tx_rate_mbps: f64,
    /// RX rate
    #[prost(double, tag = "4")]
    pub rx_rate_mbps: f64,
    /// Packets sent
    #[prost(uint64, tag = "5")]
    pub packets_sent: u64,
    /// Packets received
    #[prost(uint64, tag = "6")]
    pub packets_received: u64,
    /// Bytes sent
    #[prost(uint64, tag = "7")]
    pub bytes_sent: u64,
    /// Bytes received
    #[prost(uint64, tag = "8")]
    pub bytes_received: u64,
    /// Retry count
    #[prost(uint32, tag = "9")]
    pub retries: u32,
    /// Roam count
    #[prost(uint32, tag = "10")]
    pub roam_count: u32,
}
/// Radio statistics response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RadioStatsResponse {
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "1")]
    pub radio_band: i32,
    /// Current channel
    #[prost(uint32, tag = "2")]
    pub current_channel: u32,
    /// Channel utilization
    #[prost(double, tag = "3")]
    pub channel_utilization_percent: f64,
    /// Noise floor
    #[prost(int32, tag = "4")]
    pub noise_floor_dbm: i32,
    /// Interference flag
    #[prost(bool, tag = "5")]
    pub interference_detected: bool,
    /// Stats timestamp
    #[prost(message, optional, tag = "6")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
/// Captive portal response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CaptivePortalResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Portal URL
    #[prost(string, tag = "2")]
    pub portal_url: ::prost::alloc::string::String,
    /// Status message
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Guest clients response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GuestClientsResponse {
    /// Guest clients
    #[prost(message, repeated, tag = "1")]
    pub clients: ::prost::alloc::vec::Vec<GuestClient>,
    /// Total count
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
}
/// SSID
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ssid {
    /// SSID ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// SSID name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Radio band
    #[prost(enumeration = "RadioBand", tag = "3")]
    pub radio_band: i32,
    /// Security mode
    #[prost(enumeration = "SecurityMode", tag = "4")]
    pub security_mode: i32,
    /// Is enabled
    #[prost(bool, tag = "5")]
    pub enabled: bool,
    /// Is hidden
    #[prost(bool, tag = "6")]
    pub hidden: bool,
    /// Max clients
    #[prost(uint32, tag = "7")]
    pub max_clients: u32,
    /// Current clients
    #[prost(uint32, tag = "8")]
    pub current_clients: u32,
    /// VLAN ID
    #[prost(uint32, tag = "9")]
    pub vlan_id: u32,
    /// Is guest network
    #[prost(bool, tag = "10")]
    pub guest_network: bool,
    /// Captive portal
    #[prost(bool, tag = "11")]
    pub captive_portal_enabled: bool,
}
/// Client
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Client {
    /// Client MAC
    #[prost(message, optional, tag = "1")]
    pub mac_address: ::core::option::Option<super::common::MacAddress>,
    /// Client IP
    #[prost(message, optional, tag = "2")]
    pub ip_address: ::core::option::Option<super::common::IpAddress>,
    /// Hostname
    #[prost(string, tag = "3")]
    pub hostname: ::prost::alloc::string::String,
    /// Associated SSID
    #[prost(string, tag = "4")]
    pub ssid_id: ::prost::alloc::string::String,
    /// Signal strength
    #[prost(int32, tag = "5")]
    pub signal_strength_dbm: i32,
    /// TX rate
    #[prost(double, tag = "6")]
    pub tx_rate_mbps: f64,
    /// RX rate
    #[prost(double, tag = "7")]
    pub rx_rate_mbps: f64,
    /// Connection time
    #[prost(message, optional, tag = "8")]
    pub connected_at: ::core::option::Option<super::common::Timestamp>,
    /// Last seen
    #[prost(message, optional, tag = "9")]
    pub last_seen: ::core::option::Option<super::common::Timestamp>,
    /// Data usage
    #[prost(uint64, tag = "10")]
    pub data_usage_bytes: u64,
    /// Is blocked
    #[prost(bool, tag = "11")]
    pub blocked: bool,
}
/// Guest client
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GuestClient {
    /// Client MAC
    #[prost(message, optional, tag = "1")]
    pub mac_address: ::core::option::Option<super::common::MacAddress>,
    /// Is authorized
    #[prost(bool, tag = "2")]
    pub authorized: bool,
    /// Authorization expiry
    #[prost(message, optional, tag = "3")]
    pub authorized_until: ::core::option::Option<super::common::Timestamp>,
    /// Voucher code
    #[prost(string, tag = "4")]
    pub voucher_code: ::prost::alloc::string::String,
    /// Email (if email auth)
    #[prost(string, tag = "5")]
    pub email: ::prost::alloc::string::String,
}
/// Client event (for streaming)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientEvent {
    /// Event type
    #[prost(enumeration = "client_event::EventType", tag = "1")]
    pub event_type: i32,
    /// Client info
    #[prost(message, optional, tag = "2")]
    pub client: ::core::option::Option<Client>,
    /// Event timestamp
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
/// Nested message and enum types in `ClientEvent`.
pub mod client_event {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum EventType {
        EventUnknown = 0,
        EventConnected = 1,
        EventDisconnected = 2,
        EventRoamed = 3,
        EventBlocked = 4,
    }
    impl EventType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                EventType::EventUnknown => "EVENT_UNKNOWN",
                EventType::EventConnected => "EVENT_CONNECTED",
                EventType::EventDisconnected => "EVENT_DISCONNECTED",
                EventType::EventRoamed => "EVENT_ROAMED",
                EventType::EventBlocked => "EVENT_BLOCKED",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "EVENT_UNKNOWN" => Some(Self::EventUnknown),
                "EVENT_CONNECTED" => Some(Self::EventConnected),
                "EVENT_DISCONNECTED" => Some(Self::EventDisconnected),
                "EVENT_ROAMED" => Some(Self::EventRoamed),
                "EVENT_BLOCKED" => Some(Self::EventBlocked),
                _ => None,
            }
        }
    }
}
/// Radio band
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RadioBand {
    BandUnknown = 0,
    Band24ghz = 1,
    Band5ghz = 2,
    Band6ghz = 3,
}
impl RadioBand {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RadioBand::BandUnknown => "BAND_UNKNOWN",
            RadioBand::Band24ghz => "BAND_2_4GHZ",
            RadioBand::Band5ghz => "BAND_5GHZ",
            RadioBand::Band6ghz => "BAND_6GHZ",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BAND_UNKNOWN" => Some(Self::BandUnknown),
            "BAND_2_4GHZ" => Some(Self::Band24ghz),
            "BAND_5GHZ" => Some(Self::Band5ghz),
            "BAND_6GHZ" => Some(Self::Band6ghz),
            _ => None,
        }
    }
}
/// Security mode
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SecurityMode {
    SecurityUnknown = 0,
    SecurityOpen = 1,
    SecurityWpa2Psk = 2,
    SecurityWpa3Sae = 3,
    SecurityWpa2Wpa3Mixed = 4,
    SecurityWpa2Enterprise = 5,
    SecurityWpa3Enterprise = 6,
}
impl SecurityMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SecurityMode::SecurityUnknown => "SECURITY_UNKNOWN",
            SecurityMode::SecurityOpen => "SECURITY_OPEN",
            SecurityMode::SecurityWpa2Psk => "SECURITY_WPA2_PSK",
            SecurityMode::SecurityWpa3Sae => "SECURITY_WPA3_SAE",
            SecurityMode::SecurityWpa2Wpa3Mixed => "SECURITY_WPA2_WPA3_MIXED",
            SecurityMode::SecurityWpa2Enterprise => "SECURITY_WPA2_ENTERPRISE",
            SecurityMode::SecurityWpa3Enterprise => "SECURITY_WPA3_ENTERPRISE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SECURITY_UNKNOWN" => Some(Self::SecurityUnknown),
            "SECURITY_OPEN" => Some(Self::SecurityOpen),
            "SECURITY_WPA2_PSK" => Some(Self::SecurityWpa2Psk),
            "SECURITY_WPA3_SAE" => Some(Self::SecurityWpa3Sae),
            "SECURITY_WPA2_WPA3_MIXED" => Some(Self::SecurityWpa2Wpa3Mixed),
            "SECURITY_WPA2_ENTERPRISE" => Some(Self::SecurityWpa2Enterprise),
            "SECURITY_WPA3_ENTERPRISE" => Some(Self::SecurityWpa3Enterprise),
            _ => None,
        }
    }
}
/// Channel width
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ChannelWidth {
    WidthUnknown = 0,
    Width20mhz = 1,
    Width40mhz = 2,
    Width80mhz = 3,
    Width160mhz = 4,
}
impl ChannelWidth {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ChannelWidth::WidthUnknown => "WIDTH_UNKNOWN",
            ChannelWidth::Width20mhz => "WIDTH_20MHZ",
            ChannelWidth::Width40mhz => "WIDTH_40MHZ",
            ChannelWidth::Width80mhz => "WIDTH_80MHZ",
            ChannelWidth::Width160mhz => "WIDTH_160MHZ",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WIDTH_UNKNOWN" => Some(Self::WidthUnknown),
            "WIDTH_20MHZ" => Some(Self::Width20mhz),
            "WIDTH_40MHZ" => Some(Self::Width40mhz),
            "WIDTH_80MHZ" => Some(Self::Width80mhz),
            "WIDTH_160MHZ" => Some(Self::Width160mhz),
            _ => None,
        }
    }
}
/// WiFi standard
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WifiStandard {
    StandardUnknown = 0,
    /// WiFi 4
    Standard80211n = 1,
    /// WiFi 5
    Standard80211ac = 2,
    /// WiFi 6/6E
    Standard80211ax = 3,
}
impl WifiStandard {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            WifiStandard::StandardUnknown => "STANDARD_UNKNOWN",
            WifiStandard::Standard80211n => "STANDARD_802_11N",
            WifiStandard::Standard80211ac => "STANDARD_802_11AC",
            WifiStandard::Standard80211ax => "STANDARD_802_11AX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STANDARD_UNKNOWN" => Some(Self::StandardUnknown),
            "STANDARD_802_11N" => Some(Self::Standard80211n),
            "STANDARD_802_11AC" => Some(Self::Standard80211ac),
            "STANDARD_802_11AX" => Some(Self::Standard80211ax),
            _ => None,
        }
    }
}
/// Encryption type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EncryptionType {
    EncryptionUnknown = 0,
    EncryptionTkip = 1,
    EncryptionAes = 2,
    EncryptionCcmp = 3,
}
impl EncryptionType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            EncryptionType::EncryptionUnknown => "ENCRYPTION_UNKNOWN",
            EncryptionType::EncryptionTkip => "ENCRYPTION_TKIP",
            EncryptionType::EncryptionAes => "ENCRYPTION_AES",
            EncryptionType::EncryptionCcmp => "ENCRYPTION_CCMP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENCRYPTION_UNKNOWN" => Some(Self::EncryptionUnknown),
            "ENCRYPTION_TKIP" => Some(Self::EncryptionTkip),
            "ENCRYPTION_AES" => Some(Self::EncryptionAes),
            "ENCRYPTION_CCMP" => Some(Self::EncryptionCcmp),
            _ => None,
        }
    }
}
/// Captive portal authentication method
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CaptivePortalAuth {
    AuthNone = 0,
    AuthEmail = 1,
    AuthSms = 2,
    AuthVoucher = 3,
}
impl CaptivePortalAuth {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CaptivePortalAuth::AuthNone => "AUTH_NONE",
            CaptivePortalAuth::AuthEmail => "AUTH_EMAIL",
            CaptivePortalAuth::AuthSms => "AUTH_SMS",
            CaptivePortalAuth::AuthVoucher => "AUTH_VOUCHER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTH_NONE" => Some(Self::AuthNone),
            "AUTH_EMAIL" => Some(Self::AuthEmail),
            "AUTH_SMS" => Some(Self::AuthSms),
            "AUTH_VOUCHER" => Some(Self::AuthVoucher),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod wi_fi_ap_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// WiFi AP Service - Wireless network management
    #[derive(Debug, Clone)]
    pub struct WiFiApServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl WiFiApServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> WiFiApServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> WiFiApServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            WiFiApServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// SSID Management
        pub async fn create_ssid(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateSsidRequest>,
        ) -> std::result::Result<tonic::Response<super::SsidResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/CreateSSID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "CreateSSID"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_ssid(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateSsidRequest>,
        ) -> std::result::Result<tonic::Response<super::SsidResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/UpdateSSID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "UpdateSSID"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_ssid(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteSsidRequest>,
        ) -> std::result::Result<tonic::Response<super::SsidResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/DeleteSSID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "DeleteSSID"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_ssi_ds(
            &mut self,
            request: impl tonic::IntoRequest<super::ListSsiDsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SsidListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/ListSSIDs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "ListSSIDs"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn enable_ssid(
            &mut self,
            request: impl tonic::IntoRequest<super::EnableSsidRequest>,
        ) -> std::result::Result<tonic::Response<super::SsidResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/EnableSSID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "EnableSSID"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn disable_ssid(
            &mut self,
            request: impl tonic::IntoRequest<super::DisableSsidRequest>,
        ) -> std::result::Result<tonic::Response<super::SsidResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/DisableSSID",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "DisableSSID"));
            self.inner.unary(req, path, codec).await
        }
        /// Client Methods
        pub async fn get_clients(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClientsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetClients",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetClients"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_client_details(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClientDetailsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientDetailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetClientDetails",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetClientDetails"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn disconnect_client(
            &mut self,
            request: impl tonic::IntoRequest<super::DisconnectClientRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientActionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/DisconnectClient",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "DisconnectClient"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn block_client(
            &mut self,
            request: impl tonic::IntoRequest<super::BlockClientRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientActionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/BlockClient",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "BlockClient"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn unblock_client(
            &mut self,
            request: impl tonic::IntoRequest<super::UnblockClientRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientActionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/UnblockClient",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "UnblockClient"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Radio Methods
        pub async fn set_radio_settings(
            &mut self,
            request: impl tonic::IntoRequest<super::RadioSettingsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RadioSettingsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/SetRadioSettings",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "SetRadioSettings"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_radio_settings(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRadioSettingsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RadioSettingsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetRadioSettings",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetRadioSettings"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_channel(
            &mut self,
            request: impl tonic::IntoRequest<super::SetChannelRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChannelResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/SetChannel",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "SetChannel"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_tx_power(
            &mut self,
            request: impl tonic::IntoRequest<super::SetTxPowerRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TxPowerResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/SetTxPower",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "SetTxPower"));
            self.inner.unary(req, path, codec).await
        }
        /// Security Methods
        pub async fn set_security_mode(
            &mut self,
            request: impl tonic::IntoRequest<super::SecurityModeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SecurityModeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/SetSecurityMode",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "SetSecurityMode"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn update_psk(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdatePskRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SecurityModeResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/UpdatePSK",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "UpdatePSK"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn enable_wps(
            &mut self,
            request: impl tonic::IntoRequest<super::EnableWpsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WpsStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/EnableWPS",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "EnableWPS"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn disable_wps(
            &mut self,
            request: impl tonic::IntoRequest<super::DisableWpsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WpsStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/DisableWPS",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "DisableWPS"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_wps_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetWpsStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::WpsStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetWPSStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetWPSStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Statistics Methods
        pub async fn get_ap_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetApStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ApStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetAPStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetAPStats"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_client_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetClientStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClientStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetClientStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetClientStats"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_radio_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRadioStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RadioStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetRadioStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetRadioStats"),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn stream_client_events(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamClientEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::ClientEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/StreamClientEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.wifi_ap.WiFiAPService",
                        "StreamClientEvents",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Guest Network
        pub async fn create_guest_network(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateGuestNetworkRequest>,
        ) -> std::result::Result<tonic::Response<super::SsidResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/CreateGuestNetwork",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.wifi_ap.WiFiAPService",
                        "CreateGuestNetwork",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn configure_captive_portal(
            &mut self,
            request: impl tonic::IntoRequest<super::CaptivePortalRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CaptivePortalResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/ConfigureCaptivePortal",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.wifi_ap.WiFiAPService",
                        "ConfigureCaptivePortal",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_guest_clients(
            &mut self,
            request: impl tonic::IntoRequest<super::GetGuestClientsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GuestClientsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.wifi_ap.WiFiAPService/GetGuestClients",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("safeops.wifi_ap.WiFiAPService", "GetGuestClients"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
