// This file is @generated by prost-build.
/// Create backup request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateBackupRequest {
    /// Backup name
    #[prost(string, tag = "1")]
    pub backup_name: ::prost::alloc::string::String,
    /// Backup type
    #[prost(enumeration = "BackupType", tag = "2")]
    pub backup_type: i32,
    /// Components to backup
    #[prost(enumeration = "BackupComponent", repeated, tag = "3")]
    pub components: ::prost::alloc::vec::Vec<i32>,
    /// Backup description
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    /// Enable compression
    #[prost(bool, tag = "5")]
    pub compression_enabled: bool,
    /// Enable encryption
    #[prost(bool, tag = "6")]
    pub encryption_enabled: bool,
}
/// Schedule backup request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleBackupRequest {
    /// Backup name
    #[prost(string, tag = "1")]
    pub backup_name: ::prost::alloc::string::String,
    /// Cron expression
    #[prost(string, tag = "2")]
    pub schedule_cron: ::prost::alloc::string::String,
    /// Backup type
    #[prost(enumeration = "BackupType", tag = "3")]
    pub backup_type: i32,
    /// Components to backup
    #[prost(enumeration = "BackupComponent", repeated, tag = "4")]
    pub components: ::prost::alloc::vec::Vec<i32>,
    /// Retention period
    #[prost(uint32, tag = "5")]
    pub retention_days: u32,
    /// Enable schedule
    #[prost(bool, tag = "6")]
    pub enabled: bool,
}
/// Cancel scheduled backup request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CancelScheduledBackupRequest {
    /// Schedule ID to cancel
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
}
/// List backups request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListBackupsRequest {
    /// Filter by type
    #[prost(enumeration = "BackupType", tag = "1")]
    pub backup_type: i32,
    /// Start of date range
    #[prost(message, optional, tag = "2")]
    pub start_date: ::core::option::Option<super::common::Timestamp>,
    /// End of date range
    #[prost(message, optional, tag = "3")]
    pub end_date: ::core::option::Option<super::common::Timestamp>,
    /// Filter by component
    #[prost(enumeration = "BackupComponent", tag = "4")]
    pub component: i32,
    /// Pagination
    #[prost(message, optional, tag = "5")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Get backup details request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBackupDetailsRequest {
    /// Backup ID
    #[prost(string, tag = "1")]
    pub backup_id: ::prost::alloc::string::String,
}
/// Delete backup request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteBackupRequest {
    /// Backup ID to delete
    #[prost(string, tag = "1")]
    pub backup_id: ::prost::alloc::string::String,
    /// Also delete from storage
    #[prost(bool, tag = "2")]
    pub delete_from_storage: bool,
}
/// Restore backup request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RestoreBackupRequest {
    /// Backup ID to restore
    #[prost(string, tag = "1")]
    pub backup_id: ::prost::alloc::string::String,
    /// Components to restore
    #[prost(enumeration = "BackupComponent", repeated, tag = "2")]
    pub components_to_restore: ::prost::alloc::vec::Vec<i32>,
    /// Point-in-time restore
    #[prost(message, optional, tag = "3")]
    pub restore_point_in_time: ::core::option::Option<super::common::Timestamp>,
    /// Dry run (test only)
    #[prost(bool, tag = "4")]
    pub dry_run: bool,
}
/// Validate backup request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateBackupRequest {
    /// Backup ID to validate
    #[prost(string, tag = "1")]
    pub backup_id: ::prost::alloc::string::String,
}
/// Get restore status request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRestoreStatusRequest {
    /// Restore operation ID
    #[prost(string, tag = "1")]
    pub restore_id: ::prost::alloc::string::String,
}
/// Backup policy request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupPolicyRequest {
    /// Enable auto backups
    #[prost(bool, tag = "1")]
    pub auto_backup_enabled: bool,
    /// Full backup frequency (cron)
    #[prost(string, tag = "2")]
    pub full_backup_frequency: ::prost::alloc::string::String,
    /// Incremental frequency (cron)
    #[prost(string, tag = "3")]
    pub incremental_frequency: ::prost::alloc::string::String,
    /// Max retention days
    #[prost(uint32, tag = "4")]
    pub max_retention_days: u32,
    /// Max backup count
    #[prost(uint32, tag = "5")]
    pub max_backup_count: u32,
}
/// Get backup policy request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBackupPolicyRequest {}
/// Retention policy request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetentionPolicyRequest {
    /// Daily backups to keep
    #[prost(uint32, tag = "1")]
    pub daily_backups_to_keep: u32,
    /// Weekly backups to keep
    #[prost(uint32, tag = "2")]
    pub weekly_backups_to_keep: u32,
    /// Monthly backups to keep
    #[prost(uint32, tag = "3")]
    pub monthly_backups_to_keep: u32,
}
/// Get retention policy request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRetentionPolicyRequest {}
/// Storage config request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageConfigRequest {
    /// Storage type
    #[prost(enumeration = "StorageType", tag = "1")]
    pub storage_type: i32,
    /// Connection string
    #[prost(string, tag = "2")]
    pub connection_string: ::prost::alloc::string::String,
    /// Credentials (encrypted)
    #[prost(string, tag = "3")]
    pub credentials: ::prost::alloc::string::String,
    /// Bucket/container name
    #[prost(string, tag = "4")]
    pub bucket_name: ::prost::alloc::string::String,
    /// Path prefix
    #[prost(string, tag = "5")]
    pub path_prefix: ::prost::alloc::string::String,
}
/// Test storage connection request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TestStorageConnectionRequest {
    /// Storage type to test
    #[prost(enumeration = "StorageType", tag = "1")]
    pub storage_type: i32,
}
/// Get storage status request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStorageStatusRequest {}
/// Get backup stats request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBackupStatsRequest {
    /// Start time
    #[prost(message, optional, tag = "1")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// End time
    #[prost(message, optional, tag = "2")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
}
/// Get storage utilization request
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStorageUtilizationRequest {}
/// Backup response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupResponse {
    /// Backup ID
    #[prost(string, tag = "1")]
    pub backup_id: ::prost::alloc::string::String,
    /// Backup status
    #[prost(enumeration = "BackupStatus", tag = "2")]
    pub status: i32,
    /// Progress percentage
    #[prost(uint32, tag = "3")]
    pub progress_percent: u32,
    /// ETA
    #[prost(message, optional, tag = "4")]
    pub estimated_completion_time: ::core::option::Option<super::common::Timestamp>,
    /// Status message
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
/// Schedule response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScheduleResponse {
    /// Schedule ID
    #[prost(string, tag = "1")]
    pub schedule_id: ::prost::alloc::string::String,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "2")]
    pub status: i32,
    /// Next run time
    #[prost(message, optional, tag = "3")]
    pub next_run_time: ::core::option::Option<super::common::Timestamp>,
    /// Status message
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
/// Backup list response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupListResponse {
    /// List of backups
    #[prost(message, repeated, tag = "1")]
    pub backups: ::prost::alloc::vec::Vec<Backup>,
    /// Total count
    #[prost(uint32, tag = "2")]
    pub total_count: u32,
    /// Pagination info
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::Pagination>,
}
/// Backup detail response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupDetailResponse {
    /// Backup metadata
    #[prost(message, optional, tag = "1")]
    pub backup: ::core::option::Option<Backup>,
    /// Backup size
    #[prost(uint64, tag = "2")]
    pub size_bytes: u64,
    /// Checksum
    #[prost(string, tag = "3")]
    pub checksum: ::prost::alloc::string::String,
    /// Is encrypted
    #[prost(bool, tag = "4")]
    pub encrypted: bool,
    /// Is compressed
    #[prost(bool, tag = "5")]
    pub compressed: bool,
    /// Storage location
    #[prost(string, tag = "6")]
    pub storage_location: ::prost::alloc::string::String,
}
/// Restore response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RestoreResponse {
    /// Restore operation ID
    #[prost(string, tag = "1")]
    pub restore_id: ::prost::alloc::string::String,
    /// Restore status
    #[prost(enumeration = "RestoreStatus", tag = "2")]
    pub status: i32,
    /// Progress percentage
    #[prost(uint32, tag = "3")]
    pub progress_percent: u32,
    /// Status message
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
/// Restore status response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RestoreStatusResponse {
    /// Restore operation ID
    #[prost(string, tag = "1")]
    pub restore_id: ::prost::alloc::string::String,
    /// Current status
    #[prost(enumeration = "RestoreStatus", tag = "2")]
    pub status: i32,
    /// Progress percentage
    #[prost(uint32, tag = "3")]
    pub progress_percent: u32,
    /// Completed components
    #[prost(string, repeated, tag = "4")]
    pub restored_components: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Pending components
    #[prost(string, repeated, tag = "5")]
    pub pending_components: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Error if failed
    #[prost(string, tag = "6")]
    pub error_message: ::prost::alloc::string::String,
}
/// Validate backup response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateBackupResponse {
    /// Is valid
    #[prost(bool, tag = "1")]
    pub is_valid: bool,
    /// Checksum matches
    #[prost(bool, tag = "2")]
    pub checksum_match: bool,
    /// Missing components
    #[prost(string, repeated, tag = "3")]
    pub missing_components: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Corrupted files
    #[prost(string, repeated, tag = "4")]
    pub corrupted_files: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Validation details
    #[prost(string, tag = "5")]
    pub validation_message: ::prost::alloc::string::String,
}
/// Backup policy response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupPolicyResponse {
    /// Auto backup enabled
    #[prost(bool, tag = "1")]
    pub auto_backup_enabled: bool,
    /// Full backup frequency
    #[prost(string, tag = "2")]
    pub full_backup_frequency: ::prost::alloc::string::String,
    /// Incremental frequency
    #[prost(string, tag = "3")]
    pub incremental_frequency: ::prost::alloc::string::String,
    /// Max retention days
    #[prost(uint32, tag = "4")]
    pub max_retention_days: u32,
    /// Max backup count
    #[prost(uint32, tag = "5")]
    pub max_backup_count: u32,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "6")]
    pub status: i32,
}
/// Retention policy response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetentionPolicyResponse {
    /// Daily backups
    #[prost(uint32, tag = "1")]
    pub daily_backups_to_keep: u32,
    /// Weekly backups
    #[prost(uint32, tag = "2")]
    pub weekly_backups_to_keep: u32,
    /// Monthly backups
    #[prost(uint32, tag = "3")]
    pub monthly_backups_to_keep: u32,
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "4")]
    pub status: i32,
}
/// Storage config response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageConfigResponse {
    /// Operation status
    #[prost(enumeration = "super::common::Status", tag = "1")]
    pub status: i32,
    /// Status message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Storage connection test response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageConnectionTestResponse {
    /// Connection successful
    #[prost(bool, tag = "1")]
    pub connected: bool,
    /// Connection latency
    #[prost(uint32, tag = "2")]
    pub latency_ms: u32,
    /// Error if failed
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
/// Storage status response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageStatusResponse {
    /// Storage type
    #[prost(enumeration = "StorageType", tag = "1")]
    pub storage_type: i32,
    /// Is connected
    #[prost(bool, tag = "2")]
    pub connected: bool,
    /// Total space
    #[prost(uint64, tag = "3")]
    pub total_space_bytes: u64,
    /// Used space
    #[prost(uint64, tag = "4")]
    pub used_space_bytes: u64,
    /// Available space
    #[prost(uint64, tag = "5")]
    pub available_space_bytes: u64,
    /// Storage latency
    #[prost(uint32, tag = "6")]
    pub latency_ms: u32,
}
/// Backup statistics response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BackupStatsResponse {
    /// Total backups
    #[prost(uint32, tag = "1")]
    pub total_backups: u32,
    /// Total size
    #[prost(uint64, tag = "2")]
    pub total_size_bytes: u64,
    /// Successful count
    #[prost(uint32, tag = "3")]
    pub successful_backups_count: u32,
    /// Failed count
    #[prost(uint32, tag = "4")]
    pub failed_backups_count: u32,
    /// Last backup time
    #[prost(message, optional, tag = "5")]
    pub last_backup_time: ::core::option::Option<super::common::Timestamp>,
    /// Next scheduled
    #[prost(message, optional, tag = "6")]
    pub next_scheduled_backup: ::core::option::Option<super::common::Timestamp>,
    /// Size breakdown
    #[prost(map = "string, uint64", tag = "7")]
    pub size_by_component: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        u64,
    >,
}
/// Storage utilization response
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StorageUtilizationResponse {
    /// Total backup size
    #[prost(uint64, tag = "1")]
    pub total_backup_size_bytes: u64,
    /// Available storage
    #[prost(uint64, tag = "2")]
    pub available_storage_bytes: u64,
    /// Utilization %
    #[prost(double, tag = "3")]
    pub utilization_percent: f64,
    /// Number of backups
    #[prost(uint32, tag = "4")]
    pub backup_count: u32,
    /// Oldest backup time
    #[prost(message, optional, tag = "5")]
    pub oldest_backup: ::core::option::Option<super::common::Timestamp>,
}
/// Backup
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Backup {
    /// Backup ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Backup name
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Backup type
    #[prost(enumeration = "BackupType", tag = "3")]
    pub r#type: i32,
    /// Included components
    #[prost(enumeration = "BackupComponent", repeated, tag = "4")]
    pub components: ::prost::alloc::vec::Vec<i32>,
    /// Backup size
    #[prost(uint64, tag = "5")]
    pub size_bytes: u64,
    /// Creation time
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
    /// Completion time
    #[prost(message, optional, tag = "7")]
    pub completed_at: ::core::option::Option<super::common::Timestamp>,
    /// Checksum
    #[prost(string, tag = "8")]
    pub checksum: ::prost::alloc::string::String,
    /// Is encrypted
    #[prost(bool, tag = "9")]
    pub encrypted: bool,
    /// Is compressed
    #[prost(bool, tag = "10")]
    pub compressed: bool,
    /// Storage location
    #[prost(string, tag = "11")]
    pub storage_location: ::prost::alloc::string::String,
    /// Description
    #[prost(string, tag = "12")]
    pub description: ::prost::alloc::string::String,
    /// Current status
    #[prost(enumeration = "BackupStatus", tag = "13")]
    pub status: i32,
}
/// Backup component
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BackupComponent {
    ComponentUnknown = 0,
    ComponentConfigs = 1,
    ComponentDatabase = 2,
    ComponentLogs = 3,
    ComponentCertificates = 4,
    ComponentUserData = 5,
    ComponentFirewallRules = 6,
    ComponentDnsZones = 7,
    ComponentDhcpLeases = 8,
}
impl BackupComponent {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            BackupComponent::ComponentUnknown => "COMPONENT_UNKNOWN",
            BackupComponent::ComponentConfigs => "COMPONENT_CONFIGS",
            BackupComponent::ComponentDatabase => "COMPONENT_DATABASE",
            BackupComponent::ComponentLogs => "COMPONENT_LOGS",
            BackupComponent::ComponentCertificates => "COMPONENT_CERTIFICATES",
            BackupComponent::ComponentUserData => "COMPONENT_USER_DATA",
            BackupComponent::ComponentFirewallRules => "COMPONENT_FIREWALL_RULES",
            BackupComponent::ComponentDnsZones => "COMPONENT_DNS_ZONES",
            BackupComponent::ComponentDhcpLeases => "COMPONENT_DHCP_LEASES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPONENT_UNKNOWN" => Some(Self::ComponentUnknown),
            "COMPONENT_CONFIGS" => Some(Self::ComponentConfigs),
            "COMPONENT_DATABASE" => Some(Self::ComponentDatabase),
            "COMPONENT_LOGS" => Some(Self::ComponentLogs),
            "COMPONENT_CERTIFICATES" => Some(Self::ComponentCertificates),
            "COMPONENT_USER_DATA" => Some(Self::ComponentUserData),
            "COMPONENT_FIREWALL_RULES" => Some(Self::ComponentFirewallRules),
            "COMPONENT_DNS_ZONES" => Some(Self::ComponentDnsZones),
            "COMPONENT_DHCP_LEASES" => Some(Self::ComponentDhcpLeases),
            _ => None,
        }
    }
}
/// Backup type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BackupType {
    TypeUnknown = 0,
    TypeFull = 1,
    TypeIncremental = 2,
    TypeDifferential = 3,
}
impl BackupType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            BackupType::TypeUnknown => "TYPE_UNKNOWN",
            BackupType::TypeFull => "TYPE_FULL",
            BackupType::TypeIncremental => "TYPE_INCREMENTAL",
            BackupType::TypeDifferential => "TYPE_DIFFERENTIAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TYPE_UNKNOWN" => Some(Self::TypeUnknown),
            "TYPE_FULL" => Some(Self::TypeFull),
            "TYPE_INCREMENTAL" => Some(Self::TypeIncremental),
            "TYPE_DIFFERENTIAL" => Some(Self::TypeDifferential),
            _ => None,
        }
    }
}
/// Backup status
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BackupStatus {
    StatusUnknown = 0,
    StatusPending = 1,
    StatusInProgress = 2,
    StatusCompleted = 3,
    StatusFailed = 4,
    StatusValidating = 5,
}
impl BackupStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            BackupStatus::StatusUnknown => "STATUS_UNKNOWN",
            BackupStatus::StatusPending => "STATUS_PENDING",
            BackupStatus::StatusInProgress => "STATUS_IN_PROGRESS",
            BackupStatus::StatusCompleted => "STATUS_COMPLETED",
            BackupStatus::StatusFailed => "STATUS_FAILED",
            BackupStatus::StatusValidating => "STATUS_VALIDATING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STATUS_UNKNOWN" => Some(Self::StatusUnknown),
            "STATUS_PENDING" => Some(Self::StatusPending),
            "STATUS_IN_PROGRESS" => Some(Self::StatusInProgress),
            "STATUS_COMPLETED" => Some(Self::StatusCompleted),
            "STATUS_FAILED" => Some(Self::StatusFailed),
            "STATUS_VALIDATING" => Some(Self::StatusValidating),
            _ => None,
        }
    }
}
/// Restore status
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RestoreStatus {
    RestoreUnknown = 0,
    RestorePending = 1,
    RestoreInProgress = 2,
    RestoreCompleted = 3,
    RestoreFailed = 4,
    RestoreRolledBack = 5,
}
impl RestoreStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            RestoreStatus::RestoreUnknown => "RESTORE_UNKNOWN",
            RestoreStatus::RestorePending => "RESTORE_PENDING",
            RestoreStatus::RestoreInProgress => "RESTORE_IN_PROGRESS",
            RestoreStatus::RestoreCompleted => "RESTORE_COMPLETED",
            RestoreStatus::RestoreFailed => "RESTORE_FAILED",
            RestoreStatus::RestoreRolledBack => "RESTORE_ROLLED_BACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RESTORE_UNKNOWN" => Some(Self::RestoreUnknown),
            "RESTORE_PENDING" => Some(Self::RestorePending),
            "RESTORE_IN_PROGRESS" => Some(Self::RestoreInProgress),
            "RESTORE_COMPLETED" => Some(Self::RestoreCompleted),
            "RESTORE_FAILED" => Some(Self::RestoreFailed),
            "RESTORE_ROLLED_BACK" => Some(Self::RestoreRolledBack),
            _ => None,
        }
    }
}
/// Storage type
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum StorageType {
    StorageUnknown = 0,
    StorageLocal = 1,
    StorageS3 = 2,
    StorageAzureBlob = 3,
    StorageGcs = 4,
    StorageFtp = 5,
    StorageSftp = 6,
    StorageNfs = 7,
    StorageSmb = 8,
}
impl StorageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            StorageType::StorageUnknown => "STORAGE_UNKNOWN",
            StorageType::StorageLocal => "STORAGE_LOCAL",
            StorageType::StorageS3 => "STORAGE_S3",
            StorageType::StorageAzureBlob => "STORAGE_AZURE_BLOB",
            StorageType::StorageGcs => "STORAGE_GCS",
            StorageType::StorageFtp => "STORAGE_FTP",
            StorageType::StorageSftp => "STORAGE_SFTP",
            StorageType::StorageNfs => "STORAGE_NFS",
            StorageType::StorageSmb => "STORAGE_SMB",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "STORAGE_UNKNOWN" => Some(Self::StorageUnknown),
            "STORAGE_LOCAL" => Some(Self::StorageLocal),
            "STORAGE_S3" => Some(Self::StorageS3),
            "STORAGE_AZURE_BLOB" => Some(Self::StorageAzureBlob),
            "STORAGE_GCS" => Some(Self::StorageGcs),
            "STORAGE_FTP" => Some(Self::StorageFtp),
            "STORAGE_SFTP" => Some(Self::StorageSftp),
            "STORAGE_NFS" => Some(Self::StorageNfs),
            "STORAGE_SMB" => Some(Self::StorageSmb),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod backup_restore_service_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Backup and Restore Service - System backup and disaster recovery
    #[derive(Debug, Clone)]
    pub struct BackupRestoreServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl BackupRestoreServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> BackupRestoreServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> BackupRestoreServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            BackupRestoreServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Backup Methods
        pub async fn create_backup(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateBackupRequest>,
        ) -> std::result::Result<tonic::Response<super::BackupResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/CreateBackup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "CreateBackup",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn schedule_backup(
            &mut self,
            request: impl tonic::IntoRequest<super::ScheduleBackupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/ScheduleBackup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "ScheduleBackup",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn cancel_scheduled_backup(
            &mut self,
            request: impl tonic::IntoRequest<super::CancelScheduledBackupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ScheduleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/CancelScheduledBackup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "CancelScheduledBackup",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_backups(
            &mut self,
            request: impl tonic::IntoRequest<super::ListBackupsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BackupListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/ListBackups",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "ListBackups",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_backup_details(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBackupDetailsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BackupDetailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/GetBackupDetails",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "GetBackupDetails",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn delete_backup(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteBackupRequest>,
        ) -> std::result::Result<tonic::Response<super::BackupResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/DeleteBackup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "DeleteBackup",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Restore Methods
        pub async fn restore_backup(
            &mut self,
            request: impl tonic::IntoRequest<super::RestoreBackupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RestoreResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/RestoreBackup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "RestoreBackup",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn validate_backup(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateBackupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateBackupResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/ValidateBackup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "ValidateBackup",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_restore_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRestoreStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RestoreStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/GetRestoreStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "GetRestoreStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Configuration
        pub async fn set_backup_policy(
            &mut self,
            request: impl tonic::IntoRequest<super::BackupPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BackupPolicyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/SetBackupPolicy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "SetBackupPolicy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_backup_policy(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBackupPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BackupPolicyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/GetBackupPolicy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "GetBackupPolicy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn set_retention_policy(
            &mut self,
            request: impl tonic::IntoRequest<super::RetentionPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetentionPolicyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/SetRetentionPolicy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "SetRetentionPolicy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_retention_policy(
            &mut self,
            request: impl tonic::IntoRequest<super::GetRetentionPolicyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RetentionPolicyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/GetRetentionPolicy",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "GetRetentionPolicy",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Storage Methods
        pub async fn configure_storage(
            &mut self,
            request: impl tonic::IntoRequest<super::StorageConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StorageConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/ConfigureStorage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "ConfigureStorage",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn test_storage_connection(
            &mut self,
            request: impl tonic::IntoRequest<super::TestStorageConnectionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StorageConnectionTestResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/TestStorageConnection",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "TestStorageConnection",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_storage_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStorageStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StorageStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/GetStorageStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "GetStorageStatus",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Statistics
        pub async fn get_backup_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBackupStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::BackupStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/GetBackupStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "GetBackupStats",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        pub async fn get_storage_utilization(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStorageUtilizationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StorageUtilizationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/safeops.backup_restore.BackupRestoreService/GetStorageUtilization",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "safeops.backup_restore.BackupRestoreService",
                        "GetStorageUtilization",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
