//! # SafeOps Shared Library
//!
//! High-performance utilities and shared code for SafeOps firewall services.
//! Provides packet processing, IP utilities, fast hashing, lock-free data structures,
//! SIMD optimizations, and Protocol Buffer integration.
//!
//! ## Usage
//!
//! For most use cases, import the prelude:
//!
//! ```
//! use safeops_shared::prelude::*;
//! ```
//!
//! For specific functionality, import individual modules:
//!
//! ```
//! use safeops_shared::ip_utils::parse_cidr;
//! use safeops_shared::hash_utils::xxhash64;
//! use safeops_shared::metrics::MetricsRegistry;
//! ```

#![warn(missing_docs)]
#![warn(clippy::all)]
#![forbid(unsafe_code)]

// ============================================================================
// Module Declarations
// ============================================================================

/// Error types and Result alias
pub mod error;

/// IP address parsing and CIDR utilities
pub mod ip_utils;

/// Fast hashing algorithms (xxHash, aHash)
pub mod hash_utils;

/// Object pooling for zero-allocation performance
pub mod memory_pool;

/// Lock-free data structures for concurrent access
pub mod lock_free;

/// SIMD-optimized packet parsing
pub mod simd_utils;

/// Time and timestamp utilities
pub mod time_utils;

/// Protocol Buffer helper functions
pub mod proto_utils;

/// Prometheus metrics collection
pub mod metrics;

/// Buffer pooling for packet processing
pub mod buffer_pool;

// ============================================================================
// Generated Proto Code
// ============================================================================

/// Generated Protocol Buffer types and gRPC clients
///
/// This module contains auto-generated code from proto files:
/// - `common` - Common types (Timestamp, Status, Metadata, etc.)
/// - `firewall` - Firewall service definitions
/// - `threat_intel` - Threat intelligence service definitions
#[allow(clippy::all)]
#[allow(missing_docs)]
#[allow(warnings)]
pub mod proto {
    // Proto files are generated by build.rs at compile time
    // They will be included here automatically when cargo build runs
    // For now, this module exists as a placeholder until proto compilation
}

// ============================================================================
// Root Re-exports - Common Types at Crate Root
// ============================================================================

// Error types - most commonly used
pub use error::{Error as SafeOpsError, Result};

// Note: Specific type re-exports will be added as modules are implemented
// Examples for future:
// pub use ip_utils::{parse_cidr, validate_ip};
// pub use hash_utils::{xxhash64, ahash_hash};
// pub use memory_pool::MemoryPool;
// pub use metrics::MetricsRegistry;

// ============================================================================
// Prelude Module - Convenience Imports
// ============================================================================

/// Prelude module containing the most commonly used types and functions.
///
/// Import this module to get all essential types in one line:
///
/// ```
/// use safeops_shared::prelude::*;
/// ```
///
/// This provides:
/// - Error types (`SafeOpsError`, `Result`)
/// - IP utilities (when implemented)
/// - Hash functions (when implemented)
/// - Metrics registry (when implemented)
/// - Common traits and functions
pub mod prelude {
    //! Convenient re-exports of commonly used types

    // Error handling - always needed
    pub use crate::error::{Error as SafeOpsError, Result};
    
    // When modules are fully implemented, add:
    // pub use crate::ip_utils::{parse_cidr, validate_ip, IPAddress};
    // pub use crate::hash_utils::{xxhash64, ahash_hash};
    // pub use crate::time_utils::{current_timestamp, parse_duration};
    // pub use crate::metrics::MetricsRegistry;
    // pub use crate::memory_pool::MemoryPool;
}
