/**
 * ioctl_handler.h - IOCTL Handler Header
 */

#ifndef _IOCTL_HANDLER_H_
#define _IOCTL_HANDLER_H_

#include "driver.h"

// IOCTL Codes
#define FILE_DEVICE_SAFEOPS         0x8000

#define IOCTL_SAFEOPS_GET_VERSION       CTL_CODE(FILE_DEVICE_SAFEOPS, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_SAFEOPS_GET_STATISTICS    CTL_CODE(FILE_DEVICE_SAFEOPS, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_SAFEOPS_ADD_RULE          CTL_CODE(FILE_DEVICE_SAFEOPS, 0x802, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_SAFEOPS_REMOVE_RULE       CTL_CODE(FILE_DEVICE_SAFEOPS, 0x803, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_SAFEOPS_LIST_RULES        CTL_CODE(FILE_DEVICE_SAFEOPS, 0x804, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_SAFEOPS_MAP_SHARED_MEMORY CTL_CODE(FILE_DEVICE_SAFEOPS, 0x805, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_SAFEOPS_SET_NIC_ZONE      CTL_CODE(FILE_DEVICE_SAFEOPS, 0x806, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_SAFEOPS_GET_NIC_INFO      CTL_CODE(FILE_DEVICE_SAFEOPS, 0x807, METHOD_BUFFERED, FILE_READ_ACCESS)
#define IOCTL_SAFEOPS_ENABLE_RSS        CTL_CODE(FILE_DEVICE_SAFEOPS, 0x808, METHOD_BUFFERED, FILE_WRITE_ACCESS)

// Request/Response structures
#pragma pack(push, 1)

typedef struct _SAFEOPS_VERSION_INFO {
    USHORT Major;
    USHORT Minor;
    USHORT Patch;
    USHORT Build;
    CHAR VersionString[32];
} SAFEOPS_VERSION_INFO, *PSAFEOPS_VERSION_INFO;

typedef struct _SAFEOPS_STATISTICS {
    ULONGLONG PacketsProcessed;
    ULONGLONG PacketsAllowed;
    ULONGLONG PacketsDropped;
    ULONGLONG BytesProcessed;
    ULONG FilterRuleCount;
    LONG ConnectionCount;
    ULONG DroppedPackets;
    LARGE_INTEGER DriverStartTime;
    LARGE_INTEGER CurrentTime;
} SAFEOPS_STATISTICS, *PSAFEOPS_STATISTICS;

typedef struct _NIC_ZONE_REQUEST {
    ULONG NicIndex;
    NIC_ZONE Zone;
} NIC_ZONE_REQUEST, *PNIC_ZONE_REQUEST;

typedef struct _RSS_REQUEST {
    BOOLEAN Enable;
    ULONG CpuCount;
} RSS_REQUEST, *PRSS_REQUEST;

#pragma pack(pop)

#endif // _IOCTL_HANDLER_H_
